// Generated by scripts/build.mjs — do not edit. The source is @jannchie/slides.

// ../slides/dist/deck-tree-CrWrpH_9.js
function e(e2) {
  switch (e2) {
    case "section":
    case "body":
      return "section";
    case "div":
      return "div";
    case "h1":
    case "h2":
    case "h3":
    case "p":
    case "ul":
    case "ol":
    case "li":
      return "text";
    case "span":
    case "a":
    case "b":
    case "i":
    case "u":
    case "s":
      return "inline";
    case "img":
      return "img";
    case "table":
      return "table";
    case "tr":
      return "row";
    case "th":
    case "td":
      return "cell";
    case "x-shape":
      return "shape";
    case "x-icon":
      return "icon";
    case "x-connector":
      return "connector";
    case "hr":
      return "hr";
    case "svg":
      return "svg";
    default:
      return;
  }
}
var t = [
  "section",
  "div",
  "text",
  "inline",
  "img",
  "table",
  "row",
  "cell",
  "shape",
  "icon",
  "connector",
  "hr",
  "svg"
];
var n = [
  "div",
  "text",
  "img",
  "table",
  "cell",
  "shape",
  "icon",
  "hr",
  "svg"
];
var r = [
  "div",
  "text",
  "img",
  "table",
  "shape",
  "icon",
  "hr",
  "svg",
  "connector"
];
var i = ["section", "div"];
var a = [
  "section",
  "div",
  "text",
  "table",
  "cell"
];
var o = [
  "section",
  "div",
  "text",
  "img",
  "table",
  "cell",
  "icon"
];
var s = (e2) => ({ value: e2 });
var c = (e2) => ({ refused: e2 });
var l = /^-?(?:\d+\.?\d*|\.\d+)$/;
function u(e2) {
  return l.test(e2) ? Number(e2) : void 0;
}
function d(e2) {
  return String(Math.round(e2 * 1e3) / 1e3);
}
function f(e2) {
  let t2 = /^(-?(?:\d+\.?\d*|\.\d+))(px|pt)?$/i.exec(e2.trim());
  if (t2 === null) return;
  let n2 = Number(t2[1]);
  return t2[2]?.toLowerCase() === "pt" ? n2 * 4 / 3 : n2;
}
var p = (e2) => e2 === 0 ? "0" : `${d(e2)}px`;
function m(e2, t2 = -4096, n2 = 8192) {
  let r2 = f(e2);
  return r2 === void 0 ? c(/(em|rem|vw|vh|vmin|vmax|ch|ex)$/i.test(e2) ? "only px lengths" : "a length in px") : r2 < t2 || r2 > n2 ? c(`a length from ${t2} to ${n2}px`) : s(p(r2));
}
function h(e2) {
  let t2 = /^(-?(?:\d+\.?\d*|\.\d+))%$/.exec(e2.trim());
  return t2 === null ? void 0 : Number(t2[1]);
}
function g(e2, t2 = []) {
  let n2 = e2.trim().toLowerCase();
  if (t2.includes(n2)) return s(n2);
  let r2 = h(e2);
  return r2 === void 0 ? m(e2) : s(`${d(r2)}%`);
}
function _(e2) {
  return (t2) => {
    let n2 = t2.trim().toLowerCase();
    return e2.includes(n2) ? s(n2) : c(e2.join(" | "));
  };
}
function v(e2, t2, n2 = false) {
  return (r2) => {
    let i2 = u(r2.trim());
    return i2 === void 0 || i2 < e2 || i2 > t2 || n2 && !Number.isInteger(i2) ? c(`a ${n2 ? "whole " : ""}number from ${e2} to ${t2}`) : s(d(i2));
  };
}
function y(e2, t2) {
  let n2 = [], r2 = 0, i2, a2 = false, o2 = "";
  for (let s2 of e2) i2 === void 0 ? s2 === '"' || s2 === "'" ? (i2 = s2, o2 += s2) : (s2 === "(" ? r2 += 1 : s2 === ")" && --r2, (t2 === "," ? s2 === "," : /\s/.test(s2)) && r2 === 0 ? (o2.trim() !== "" && n2.push(o2.trim()), o2 = "") : o2 += s2) : (o2 += s2, a2 ? a2 = false : s2 === "\\" ? a2 = true : s2 === i2 && (i2 = void 0));
  return o2.trim() !== "" && n2.push(o2.trim()), n2;
}
var b = new Set("aliceblue antiquewhite aqua aquamarine azure beige bisque black blanchedalmond blue blueviolet brown burlywood cadetblue chartreuse chocolate coral cornflowerblue cornsilk crimson cyan darkblue darkcyan darkgoldenrod darkgray darkgreen darkgrey darkkhaki darkmagenta darkolivegreen darkorange darkorchid darkred darksalmon darkseagreen darkslateblue darkslategray darkslategrey darkturquoise darkviolet deeppink deepskyblue dimgray dimgrey dodgerblue firebrick floralwhite forestgreen fuchsia gainsboro ghostwhite gold goldenrod gray green greenyellow grey honeydew hotpink indianred indigo ivory khaki lavender lavenderblush lawngreen lemonchiffon lightblue lightcoral lightcyan lightgoldenrodyellow lightgray lightgreen lightgrey lightpink lightsalmon lightseagreen lightskyblue lightslategray lightslategrey lightsteelblue lightyellow lime limegreen linen magenta maroon mediumaquamarine mediumblue mediumorchid mediumpurple mediumseagreen mediumslateblue mediumspringgreen mediumturquoise mediumvioletred midnightblue mintcream mistyrose moccasin navajowhite navy oldlace olive olivedrab orange orangered orchid palegoldenrod palegreen paleturquoise palevioletred papayawhip peachpuff peru pink plum powderblue purple rebeccapurple red rosybrown royalblue saddlebrown salmon sandybrown seagreen seashell sienna silver skyblue slateblue slategray slategrey snow springgreen steelblue tan teal thistle tomato turquoise violet wheat white whitesmoke yellow yellowgreen transparent".split(" "));
var ee = /^(rgba?|hsla?)\(\s*[-\d.%\s,/deg]+\)$/i;
function x(e2) {
  let t2 = e2.trim().toLowerCase();
  return /^#(?:[0-9a-f]{3,4}|[0-9a-f]{6}|[0-9a-f]{8})$/.test(t2) || ee.test(t2) || b.has(t2);
}
function te(e2) {
  let t2 = e2.trim();
  return /currentcolor|var\(/i.test(t2) ? c("a colour written out: #hex, rgb(), hsl() or a name \u2014 not currentColor or var()") : x(t2) ? s(t2.toLowerCase()) : c("a colour: #hex, rgb(), hsl() or a name");
}
function ne(e2) {
  return /^-?(?:\d+\.?\d*|\.\d+)(deg|turn|rad)$/i.test(e2.trim()) || e2.trim() === "0";
}
var re = /^(repeating-)?(linear|radial)-gradient\((.*)\)$/is;
function ie(e2) {
  let t2 = re.exec(e2.trim());
  if (t2 === null) return c("a colour or a linear-gradient() / radial-gradient()");
  let n2 = y(t2[3], ","), r2 = n2.filter((e3) => x(y(e3, " ")[0] ?? ""));
  if (r2.length < 2 || r2.length > 8) return c("a gradient of 2 to 8 colour stops");
  for (let e3 of n2) {
    let [t3, ...n3] = y(e3, " ");
    if (x(t3 ?? "")) {
      if (!n3.every((e4) => h(e4) !== void 0 || f(e4) !== void 0)) return c("gradient stops as a colour and up to two positions in % or px");
      continue;
    }
    let r3 = y(e3, " ");
    if (!(r3.length === 1 && ne(r3[0]) || r3[0] === "to" && r3.slice(1).every((e4) => [
      "top",
      "bottom",
      "left",
      "right"
    ].includes(e4)) || r3.every((e4) => [
      "circle",
      "ellipse",
      "at",
      "center",
      "top",
      "bottom",
      "left",
      "right",
      "closest-side",
      "farthest-corner"
    ].includes(e4) || h(e4) !== void 0 || f(e4) !== void 0))) return c("a gradient's direction as an angle, `to <side>`, or a radial shape `at X% Y%`");
  }
  return s(e2.trim().replace(/\s+/g, " "));
}
function ae(e2) {
  let t2 = e2.trim();
  if (/url\(/i.test(t2)) return c("a colour or a gradient \u2014 an image is an <img>");
  if (x(t2)) return s(t2.toLowerCase());
  let n2 = y(t2, ",");
  if (n2.length > 2 || n2.length === 2 && !x(n2[1])) return c("one gradient, optionally with a colour under it");
  let r2 = ie(n2[0]);
  return "refused" in r2 ? r2 : s(n2.length === 2 ? `${r2.value}, ${n2[1].toLowerCase()}` : r2.value);
}
var oe = [
  "solid",
  "dashed",
  "dotted",
  "double",
  "none"
];
function S(e2) {
  let t2 = e2.trim().toLowerCase();
  if (t2 === "none" || t2 === "0") return s("none");
  let n2 = y(t2, " "), r2 = n2.find((e3) => oe.includes(e3)), i2 = n2.find((e3) => f(e3) !== void 0), a2 = n2.find((e3) => e3 !== r2 && e3 !== i2);
  if (r2 === void 0) return c("a stroke with its style word: `2px solid #ccc`");
  if (n2.length > 3 || a2 !== void 0 && !x(a2)) return c("a width, a style and a colour: `2px solid #ccc`");
  let o2 = i2 === void 0 ? 1 : f(i2);
  return o2 < 0 || o2 > 32 ? c("a stroke from 0 to 32px") : s([
    p(o2),
    r2,
    ...a2 === void 0 ? [] : [a2]
  ].join(" "));
}
function se(e2, t2, n2 = false) {
  return (r2) => {
    let i2 = y(r2.trim(), " ");
    if (i2.length < 1 || i2.length > 4) return c("one to four lengths in px");
    let a2 = i2.map((r3) => n2 && h(r3) !== void 0 ? s(`${d(h(r3))}%`) : m(r3, e2, t2));
    return a2.find((e3) => "refused" in e3) ?? s(a2.map((e3) => e3.value).join(" "));
  };
}
function ce(e2) {
  return (t2) => {
    if (t2.trim().toLowerCase() === "none") return s("none");
    let n2 = y(t2, ",");
    if (n2.length > 8) return c("at most eight shadows");
    for (let t3 of n2) {
      let n3 = y(t3, " ").filter((t4) => !(e2 && t4.toLowerCase() === "inset")), r2 = n3.filter((e3) => x(e3)), i2 = n3.filter((e3) => f(e3) !== void 0);
      if (r2.length !== 1 || i2.length < 2 || i2.length > (e2 ? 4 : 3) || r2.length + i2.length !== n3.length) return c(`shadows as x y${e2 ? " [blur [spread]]" : " [blur]"} and one colour`);
    }
    return s(n2.map((e3) => e3.replace(/\s+/g, " ").trim()).join(", "));
  };
}
var le = /^(translate|translateX|translateY|rotate|scale|skew|skewX|skewY)\(([^()]*)\)$/;
function ue(e2) {
  let t2 = e2.trim();
  if (t2 === "none") return s("none");
  for (let e3 of y(t2, " ")) {
    let t3 = le.exec(e3);
    if (t3 === null) return c("translate(), rotate(), scale() and skew() only");
    let n2 = y(t3[2], ","), r2 = t3[1];
    if (!(r2.startsWith("translate") ? n2.length >= 1 && n2.length <= (r2 === "translate" ? 2 : 1) && n2.every((e4) => f(e4) !== void 0 || h(e4) !== void 0) : r2 === "rotate" || r2.startsWith("skew") ? n2.length >= 1 && n2.length <= (r2 === "skew" ? 2 : 1) && n2.every(ne) : n2.length === 1 && u(n2[0]) !== void 0 && Number(n2[0]) >= 0.1 && Number(n2[0]) <= 4)) return c(`${r2}() with ${r2.startsWith("translate") ? "px or % offsets" : r2 === "scale" ? "one factor" : "an angle"}`);
  }
  return s(t2.replace(/\s+/g, " "));
}
var de = /^(blur|brightness|contrast|saturate|grayscale|sepia|invert|hue-rotate|opacity)\(([^()]*)\)$/;
function fe(e2) {
  let t2 = e2.trim();
  return t2 === "none" ? s("none") : y(t2, " ").every((e3) => de.test(e3)) ? s(t2.replace(/\s+/g, " ")) : c("blur(), brightness(), contrast(), saturate(), grayscale(), sepia(), invert(), hue-rotate() and opacity()");
}
function pe(e2) {
  let t2 = y(e2, ",");
  return t2.length === 0 || t2.some((e3) => !/^(["'])[^"';{}<>]+\1$|^[A-Za-z][\w -]*$/.test(e3)) ? c("font names, quoted when they have spaces, then a generic family") : s(t2.join(", "));
}
function me(e2) {
  let t2 = e2.trim().toLowerCase();
  if (t2 === "normal") return s("400");
  if (t2 === "bold") return s("700");
  let n2 = u(t2);
  return n2 !== void 0 && n2 >= 100 && n2 <= 900 && n2 % 100 == 0 ? s(String(n2)) : c("100 to 900 in hundreds, normal or bold");
}
function he(e2) {
  let t2 = e2.trim(), n2 = u(t2);
  if (n2 !== void 0) return n2 >= 0.5 && n2 <= 4 ? s(d(n2)) : c("a factor from 0.5 to 4");
  let r2 = h(t2);
  return r2 === void 0 ? m(t2, 4, 1600) : r2 >= 50 && r2 <= 400 ? s(d(r2 / 100)) : c("a factor from 0.5 to 4");
}
function ge(e2) {
  let t2 = e2.trim().toLowerCase();
  if (t2 === "normal") return s("normal");
  let n2 = /^(-?(?:\d+\.?\d*|\.\d+))em$/.exec(t2);
  return n2 === null ? m(t2, -24, 32) : s(`${d(Number(n2[1]))}em`);
}
function _e(e2) {
  let t2 = /^span\s+(\d+)$/.exec(e2.trim());
  return t2 !== null && Number(t2[1]) >= 1 && Number(t2[1]) <= 24 ? s(`span ${Number(t2[1])}`) : c("`span N`: grid children fill in order");
}
function ve(e2) {
  let t2 = e2.trim().replace(/\s+/g, " "), n2 = y(t2.replace(/repeat\(\s*(\d+)\s*,\s*([^()]+)\)/g, (e3, t3, n3) => Array.from({ length: Math.min(Number(t3), 25) }, () => n3.trim()).join(" ")), " ");
  return n2.length === 0 || n2.length > 24 ? c("1 to 24 tracks") : n2.every((e3) => e3 === "auto" || /^\d+(\.\d+)?fr$/.test(e3) || f(e3) !== void 0 || h(e3) !== void 0) ? s(t2) : c("tracks in px, %, fr or auto \u2014 no minmax(), auto-fill or names");
}
function ye(e2) {
  let t2 = e2.trim().toLowerCase();
  if (["none", "auto"].includes(t2)) return s(t2);
  let n2 = y(t2, " "), r2 = (e3) => e3 === "auto" || e3 === "content" || f(e3) !== void 0 || h(e3) !== void 0;
  return n2.length >= 1 && n2.length <= 3 && u(n2[0]) !== void 0 && (n2.length < 2 || u(n2[1]) !== void 0 || n2.length === 2 && r2(n2[1])) && (n2.length < 3 || r2(n2[2])) ? s(t2) : c("none, auto, or grow [shrink] [basis]");
}
function be(e2) {
  let t2 = e2.trim();
  return /^\d+(\.\d+)?(\s*\/\s*\d+(\.\d+)?)?$/.test(t2) ? s(t2.replace(/\s*\/\s*/, " / ")) : c("N or N / N");
}
function xe(e2) {
  let t2 = e2.trim(), n2 = /^calc\(\s*(-?[\d.]+)%\s*([+-])\s*([\d.]+)px\s*\)$/.exec(t2);
  return n2 === null ? g(t2, ["auto"]) : s(`calc(${d(Number(n2[1]))}% ${n2[2]} ${d(Number(n2[3]))}px)`);
}
function Se(e2) {
  let t2 = y(e2.trim().toLowerCase(), " "), n2 = [
    "none",
    "underline",
    "line-through"
  ], r2 = [
    "solid",
    "double",
    "dotted",
    "dashed",
    "wavy"
  ];
  return t2.length >= 1 && n2.includes(t2[0]) && t2.slice(1).every((e3) => r2.includes(e3) || x(e3)) ? s(t2.join(" ")) : c("none, underline or line-through, then a style and a colour");
}
function Ce(e2) {
  let t2 = y(e2.trim(), " "), n2 = t2[0] === void 0 ? void 0 : f(t2[0]);
  return t2.length === 2 && n2 !== void 0 && n2 >= 0 && n2 <= 8 && x(t2[1]) ? s(`${p(n2)} ${t2[1].toLowerCase()}`) : c("a width up to 8px and a colour");
}
function we(e2) {
  let t2 = e2.trim().toLowerCase();
  return t2 === "transparent" || t2 === "currentcolor" ? s(t2) : c("transparent, with background-clip:text");
}
var C = [
  "start",
  "center",
  "end",
  "stretch",
  "baseline",
  "flex-start",
  "flex-end"
];
var Te = {
  position: {
    targets: r,
    read: _(["absolute", "relative"]),
    takes: "absolute | relative"
  },
  left: {
    targets: r,
    read: xe,
    takes: "px, %, calc(% \xB1 px) or auto"
  },
  top: {
    targets: r,
    read: xe,
    takes: "px, %, calc(% \xB1 px) or auto"
  },
  right: {
    targets: r,
    read: (e2) => g(e2, ["auto"]),
    takes: "px, % or auto"
  },
  bottom: {
    targets: r,
    read: (e2) => g(e2, ["auto"]),
    takes: "px, % or auto"
  },
  width: {
    targets: [...n, "section"],
    read: (e2) => g(e2, ["auto"]),
    takes: "px, % or auto"
  },
  height: {
    targets: [...n, "section"],
    read: (e2) => g(e2, ["auto"]),
    takes: "px, % or auto"
  },
  "min-width": {
    targets: n,
    read: (e2) => g(e2, ["min-content", "max-content"]),
    takes: "px, min-content or max-content"
  },
  "min-height": {
    targets: n,
    read: (e2) => m(e2, 0),
    takes: "px"
  },
  "max-width": {
    targets: n,
    read: (e2) => m(e2, 0),
    takes: "px"
  },
  "max-height": {
    targets: n,
    read: (e2) => m(e2, 0),
    takes: "px"
  },
  display: {
    targets: i,
    read: _([
      "flex",
      "grid",
      "none"
    ]),
    takes: "flex | grid | none"
  },
  "flex-direction": {
    targets: i,
    read: _([
      "row",
      "column",
      "row-reverse",
      "column-reverse"
    ]),
    takes: "row | column [-reverse]"
  },
  "flex-wrap": {
    targets: i,
    read: _(["wrap", "nowrap"]),
    takes: "wrap | nowrap"
  },
  gap: {
    targets: i,
    read: (e2) => m(e2, 0, 512),
    takes: "one length from 0 to 512px"
  },
  "align-items": {
    targets: i,
    read: _(C),
    takes: C.join(" | ")
  },
  "justify-content": {
    targets: i,
    read: _([
      "start",
      "center",
      "end",
      "space-between",
      "space-around",
      "space-evenly",
      "flex-start",
      "flex-end"
    ]),
    takes: "start | center | end | space-between | space-around | space-evenly"
  },
  "justify-items": {
    targets: i,
    read: _([
      "start",
      "center",
      "end",
      "stretch"
    ]),
    takes: "start | center | end | stretch"
  },
  "align-self": {
    targets: n,
    read: _([...C, "auto"]),
    takes: `${C.join(" | ")} | auto`
  },
  "justify-self": {
    targets: n,
    read: _([
      "start",
      "center",
      "end",
      "stretch",
      "auto"
    ]),
    takes: "start | center | end | stretch | auto"
  },
  flex: {
    targets: n,
    read: ye,
    takes: "none, auto, or grow [shrink] [basis]"
  },
  "flex-grow": {
    targets: n,
    read: v(0, 100),
    takes: "a number"
  },
  "flex-shrink": {
    targets: n,
    read: v(0, 100),
    takes: "a number"
  },
  "flex-basis": {
    targets: n,
    read: (e2) => g(e2, ["auto"]),
    takes: "px or auto"
  },
  "grid-template-columns": {
    targets: i,
    read: ve,
    takes: "tracks in px, %, fr or auto"
  },
  "grid-template-rows": {
    targets: i,
    read: ve,
    takes: "tracks in px, %, fr or auto"
  },
  "grid-column": {
    targets: n,
    read: _e,
    takes: "span N"
  },
  "grid-row": {
    targets: n,
    read: _e,
    takes: "span N"
  },
  "aspect-ratio": {
    targets: n,
    read: be,
    takes: "N or N / N"
  },
  padding: {
    targets: [...a, "inline"],
    read: se(0, 256),
    takes: "one to four lengths from 0 to 256px"
  },
  overflow: {
    targets: ["div", "section"],
    read: _(["hidden", "visible"]),
    takes: "hidden | visible"
  },
  "font-family": {
    targets: [...a, "inline"],
    read: pe,
    takes: "font names, then a generic family"
  },
  "font-size": {
    targets: [...a, "inline"],
    read: (e2) => m(e2, 8, 400),
    takes: "a size from 8 to 400px"
  },
  "font-weight": {
    targets: [...a, "inline"],
    read: me,
    takes: "100 to 900, normal or bold"
  },
  "font-style": {
    targets: [...a, "inline"],
    read: _(["normal", "italic"]),
    takes: "normal | italic"
  },
  "line-height": {
    targets: a,
    read: he,
    takes: "a factor from 0.5 to 4, or px"
  },
  "letter-spacing": {
    targets: [...a, "inline"],
    read: ge,
    takes: "px, em or normal"
  },
  "text-align": {
    targets: a,
    read: _([
      "left",
      "center",
      "right",
      "justify",
      "start",
      "end"
    ]),
    takes: "left | center | right | justify"
  },
  "text-transform": {
    targets: [...a, "inline"],
    read: _([
      "none",
      "uppercase",
      "lowercase",
      "capitalize"
    ]),
    takes: "none | uppercase | lowercase | capitalize"
  },
  "white-space": {
    targets: a,
    read: _(["normal", "nowrap"]),
    takes: "normal | nowrap"
  },
  "text-decoration": {
    targets: [...a, "inline"],
    read: Se,
    takes: "none | underline | line-through [style] [colour]"
  },
  "font-variant-numeric": {
    targets: [...a, "inline"],
    read: _(["normal", "tabular-nums"]),
    takes: "normal | tabular-nums"
  },
  "-webkit-text-stroke": {
    targets: ["text"],
    read: Ce,
    takes: "a width and a colour"
  },
  "-webkit-text-fill-color": {
    targets: ["text", "inline"],
    read: we,
    takes: "transparent"
  },
  "background-clip": {
    targets: ["text"],
    read: _(["text", "border-box"]),
    takes: "text"
  },
  color: {
    targets: [
      ...a,
      "inline",
      "icon",
      "connector",
      "hr"
    ],
    read: te,
    takes: "a colour"
  },
  background: {
    targets: [
      ...o,
      "row",
      "shape",
      "hr",
      "inline"
    ],
    read: ae,
    takes: "a colour or one gradient"
  },
  border: {
    targets: [
      ...o,
      "shape",
      "hr",
      "connector"
    ],
    read: S,
    takes: "`2px solid #ccc`"
  },
  "border-top": {
    targets: [...o, "hr"],
    read: S,
    takes: "`2px solid #ccc`"
  },
  "border-right": {
    targets: o,
    read: S,
    takes: "`2px solid #ccc`"
  },
  "border-bottom": {
    targets: o,
    read: S,
    takes: "`2px solid #ccc`"
  },
  "border-left": {
    targets: o,
    read: S,
    takes: "`2px solid #ccc`"
  },
  "border-radius": {
    targets: [
      ...o,
      "shape",
      "inline"
    ],
    read: se(0, 2048, true),
    takes: "one to four lengths, or 50%"
  },
  "box-shadow": {
    targets: [...o, "shape"],
    read: ce(true),
    takes: "x y [blur [spread]] colour, up to eight"
  },
  "text-shadow": {
    targets: [...a, "inline"],
    read: ce(false),
    takes: "x y [blur] colour, up to eight"
  },
  opacity: {
    targets: t,
    read: v(0, 1),
    takes: "0 to 1"
  },
  transform: {
    targets: [...r, "section"],
    read: ue,
    takes: "translate(), rotate(), scale(), skew()"
  },
  filter: {
    targets: [
      "div",
      "text",
      "img",
      "shape",
      "svg"
    ],
    read: fe,
    takes: "blur(), brightness(), \u2026 \u2014 no url()"
  },
  "backdrop-filter": {
    targets: ["div", "text"],
    read: fe,
    takes: "blur(), brightness(), \u2026 \u2014 no url()"
  },
  "mix-blend-mode": {
    targets: [
      "div",
      "text",
      "img",
      "shape",
      "svg"
    ],
    read: _([
      "normal",
      "multiply",
      "screen",
      "overlay",
      "darken",
      "lighten"
    ]),
    takes: "normal | multiply | screen | overlay | darken | lighten"
  },
  "object-fit": {
    targets: ["img"],
    read: _([
      "cover",
      "contain",
      "fill"
    ]),
    takes: "cover | contain"
  },
  "object-position": {
    targets: ["img"],
    read: (e2) => y(e2, " ").every((e3) => h(e3) !== void 0 || [
      "center",
      "top",
      "bottom",
      "left",
      "right"
    ].includes(e3)) ? s(e2.trim()) : c("X% Y%"),
    takes: "X% Y%"
  }
};
var Ee = {
  "background-color": "background",
  "background-image": "background",
  "grid-gap": "gap",
  "row-gap": "gap",
  "column-gap": "gap",
  "text-fill-color": "-webkit-text-fill-color",
  "-webkit-background-clip": "background-clip"
};
var De = /* @__PURE__ */ new Set([
  "box-sizing",
  "-webkit-font-smoothing",
  "-moz-osx-font-smoothing",
  "font-feature-settings",
  "text-rendering",
  "cursor",
  "user-select",
  "pointer-events",
  "list-style",
  "list-style-type"
]);
var Oe = {
  margin: "space boxes with the parent's gap and padding",
  "margin-top": "space boxes with the parent's gap and padding",
  "margin-bottom": "space boxes with the parent's gap and padding",
  "margin-left": "space boxes with the parent's gap and padding",
  "margin-right": "space boxes with the parent's gap and padding",
  "z-index": "later elements paint over earlier ones: order them instead",
  float: "use a flex row",
  "border-color": "write the whole stroke: `border:2px solid #ccc`",
  "border-width": "write the whole stroke: `border:2px solid #ccc`",
  "border-style": "write the whole stroke: `border:2px solid #ccc`",
  animation: "use data-build-in on a pinned element",
  transition: "use data-transition on the slide",
  "vertical-align": "align with a flex container's align-items",
  "word-break": "size the box to its longest word",
  "text-wrap": "size the box to its text"
};
function ke(t2, n2) {
  let r2 = e(t2), i2 = [];
  for (let e2 of je(n2)) {
    let n3 = e2.indexOf(":");
    if (n3 === -1) {
      i2.push({
        property: e2.trim(),
        dropped: "is not a declaration: write `property:value`"
      });
      continue;
    }
    let a2 = e2.slice(0, n3).trim().toLowerCase(), o2 = e2.slice(n3 + 1).trim();
    /!important$/i.test(o2) && (o2 = o2.replace(/\s*!important$/i, "")), a2 !== "" && (a2 === "font" ? i2.push(...Ae(t2, o2)) : i2.push(w(r2, t2, Ee[a2] ?? a2, o2)));
  }
  return i2;
}
function w(e2, t2, n2, r2) {
  if (De.has(n2) || n2.startsWith("margin") && /^0(px)?(\s+0(px)?)*$/.test(r2)) return {
    property: n2,
    dropped: "",
    silent: true
  };
  let i2 = Te[n2];
  if (i2 === void 0) {
    let e3 = Oe[n2];
    return {
      property: n2,
      dropped: `is not in the slide subset${e3 === void 0 ? "" : `: ${e3}`}`
    };
  }
  if (e2 === void 0 || !i2.targets.includes(e2)) return {
    property: n2,
    dropped: `does not apply to <${t2}>`
  };
  if (/var\(|url\(|expression\(|\\/i.test(r2)) return {
    property: n2,
    dropped: `${JSON.stringify(r2)}: no var(), url(), expressions or escapes`
  };
  let a2 = i2.read(r2);
  return "refused" in a2 ? {
    property: n2,
    dropped: `${JSON.stringify(r2)} is not ${a2.refused}`
  } : {
    property: n2,
    value: a2.value
  };
}
function Ae(t2, n2) {
  let r2 = e(t2), i2 = /^((?:(?:italic|normal|bold|[1-9]00)\s+)*)([\d.]+(?:px|pt)?)(?:\s*\/\s*([\d.]+(?:px|%)?))?\s+(.+)$/i.exec(n2.trim());
  if (i2 === null) return [{
    property: "font",
    dropped: `${JSON.stringify(n2)} is not [italic] [weight] size[/line-height] family`
  }];
  let a2 = i2[1].trim().split(/\s+/).filter(Boolean);
  return [
    ...a2.includes("italic") ? [["font-style", "italic"]] : [],
    ...a2.filter((e2) => e2 !== "italic" && e2 !== "normal").map((e2) => ["font-weight", e2]),
    ["font-size", i2[2]],
    ...i2[3] === void 0 ? [] : [["line-height", i2[3]]],
    ["font-family", i2[4]]
  ].map(([e2, n3]) => w(r2, t2, e2, n3));
}
function je(e2) {
  let t2 = [], n2 = 0, r2, i2 = false, a2 = "";
  for (let o2 of e2) if (r2 !== void 0) a2 += o2, i2 ? i2 = false : o2 === "\\" ? i2 = true : o2 === r2 && (r2 = void 0);
  else {
    if (o2 === '"' || o2 === "'") r2 = o2;
    else if (o2 === "(") n2 += 1;
    else if (o2 === ")") --n2;
    else if (o2 === ";" && n2 === 0) {
      t2.push(a2), a2 = "";
      continue;
    }
    a2 += o2;
  }
  return t2.push(a2), t2.filter((e3) => e3.trim() !== "");
}
function Me(e2) {
  return Object.entries(e2).map(([e3, t2]) => `${e3}:${t2}`).join(";");
}
function Ne(e2) {
  return e2 in Te;
}
function Pe(t2, n2) {
  let r2 = e(t2);
  return r2 !== void 0 && Te[n2]?.targets.includes(r2) === true;
}
function Fe(t2, n2, r2) {
  let i2 = w(e(t2), t2, n2, r2);
  return "value" in i2 ? i2.value : void 0;
}
var Ie = /* @__PURE__ */ new Set([
  "svg",
  "style",
  "script",
  "aside"
]);
var Le = {
  amp: "&",
  lt: "<",
  gt: ">",
  quot: '"',
  apos: "'",
  nbsp: "\xA0",
  ensp: "\u2002",
  emsp: "\u2003",
  thinsp: "\u2009",
  mdash: "\u2014",
  ndash: "\u2013",
  hellip: "\u2026",
  middot: "\xB7",
  bull: "\u2022",
  copy: "\xA9",
  reg: "\xAE",
  trade: "\u2122",
  times: "\xD7",
  divide: "\xF7",
  minus: "\u2212",
  plusmn: "\xB1",
  deg: "\xB0",
  laquo: "\xAB",
  raquo: "\xBB",
  lsquo: "\u2018",
  rsquo: "\u2019",
  ldquo: "\u201C",
  rdquo: "\u201D",
  rarr: "\u2192",
  larr: "\u2190",
  uarr: "\u2191",
  darr: "\u2193",
  harr: "\u2194",
  rArr: "\u21D2",
  le: "\u2264",
  ge: "\u2265",
  ne: "\u2260",
  asymp: "\u2248",
  infin: "\u221E",
  check: "\u2713",
  cross: "\u2717",
  star: "\u2606",
  hearts: "\u2665",
  euro: "\u20AC",
  pound: "\xA3",
  yen: "\xA5",
  cent: "\xA2",
  sect: "\xA7",
  para: "\xB6",
  dagger: "\u2020",
  frac12: "\xBD",
  frac14: "\xBC",
  frac34: "\xBE",
  sup2: "\xB2",
  sup3: "\xB3",
  micro: "\xB5",
  alpha: "\u03B1",
  beta: "\u03B2",
  gamma: "\u03B3",
  delta: "\u03B4",
  Delta: "\u0394",
  epsilon: "\u03B5",
  theta: "\u03B8",
  lambda: "\u03BB",
  mu: "\u03BC",
  pi: "\u03C0",
  sigma: "\u03C3",
  Sigma: "\u03A3",
  omega: "\u03C9",
  Omega: "\u03A9"
};
function T(e2) {
  return e2.replace(/&(#x[0-9a-f]+|#\d+|[a-z][a-z0-9]*);/gi, (e3, t2) => {
    if (t2[0] === "#") {
      let n2 = t2[1] === "x" || t2[1] === "X" ? parseInt(t2.slice(2), 16) : parseInt(t2.slice(1), 10);
      return Number.isFinite(n2) && n2 > 0 && n2 <= 1114111 ? String.fromCodePoint(n2) : e3;
    }
    return Le[t2] ?? e3;
  });
}
function E(e2) {
  return e2.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
function D(e2) {
  return e2.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;");
}
function Re(e2) {
  let t2 = [], n2 = [0];
  for (let t3 = 0; t3 < e2.length; t3 += 1) e2.charCodeAt(t3) === 10 && n2.push(t3 + 1);
  let r2 = (e3) => {
    let t3 = 0, r3 = n2.length - 1;
    for (; t3 < r3; ) {
      let i3 = t3 + r3 + 1 >> 1;
      n2[i3] <= e3 ? t3 = i3 : r3 = i3 - 1;
    }
    return {
      line: t3 + 1,
      column: e3 - n2[t3] + 1
    };
  }, i2 = 0, a2 = 0, o2 = (n3) => {
    n3 > a2 && t2.push({
      type: "text",
      text: T(e2.slice(a2, n3)),
      ...r2(a2)
    });
  };
  for (; i2 < e2.length; ) {
    let n3 = e2.indexOf("<", i2);
    if (n3 === -1) break;
    if (e2.startsWith("<!--", n3)) {
      o2(n3);
      let t3 = e2.indexOf("-->", n3 + 4);
      i2 = t3 === -1 ? e2.length : t3 + 3, a2 = i2;
      continue;
    }
    if (e2.startsWith("<!", n3) || e2.startsWith("<?", n3)) {
      o2(n3);
      let t3 = e2.indexOf(">", n3);
      i2 = t3 === -1 ? e2.length : t3 + 1, a2 = i2;
      continue;
    }
    let s2 = /^<\/([a-zA-Z][\w-]*)\s*>/.exec(e2.slice(n3, n3 + 80));
    if (s2 !== null) {
      o2(n3), t2.push({
        type: "end",
        name: s2[1].toLowerCase(),
        ...r2(n3)
      }), i2 = n3 + s2[0].length, a2 = i2;
      continue;
    }
    let c2 = Be(e2, n3);
    if (c2 === void 0) i2 = n3 + 1;
    else {
      if (o2(n3), Ie.has(c2.name) && !c2.selfClosing) {
        let { inner: a3, after: o3, closed: s3 } = Ve(e2, c2.name, c2.end);
        t2.push({
          type: "raw",
          name: c2.name,
          attributes: c2.attributes,
          inner: a3,
          closed: s3,
          ...r2(n3)
        }), i2 = o3;
      } else t2.push({
        type: "start",
        name: c2.name,
        attributes: c2.attributes,
        selfClosing: c2.selfClosing,
        ...r2(n3)
      }), i2 = c2.end;
      a2 = i2;
    }
  }
  return o2(e2.length), t2;
}
var ze = /([^\s"'>/=]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'=<>`]+)))?/y;
function Be(e2, t2) {
  let n2 = /^<([a-zA-Z][\w-]*)/.exec(e2.slice(t2, t2 + 64));
  if (n2 === null) return;
  let r2 = [], i2 = t2 + n2[0].length, a2 = n2[1].toLowerCase() === "svg";
  for (; i2 < e2.length; ) {
    let t3 = /^\s*/.exec(e2.slice(i2, i2 + 256));
    if (i2 += t3[0].length, e2.startsWith("/>", i2)) return {
      name: n2[1].toLowerCase(),
      attributes: r2,
      selfClosing: true,
      end: i2 + 2
    };
    if (e2[i2] === ">") return {
      name: n2[1].toLowerCase(),
      attributes: r2,
      selfClosing: false,
      end: i2 + 1
    };
    ze.lastIndex = i2;
    let o2 = ze.exec(e2);
    if (o2 === null) {
      if (e2[i2] === "/") {
        i2 += 1;
        continue;
      }
      return;
    }
    r2.push({
      name: a2 ? o2[1] : o2[1].toLowerCase(),
      value: T(o2[2] ?? o2[3] ?? o2[4] ?? "")
    }), i2 += o2[0].length;
  }
}
function Ve(e2, t2, n2) {
  let r2 = RegExp(`<(/?)(${t2}|section)\\b[^>]*?(/?)>`, "gi"), i2 = 1;
  r2.lastIndex = n2;
  for (let a2 = r2.exec(e2); a2 !== null; a2 = r2.exec(e2)) {
    if (a2[2].toLowerCase() !== t2) return {
      inner: e2.slice(n2, a2.index),
      after: a2.index,
      closed: false
    };
    if (a2[1] === "/" ? --i2 : a2[3] !== "/" && t2 === "svg" && (i2 += 1), i2 === 0) return {
      inner: e2.slice(n2, a2.index),
      after: a2.index + a2[0].length,
      closed: true
    };
  }
  return {
    inner: e2.slice(n2),
    after: e2.length,
    closed: false
  };
}
var O = {
  activity: '<path d="M2.5 11.5H5.82a1 1 0 00.93-.63L9.13 4.93a.37.37 0 01.69.02l4.36 13.1a.37.37 0 00.69.02l2.38-5.94a1 1 0 01.93-.63H21.5"/>',
  add: '<path d="M12 4.5v15M4.5 12h15"/>',
  analytics: '<path d="M3 20.5H21m-16.5 0v-5a1 1 0 011-1h1a1 1 0 011 1v5m3 0v-7a1 1 0 011-1h1a1 1 0 011 1v7m3 0v-4a1 1 0 011-1h1a1 1 0 011 1v4M6 8.5L12 5l6 2.5"/><path d="M6 8.5H6M12 5h0m6 2.5h0" stroke-width="2"/>',
  api: '<path d="M10 4.5H9A1.5 1.5 0 007.5 6v4a2 2 0 01-2 2 2 2 0 012 2v4A1.5 1.5 0 009 19.5h1m4-15h1A1.5 1.5 0 0116.5 6v4a2 2 0 002 2 2 2 0 00-2 2v4A1.5 1.5 0 0115 19.5H14"/>',
  application: '<path d="M5 3.5H9A1.5 1.5 0 0110.5 5V9A1.5 1.5 0 019 10.5H5A1.5 1.5 0 013.5 9V5A1.5 1.5 0 015 3.5zm10 0h4A1.5 1.5 0 0120.5 5V9A1.5 1.5 0 0119 10.5H15A1.5 1.5 0 0113.5 9V5A1.5 1.5 0 0115 3.5zM5 13.5H9A1.5 1.5 0 0110.5 15v4A1.5 1.5 0 019 20.5H5A1.5 1.5 0 013.5 19V15A1.5 1.5 0 015 13.5zm10 0h4A1.5 1.5 0 0120.5 15v4A1.5 1.5 0 0119 20.5H15A1.5 1.5 0 0113.5 19V15A1.5 1.5 0 0115 13.5z"/>',
  "arrow-down": '<path d="M12 4.3V18.64M5.4 13.1l6.25 6.25a.5.5 0 00.7 0L18.6 13.1"/>',
  "arrow-left": '<path d="M19.7 12H5.36M10.9 5.4L4.65 11.65a.5.5 0 000 .7L10.9 18.6"/>',
  "arrow-right": '<path d="M4.3 12H18.64M13.1 5.4l6.25 6.25a.5.5 0 010 .7L13.1 18.6"/>',
  "arrow-up": '<path d="M12 19.7V5.36M5.4 10.9l6.25-6.25a.5.5 0 01.7 0L18.6 10.9"/>',
  "arrow-up-right": '<path d="M5.3 18.7L17.75 6.25M9.15 5.5H18a.5.5 0 01.5.5v8.85"/>',
  badge: '<path d="M6 9A6 6 0 1018 9 6 6 0 106 9m3.46 5.44L7.75 21l2.5-1.25 1-4.8m3.29-.51L16.25 21l-2.5-1.25-1-4.8"/><path d="M9 9a3 3 0 106 0A3 3 0 109 9" stroke-width="1.05"/>',
  book: '<path d="M12 5.75c-2-1.5-5.25-2-9.25-2v14.5c4 0 7.25.5 9.25 2zm0 0c2-1.5 5.25-2 9.25-2v14.5c-4 0-7.25.5-9.25 2z"/>',
  bot: '<path d="M7.5 8.5h9a2 2 0 012 2v6a2 2 0 01-2 2h-9a2 2 0 01-2-2v-6a2 2 0 012-2zm4.5 0v-3m-2.5 7v2m5-2v2M3.5 12v3m17-3v3"/>',
  building: '<path d="M2.5 20.5h19m-15 0V6.5a2 2 0 012-2h7a2 2 0 012 2v14m-7 0V18A1.5 1.5 0 0112 16.5h0A1.5 1.5 0 0113.5 18v2.5"/><path d="M10 7.5h0m4 0h0m-4 3h0m4 0h0m-4 3h0m4 0h0" stroke-width="2"/>',
  calendar: '<path d="M5.75 4.75h12.5a2 2 0 012 2v12.5a2 2 0 01-2 2H5.75a2 2 0 01-2-2V6.75a2 2 0 012-2zm-2 5h16.5M7.5 2.75v4.5m9-4.5v4.5"/>',
  camera: '<path d="M4.5 7.5H7.17a2 2 0 001.42-.59l.82-.82a2 2 0 011.42-.59h2.34a2 2 0 011.42.59l.82.82a2 2 0 001.42.59H19.5a2 2 0 012 2v8a2 2 0 01-2 2H4.5a2 2 0 01-2-2v-8a2 2 0 012-2zm4 5.75a3.5 3.5 0 107 0 3.5 3.5 0 10-7 0"/>',
  "chart-bar": '<path d="M3.5 3.5v16a1 1 0 001 1h16m-12-4V12m4 4.5v-9m4 9v-6"/>',
  "chart-line": '<path d="M3.5 3.5v16a1 1 0 001 1h16M7 15l2.79-2.79a1 1 0 011.42 0l2.08 2.08a1 1 0 001.42 0L19 10"/>',
  "chart-pie": '<path d="M3.5 12a8.5 8.5 0 1017 0 8.5 8.5 0 10-17 0M12 3.5V12h8.5"/>',
  chat: '<path d="M6 16.25H4.38A1.63 1.63 0 012.75 14.63V5.75a2 2 0 012-2h14.5a2 2 0 012 2v8.5a2 2 0 01-2 2H10.83a2 2 0 00-1.42.59L6 20.25"/>',
  checkmark: '<path d="M4.8 12l4.8 4.8 9.6-9.6"/>',
  "checkmark-outline": '<path d="M3 12a9 9 0 1018 0A9 9 0 103 12"/><path d="M7.8 12l2.8 2.8 5.6-5.6" stroke-width="1.2"/>',
  chip: '<path d="M7 5.5H17A1.5 1.5 0 0118.5 7V17A1.5 1.5 0 0117 18.5H7A1.5 1.5 0 015.5 17V7A1.5 1.5 0 017 5.5zm3.25 4h3.5a.75.75 0 01.75.75v3.5a.75.75 0 01-.75.75h-3.5a.75.75 0 01-.75-.75v-3.5a.75.75 0 01.75-.75zm-.75-7v3m5-3v3m-5 13v3m5-3v3m-12-12h3m-3 5h3m13-5h3m-3 5h3"/>',
  close: '<path d="M6 6L18 18M18 6L6 18"/>',
  cloud: '<path d="M5.03 18.5A2.55 2.55 0 013.91 13.67q1.26-.26 1.13-1.55a4.08 4.08 0 015.02-3.73q1.2.5 2.17-.35a4.58 4.58 0 017.04 3.23q-.02 1.3 1.1 1.95a3.07 3.07 0 01-2.08 5.33z"/>',
  code: '<path d="M8.4 7.2L3.95 11.65a.5.5 0 000 .7L8.4 16.8m7.2-9.6l4.45 4.45a.5.5 0 010 .7L15.6 16.8M13.61 6L10.39 18"/>',
  cube: '<path d="M12.5 3.29l7 4.04a1 1 0 01.5.87v7.6a1 1 0 01-.5.87l-7 4.04a1 1 0 01-1 0l-7-4.04A1 1 0 014 15.8V8.2a1 1 0 01.5-.87l7-4.04a1 1 0 011 0zM4.75 8.05L12 12.24l7.25-4.19M12 12.24V21"/>',
  "currency-dollar": '<path d="M16.38 8.25A4.38 3.75 0 1012 12 4.38 3.75 0 117.63 15.75M12 2.5v19"/>',
  dashboard: '<path d="M6.31 18.87a8.05 8.05 0 1111.38 0M12 13.18l3.66-3.66"/>',
  "data-base": '<path d="M4.5 6a7.5 2.75 0 0115 0A7.5 2.75 0 014.5 6m0 0V18a7.5 2.75 0 0015 0V6m-15 6a7.5 2.75 0 0015 0"/>',
  "delivery-truck": '<path d="M2.5 15.99V7A1.5 1.5 0 014 5.5h9A1.5 1.5 0 0114.5 7v6.82m0-4.32h3.25a1.5 1.5 0 011.2.6l2.25 3a1.5 1.5 0 01.3.9v.94M4.75 17.5a2.25 2.25 0 104.5 0 2.25 2.25 0 10-4.5 0m10.5 0a2.25 2.25 0 104.5 0 2.25 2.25 0 10-4.5 0"/>',
  document: '<path d="M6.75 2.75h7.54a.5.5 0 01.36.15L19.1 7.35a.5.5 0 01.15.36V19.25a2 2 0 01-2 2H6.75a2 2 0 01-2-2V4.75a2 2 0 012-2zm7.75 0V7.5h4.75M8.5 10.5h7m-7 4h7m-7 4h4"/>',
  earth: '<path d="M3 12a9 9 0 1018 0A9 9 0 103 12m9-9a4.5 9 0 010 18A4.5 9 0 0112 3M3 12H21M4.52 7H19.48M4.52 17H19.48"/>',
  education: '<path d="M12.21 4.59L21.54 8.8a.23.23 0 010 .41l-9.33 4.2a.5.5 0 01-.41 0L2.46 9.21a.23.23 0 010-.41L11.8 4.59a.5.5 0 01.41 0zM6.5 11.03V15.5c0 2 2.5 3 5.5 3 3 0 5.5-1 5.5-3V11.03m2-.9V17.5"/><path d="M19.5 17.5h0" stroke-width="2"/>',
  email: '<path d="M4.75 3.75h14.5a2 2 0 012 2v12.5a2 2 0 01-2 2H4.75a2 2 0 01-2-2V5.75a2 2 0 012-2zM2.75 6l8.5 4.91a1.5 1.5 0 001.5 0L21.25 6"/>',
  "face-satisfied": '<path d="M3 12a9 9 0 1018 0A9 9 0 103 12m5.5 2.25a4 4 0 007 0"/><path d="M9 9.75H9m6 0h0" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>',
  favorite: '<path d="M12 20C9 18 3 14.5 3 9.25 3 6.5 5 4.5 7.5 4.5c2 0 3.5 1 4.5 2.5 1-1.5 2.5-2.5 4.5-2.5 2.5 0 4.5 2 4.5 4.75C21 14.5 15 18 12 20z"/>',
  flag: '<path d="M5.5 21V3.5m0 0H18a.54.54 0 01.45.83L16.37 7.45a1 1 0 000 1.11l2.08 3.11A.54.54 0 0118 12.5H5.5"/>',
  flash: '<path d="M12.89 3.29L5.61 12.71A.49.49 0 006 13.5h4.5a.88.88 0 01.88.99l-.76 6.02a.27.27 0 00.49.2l7.28-9.42A.49.49 0 0018 10.5H13.5a.88.88 0 01-.88-.99l.76-6.02a.27.27 0 00-.49-.2z"/>',
  folder: '<path d="M4.75 3.75H8.17a2 2 0 011.42.59l1.82 1.82a2 2 0 001.42.59h6.42a2 2 0 012 2v9.5a2 2 0 01-2 2H4.75a2 2 0 01-2-2V5.75a2 2 0 012-2z"/>',
  gift: '<path d="M4.5 7.5h15A1.5 1.5 0 0121 9v1a1.5 1.5 0 01-1.5 1.5H4.5A1.5 1.5 0 013 10V9A1.5 1.5 0 014.5 7.5zm.5 4v7a2 2 0 002 2H17a2 2 0 002-2v-7m-7-4v13m0-13C10.5 4 6.5 3.5 7 6c.5 1.5 5 1.5 5 1.5m0 0c1.5-3.5 5.5-4 5-1.5-.5 1.5-5 1.5-5 1.5"/>',
  group: '<path d="M5.75 9a3.25 3.25 0 106.5 0A3.25 3.25 0 105.75 9M3 20a6 6 0 0112 0M15 5.6a3 3 0 111.5 5.65m.5 3a5.5 5.5 0 014 5.25"/>',
  growth: '<path d="M3 17l5.29-5.29a1 1 0 011.42 0l2.58 2.58a1 1 0 001.42 0l6.04-6.04m-3.5-.75H20a.5.5 0 01.5.5v3.75"/>',
  help: '<path d="M3 12a9 9 0 1018 0A9 9 0 103 12M9.5 9.5A2.5 2.5 0 1113 11.8c-.6.3-1 .8-1 1.5v.45"/><path d="M12 16.75h0" stroke-width="2"/>',
  home: '<path d="M2.5 20.5h19m-18-8l7.09-7.09a2 2 0 012.82 0L20.5 12.5m-14-3v11m11-11v11m-8 0v-5a2 2 0 012-2h1a2 2 0 012 2v5"/>',
  idea: '<path d="M8.42 14.62a6.25 6.25 0 117.16 0L15 17.5H9zM9.75 20.5h4.5"/>',
  image: '<path d="M5.5 3.5h13a2 2 0 012 2v13a2 2 0 01-2 2H5.5a2 2 0 01-2-2V5.5a2 2 0 012-2zm-2 13.36L8 12.35a.5.5 0 01.71 0l8.15 8.15"/><path d="M16.25 7.75h0" stroke-width="2"/>',
  industry: '<path d="M2.5 20.5h19m-16 0V10.15a2 2 0 011-1.73l5.57-3.21a.29.29 0 01.43.25V8.5a.29.29 0 00.43.25l6.14-3.54a.29.29 0 01.43.25V20.5m-9 0v-4a2 2 0 012-2h0a2 2 0 012 2v4"/>',
  information: '<path d="M3 12a9 9 0 1018 0A9 9 0 103 12m9-1v5.5"/><path d="M12 8h0" stroke-width="2"/>',
  laptop: '<path d="M7.5 5.5h9a2 2 0 012 2v6a2 2 0 01-2 2h-9a2 2 0 01-2-2v-6a2 2 0 012-2zm-5 13h19"/>',
  link: '<path d="M11.75 13.53a3 3 30 01-.5-.23h0a3 3 30 01-1.1-4.1l2-3.46a3 3 30 014.1-1.1h0 0a3 3 30 011.1 4.1l-.99 1.71m-4.11.02a3 3 30 01.5.23h0 0a3 3 30 011.1 4.1l-2 3.46a3 3 30 01-4.1 1.1h0a3 3 30 01-1.1-4.1l.99-1.71"/>',
  "list-checked": '<path d="M3.75 3.75h16.5m-16.5 6h16.5m-16.5 6H7.92"/><path d="M10.42 17l3.22 3.22 6.44-6.44" stroke-width="1.2"/>',
  location: '<path d="M12 21.25c0 0-7.25-6.07-7.25-11.25a7.25 7.25 0 0114.5 0c0 5.18-7.25 11.25-7.25 11.25zM9.5 10a2.5 2.5 0 105 0 2.5 2.5 0 10-5 0"/>',
  locked: '<path d="M8 11h8a2 2 0 012 2v4a2 2 0 01-2 2H8A2 2 0 016 17V13a2 2 0 012-2zm0 0V8.5a4 4 0 018 0V11m-4 3v2"/>',
  "machine-learning-model": '<path d="M1.75 8a1.75 1.75 0 103.5 0A1.75 1.75 0 101.75 8m0 8a1.75 1.75 0 103.5 0 1.75 1.75 0 10-3.5 0m8.5-11.75a1.75 1.75 0 103.5 0 1.75 1.75 0 10-3.5 0m0 7.75a1.75 1.75 0 103.5 0 1.75 1.75 0 10-3.5 0m0 7.75a1.75 1.75 0 103.5 0 1.75 1.75 0 10-3.5 0M18.75 8a1.75 1.75 0 103.5 0 1.75 1.75 0 10-3.5 0m0 8a1.75 1.75 0 103.5 0 1.75 1.75 0 10-3.5 0M5.1 7.29l5.3-2.33M5.08 8.75l5.34 2.5M4.53 9.42l6.44 8.91M4.53 14.58l6.44-8.91M5.08 15.25l5.34-2.5M5.1 16.71l5.3 2.33M13.6 4.96l5.3 2.33M13.03 5.67l6.44 8.91m-5.89-3.33l5.34-2.5m-5.34 4l5.34 2.5m-5.89 3.08l6.44-8.91M13.6 19.04l5.3-2.33"/>',
  map: '<path d="M4.12 5.74L9.08 3.68a1 1 0 01.83.03L14.09 5.8a1 1 0 00.83.02l4.66-1.93a.67.67 0 01.92.61V17.33a1 1 0 01-.61.93l-4.97 2.06a1 1 0 01-.83-.02L9.91 18.2a1 1 0 00-.83-.02L4.42 20.11A.67.67 0 013.5 19.5V6.67a1 1 0 01.62-.93zM9.5 3.5V18.1m5-12.2V20.5"/>',
  microphone: '<path d="M12 3h0a3 3 0 013 3v5a3 3 0 01-3 3h0A3 3 0 019 11V6a3 3 0 013-3zM6 11a6 6 0 0012 0m-6 6v3.5m-3.5 0h7"/>',
  mobile: '<path d="M8.5 2.5h7a2 2 0 012 2v15a2 2 0 01-2 2h-7a2 2 0 01-2-2V4.5a2 2 0 012-2zm2 16h3"/>',
  money: '<path d="M4.5 6.5h15a2 2 0 012 2v7a2 2 0 01-2 2H4.5a2 2 0 01-2-2v-7a2 2 0 012-2zM9.25 12a2.75 2.75 0 105.5 0 2.75 2.75 0 10-5.5 0"/><path d="M6 12H6m12 0h0" stroke-width="2"/>',
  moon: '<path d="M20.21 14.72A8.5 8.5 0 119.78 4.29q1.58-.27.76 1.11a6.5 6.5 0 008.56 8.56q1.38-.82 1.11.76z"/>',
  "network-3": '<path d="M4.63 9.92a1.7 3.5 0 012.74 0q.16.55.71.71a3.5 1.7 0 010 2.74q-.55.16-.71.71a1.7 3.5 0 01-2.74 0q-.16-.55-.71-.71a3.5 1.7 0 010-2.74q.55-.16.71-.71zm6.55.43l1.29 1.3a.5.5 0 010 .7l-1.29 1.3m5.45-3.73a1.7 3.5 0 012.74 0q.16.55.71.71a3.5 1.7 0 010 2.74q-.55.16-.71.71a1.7 3.5 0 01-2.74 0q-.16-.55-.71-.71a3.5 1.7 0 010-2.74q.55-.16.71-.71z"/>',
  password: '<path d="M3.75 16.5a3.75 3.75 0 107.5 0 3.75 3.75 0 10-7.5 0m6.4-2.65L20 4M17.5 6.5l2 2M15 9l1.5 1.5"/>',
  phone: '<path d="M6 3.5H9.5L11 8 8.75 9.5a11 11 0 005.75 5.75L16 13l4.5 1.5v4A1.5 1.5 0 0119 20 15.5 15.5 0 014.5 5 1.5 1.5 0 016 3.5z"/>',
  play: '<path d="M10.23 6l8.66 5a1.16 1.16 0 010 2l-8.66 5A1.16 1.16 0 018.5 17V7a1.16 1.16 0 011.73-1z"/>',
  "question-answering": '<path d="M14.5 6.5V5.13A1.38 1.38 0 0013.13 3.75H4.75a2 2 0 00-2 2V9.5a2 2 0 002 2H5.5a.83.83 0 01.59 1.41L4.5 14.5M19 17.25h1.13a1.13 1.13 0 001.12-1.12V10.5a2 2 0 00-2-2H11.5a2 2 0 00-2 2v4.75a2 2 0 002 2h3.67a2 2 0 011.42.59L19 20.25"/>',
  rain: '<path d="M6.1 15.5a2.16 2.16 0 01-.95-4.09q1.07-.22.96-1.31a3.45 3.45 0 014.25-3.15q1.01.42 1.84-.3a3.87 3.87 0 015.95 2.74q-.01 1.09.93 1.64a2.6 2.6 0 01-1.76 4.51zm1.9 2v3m4-3v3m4-3v3"/>',
  recycle: '<path d="M14.01 4.49a7.78 7.78 0 015.71 8.48m-2.44-1.7l1.92 2.36a.5.5 0 00.7.07l2.35-1.92M17.5 17.5a7.78 7.78 0 01-10.2.7m2.69-1.27l-3 .49a.5.5 0 00-.41.57l.49 3M4.49 14.01A7.78 7.78 0 018.98 4.83M8.73 7.79L9.81 4.95a.5.5 0 00-.29-.64L6.68 3.23"/>',
  rocket: '<path d="M18.72 5.28c.35 4.6-2.48 8.13-6.72 11.67L7.05 12c3.54-4.24 7.07-7.07 11.67-6.72zM12.88 8.64a1.75 1.75 45 102.48 2.48A1.75 1.75 45 1012.88 8.64m-3.47.77l-4.48.47L2.81 12H7.05m7.54 2.59l-.47 4.48L12 21.19V16.95M6.7 15.18L5.64 18.36 8.82 17.3"/>',
  search: '<path d="M4 10.5a6.5 6.5 0 1013 0 6.5 6.5 0 10-13 0m11.1 4.6l5.4 5.4"/>',
  security: '<path d="M3.75 4.25a23.44 23.44 0 0116.5 0V11c0 5.33-3.71 8.41-8.25 10.25C7.46 19.41 3.75 16.33 3.75 11z"/>',
  send: '<path d="M16.61 4.76L14.2 21.44a.35.35 30 01-.64.12l-3.27-5.6a1 1 30 00-.86-.5l-6.49-.03a.35.35 30 01-.22-.62L15.96 4.39a.4.4 30 01.65.37zm-.87.76L9.92 15.6"/>',
  settings: '<path d="M10.32 4.76l.14-.52a1 1 0 01.96-.74h1.16a1 1 0 01.97.74l.13.52a1 1 0 00.59.67l.77.32a1 1 0 00.89-.06l.46-.27a1 1 0 011.21.16l.82.82a1 1 0 01.16 1.21l-.27.46a1 1 0 00-.06.89l.32.77a1 1 0 00.67.59l.52.14a1 1 0 01.74.96v1.16a1 1 0 01-.74.97l-.52.13a1 1 0 00-.67.59l-.32.77a1 1 0 00.06.89l.27.46a1 1 0 01-.16 1.21l-.82.82a1 1 0 01-1.21.16l-.46-.27a1 1 0 00-.89-.06l-.77.32a1 1 0 00-.59.67l-.13.52a1 1 0 01-.97.74H11.42a1 1 0 01-.96-.74l-.14-.52a1 1 0 00-.59-.67l-.77-.32a1 1 0 00-.89.06l-.46.27A1 1 0 016.4 18.42l-.82-.82a1 1 0 01-.16-1.21l.27-.46a1 1 0 00.06-.89l-.32-.77a1 1 0 00-.67-.59l-.52-.13a1 1 0 01-.74-.97V11.42a1 1 0 01.74-.96l.52-.14a1 1 0 00.67-.59l.32-.77a1 1 0 00-.06-.89l-.27-.46A1 1 0 015.58 6.4l.82-.82a1 1 0 011.21-.16l.46.27a1 1 0 00.89.06l.77-.32a1 1 0 00.59-.67zM9 12a3 3 0 106 0A3 3 0 109 12"/>',
  "shopping-cart": '<path d="M2.5 3.5H3.78A1.5 1.5 0 015.25 4.69l2 9.62A1.5 1.5 0 008.72 15.5h8.61a1.5 1.5 0 001.45-1.14l1.36-5.4A1.17 1.17 0 0019 7.5H5.85m1.65 12a1.5 1.5 0 103 0 1.5 1.5 0 10-3 0m8 0a1.5 1.5 0 103 0 1.5 1.5 0 10-3 0"/>',
  star: '<path d="M13.22 6.83l.8 1.73a1.8 1.8 0 001.42 1.03l1.89.22a1.34 1.34 0 01.75 2.32l-1.4 1.29a1.8 1.8 0 00-.54 1.68l.37 1.86a1.34 1.34 0 01-1.97 1.43l-1.66-.93a1.8 1.8 0 00-1.76 0l-1.66.93A1.34 1.34 0 017.49 16.96l.37-1.86a1.8 1.8 0 00-.54-1.68l-1.4-1.29a1.34 1.34 0 01.75-2.32l1.89-.22A1.8 1.8 0 009.98 8.56l.8-1.73a1.34 1.34 0 012.44 0z"/>',
  store: '<path d="M2.5 20.5h19M3.85 9.15L6.91 6.09A2 2 0 018.33 5.5h7.34a2 2 0 011.42.59l3.06 3.06A.21.21 0 0120 9.5H4a.21.21 0 01-.15-.35zM10.5 5.5v4m3-4v4m-8 0v11m13-11v11m-11 0v-5a2 2 0 012-2h0a2 2 0 012 2v5m3.5-7h0A1.5 1.5 0 0116.5 15h0A1.5 1.5 0 0115 16.5h0A1.5 1.5 0 0113.5 15h0A1.5 1.5 0 0115 13.5z"/>',
  subtract: '<path d="M4.5 12h15"/>',
  sun: '<path d="M8 12a4 4 0 108 0A4 4 0 108 12m10.5 0H21m-4.4 4.6l1.76 1.76M12 18.5V21M7.4 16.6L5.64 18.36M5.5 12H3M7.4 7.4L5.64 5.64M12 5.5V3m4.6 4.4l1.76-1.76"/>',
  task: '<path d="M17 4.56A2 2 0 0118.5 6.5v12a2 2 0 01-2 2h-9a2 2 0 01-2-2V6.5A2 2 0 017 4.56M8.7 13.5l2.2 2.2 4.4-4.4M10.5 3.5h3a1 1 0 011 1v1a1 1 0 01-1 1h-3a1 1 0 01-1-1v-1a1 1 0 011-1z"/>',
  "thumbs-up": '<path d="M5 10.5H7a.5.5 0 01.5.5v9a.5.5 0 01-.5.5H5A1.5 1.5 0 013.5 19V12A1.5 1.5 0 015 10.5zm2.35.15L10.5 4c.5-1 3-1 3.5 1l-.5 5.5h5a1.72 1.72 0 011.7 1.98l-.94 6.32a2 2 0 01-1.98 1.7l-9.93-.15"/>',
  time: '<path d="M3.95 12a8.05 8.05 0 1016.1 0A8.05 8.05 0 103.95 12M12 7.4V12L8.55 15.45"/>',
  "tool-kit": '<path d="M5.5 8.5h13a2 2 0 012 2v7a2 2 0 01-2 2H5.5a2 2 0 01-2-2v-7a2 2 0 012-2zm3 0v-2a1 1 0 011-1h5a1 1 0 011 1v2m-12 4h7m3 0h7m-9.5-2h2a.5.5 0 01.5.5v3a.5.5 0 01-.5.5H11a.5.5 0 01-.5-.5V11a.5.5 0 01.5-.5z"/>',
  tools: '<path d="M11.4 7.86a4.5 4.5 45 016.43-3.81l-3 3 2.12 2.12 3-3a4.5 4.5 45 01-1.89 5.88m-7.83 4.19L8.11 18.36A1.75 1.75 45 015.64 15.89l2.61-2.61M5.99 5.99l5.3 5.3m-.17.18l.35-.35a1.5 1.5-45 012.12 0l4.6 4.59a1.5 1.5-45 010 2.12l-.36.36a1.5 1.5-45 01-2.12 0l-4.59-4.6a1.5 1.5-45 010-2.12z"/>',
  tree: '<path d="M9.5 16.5H7A4 4 0 015.5 9a6.6 6.6 0 0113 0A4 4 0 0117 16.5H14.5m-2.5 5l1-9M12 15L9.5 12.5m2.5 1l2-2"/>',
  trophy: '<path d="M7 3.5H17v6A5 5 0 017 9.5zm0 2H4.5C4.5 8 5.4 10 7.23 11M17 5.5h2.5c0 2.5-.9 4.5-2.73 5.5M12 14.5v3m-3 0h6a1 1 0 011 1v1a1 1 0 01-1 1H9a1 1 0 01-1-1v-1a1 1 0 011-1z"/>',
  user: '<path d="M8.25 8a3.75 3.75 0 107.5 0A3.75 3.75 0 108.25 8M5 20.5a7 6.5 0 0114 0"/>',
  video: '<path d="M5 6.5h8a2 2 0 012 2v7a2 2 0 01-2 2H5a2 2 0 01-2-2v-7a2 2 0 012-2zM15 10l5.13-2.96a.58.58 0 01.87.5v8.92a.58.58 0 01-.87.5L15 14"/>',
  wallet: '<path d="M5.5 5h13a2 2 0 012 2V17a2 2 0 01-2 2H5.5a2 2 0 01-2-2V7a2 2 0 012-2zm15 5H17a1.5 1.5 0 00-1.5 1.5v1A1.5 1.5 0 0017 14h3.5"/><path d="M18 12h0" stroke-width="2"/>',
  warning: '<path d="M3 12a9 9 0 1018 0A9 9 0 103 12m9-4.5v5"/><path d="M12 16h0" stroke-width="2"/>',
  "warning-alt": '<path d="M13 4.73l7.5 13.04a1.16 1.16 0 01-1 1.73H4.5a1.16 1.16 0 01-1-1.73L11 4.73a1.15 1.15 0 012 0zM12 9v4.5"/><path d="M12 16.5h0" stroke-width="2"/>'
};
var He = {
  "checkmark-filled": "checkmark-outline",
  lightning: "flash",
  "star-filled": "star",
  "user-multiple": "group"
};
var Ue = Object.keys(O);
function k(e2) {
  let t2 = Object.hasOwn(He, e2) ? He[e2] : e2;
  return Object.hasOwn(O, t2) ? O[t2] : void 0;
}
function We(e2) {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" role="img">${k(e2) ?? ""}</svg>`;
}
var A = 1920;
var j = 1080;
var M = 500;
var Ge = 200;
var Ke = 53248;
var qe = [
  "div",
  "h1",
  "h2",
  "h3",
  "p",
  "ul",
  "ol",
  "img",
  "table",
  "hr",
  "x-shape",
  "x-icon",
  "x-connector"
];
var Je = [
  "b",
  "i",
  "u",
  "s",
  "a",
  "span",
  "br"
];
var N = [
  "fade",
  "push",
  "magic"
];
var Ye = [
  "rect",
  "rounded",
  "ellipse",
  "diamond",
  "triangle",
  "arrow-right",
  "arrow-left",
  "arrow-up",
  "arrow-down",
  "line"
];
var Xe = /* @__PURE__ */ new Set([
  "br",
  "hr",
  "img",
  "meta",
  "link",
  "input",
  "wbr",
  "source",
  "col",
  "area",
  "base",
  "x-shape",
  "x-icon",
  "x-connector"
]);
var Ze = /* @__PURE__ */ new Set([
  "p",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "div",
  "ul",
  "ol",
  "table",
  "section",
  "hr",
  "blockquote",
  "figure",
  "header",
  "footer",
  "aside"
]);
var Qe = 256;
function $e(e2, t2) {
  let n2 = {
    kind: "element",
    name: "#root",
    attributes: [],
    children: [],
    line: 1,
    column: 1
  }, r2 = [n2], i2 = () => r2.at(-1), a2 = (e3, t3 = []) => {
    for (let n3 = r2.length - 1; n3 > 0; --n3) {
      let i3 = r2[n3].name;
      if (t3.includes(i3)) return;
      if (e3.includes(i3)) {
        r2.length = n3;
        return;
      }
    }
  };
  for (let n3 of Re(e2)) switch (n3.type) {
    case "text":
      i2().children.push({
        kind: "text",
        text: n3.text,
        line: n3.line,
        column: n3.column
      });
      break;
    case "raw":
      i2().children.push({
        kind: "raw",
        name: n3.name,
        attributes: n3.attributes,
        inner: n3.inner,
        closed: n3.closed,
        line: n3.line,
        column: n3.column
      });
      break;
    case "start": {
      let e3 = n3.name;
      Ze.has(e3) && a2(["p"], [
        "div",
        "section",
        "td",
        "th",
        "li",
        "body"
      ]), e3 === "li" ? a2(["li"], ["ul", "ol"]) : e3 === "tr" ? a2(["tr"], [
        "table",
        "tbody",
        "thead",
        "tfoot"
      ]) : e3 === "td" || e3 === "th" ? a2(["td", "th"], ["tr", "table"]) : e3 === "section" && a2(["section"]);
      let o2 = {
        kind: "element",
        name: e3,
        attributes: n3.attributes,
        children: [],
        line: n3.line,
        column: n3.column
      };
      i2().children.push(o2), !Xe.has(e3) && !n3.selfClosing && (r2.length < Qe ? r2.push(o2) : t2(o2));
      break;
    }
    case "end":
      if (Xe.has(n3.name)) break;
      a2([n3.name]);
  }
  return n2;
}
var et = {
  strong: "b",
  em: "i",
  del: "s",
  strike: "s",
  ins: "u",
  h4: "h3",
  h5: "h3",
  h6: "h3",
  blockquote: "div",
  figure: "div",
  figcaption: "p",
  header: "div",
  footer: "div",
  main: "div",
  article: "div",
  nav: "div",
  center: "div",
  small: "span",
  mark: "span",
  sup: "span",
  sub: "span",
  code: "span",
  kbd: "span",
  label: "span",
  time: "span",
  abbr: "span",
  cite: "span",
  q: "span"
};
var tt = /* @__PURE__ */ new Set([
  "thead",
  "tbody",
  "tfoot",
  "colgroup",
  "picture"
]);
var nt = /* @__PURE__ */ new Set([
  "script",
  "noscript",
  "iframe",
  "object",
  "embed",
  "canvas",
  "video",
  "audio",
  "form",
  "input",
  "button",
  "select",
  "textarea",
  "template",
  "x-embed",
  "col",
  "source",
  "meta",
  "link",
  "style",
  "title",
  "head"
]);
var rt = /* @__PURE__ */ new Set([
  "h1",
  "h2",
  "h3",
  "p"
]);
var it = /* @__PURE__ */ new Set([
  "b",
  "i",
  "u",
  "s",
  "a",
  "span"
]);
var at = /* @__PURE__ */ new Set([
  "id",
  "data-build-in",
  "data-build-out"
]);
var ot = {
  a: ["href"],
  img: [
    "src",
    "alt",
    "data-crop"
  ],
  "x-shape": ["kind"],
  "x-icon": ["name"],
  "x-connector": [
    "x1",
    "y1",
    "x2",
    "y2",
    "head",
    "route",
    "from"
  ]
};
var st = /^(class|role|title|lang|dir|tabindex|aria-.*|data-.*|width|height|loading|decoding|draggable|target|rel|xmlns.*)$/;
var ct = /^[A-Za-z0-9_-]{1,64}$/;
function P(e2, t2, n2, r2) {
  e2.diagnostics.push({
    severity: n2,
    line: t2.line,
    column: t2.column,
    ...e2.slide === void 0 ? {} : { slide: e2.slide },
    message: r2
  });
}
function lt(e2) {
  let t2 = {
    diagnostics: [],
    slide: void 0,
    elements: 0
  }, n2 = false, r2 = $e(e2.replace(/\r\n?/g, "\n"), (e3) => {
    n2 || (n2 = true, P(t2, e3, "warning", `Elements nest more than ${Qe} deep here; what is deeper is set beside its parent.`));
  }), i2 = I(r2, "html") ?? r2, a2 = I(i2, "head"), o2 = I(i2, "body") ?? i2, s2 = I(a2 ?? i2, "title"), c2 = [], l2 = [];
  for (let e3 of L(a2 ?? i2, (e4) => e4.kind === "element" && e4.name === "link")) {
    let n3 = F(e3, "href");
    F(e3, "rel") === "stylesheet" && n3 !== void 0 && (n3.startsWith("https://fonts.googleapis.com/") ? c2.push(n3) : P(t2, e3, "warning", `<link href="${n3}"> is dropped: a deck loads stylesheets only from Google Fonts.`));
  }
  for (let e3 of L(r2, (e4) => e4.kind === "raw" && e4.name === "style")) l2.push(...ft(t2, e3));
  let u2 = L(o2, (e3) => e3.kind === "element" && e3.name === "section", true);
  u2.length > M && P(t2, u2[M], "warning", `A deck holds at most ${M} slides; the rest are dropped.`);
  let d2 = /* @__PURE__ */ new Set(), f2 = u2.slice(0, M).map((e3, n3) => (t2.slide = n3 + 1, t2.elements = 0, ht(t2, e3, n3, d2)));
  t2.slide = void 0;
  for (let e3 of ut(o2)) P(t2, e3, "warning", "Content outside a <section> is dropped: every slide is a <section>.");
  return {
    deck: {
      title: s2 === void 0 ? "" : dt(s2).trim(),
      fontLinks: c2,
      fontFaces: l2,
      style: R(t2, "body", o2),
      slides: f2
    },
    diagnostics: t2.diagnostics
  };
}
function F(e2, t2) {
  return e2.attributes.find((e3) => e3.name === t2)?.value;
}
function I(e2, t2) {
  for (let n2 of e2.children) {
    if (n2.kind !== "element") continue;
    if (n2.name === t2) return n2;
    let e3 = I(n2, t2);
    if (e3 !== void 0) return e3;
  }
}
function L(e2, t2, n2 = false) {
  let r2 = [];
  for (let i2 of e2.children) t2(i2) && (r2.push(i2), n2) || i2.kind === "element" && r2.push(...L(i2, t2, n2));
  return r2;
}
function ut(e2) {
  return e2.children.flatMap((e3) => e3.kind === "text" ? e3.text.trim() === "" ? [] : [e3] : e3.kind === "raw" ? e3.name === "style" ? [] : [e3] : e3.name === "section" || e3.name === "head" || e3.name === "title" || e3.name === "link" || e3.name === "meta" ? [] : L(e3, (e4) => e4.kind === "element" && e4.name === "section").length > 0 ? ut(e3) : [e3]);
}
function dt(e2) {
  return e2.kind === "text" ? e2.text : e2.kind === "raw" ? "" : e2.children.map(dt).join("");
}
function ft(e2, t2) {
  let n2 = [];
  return t2.inner.replace(/@font-face\s*\{([^}]*)\}/g, (r2, i2) => {
    let a2 = /font-family\s*:\s*(["']?)([^;"']+)\1/.exec(i2)?.[2]?.trim(), o2 = /src\s*:\s*url\(\s*(["']?)([^)"']+)\1\s*\)/.exec(i2)?.[2]?.trim();
    return a2 !== void 0 && o2 !== void 0 && pt(o2) ? n2.push({
      family: a2,
      src: o2
    }) : P(e2, t2, "warning", "An @font-face is dropped: it needs a font-family and a src naming one of the deck's assets."), "";
  }).replace(/\/\*[\s\S]*?\*\//g, "").trim() !== "" && P(e2, t2, "warning", "A <style> may hold only @font-face rules; the rest is dropped. Style each element inline."), n2;
}
function pt(e2) {
  return /^assets\/[\w.-]{1,128}$/.test(e2);
}
function mt(e2) {
  return pt(e2) || /^https:\/\/[^\s"'<>]+$/.test(e2);
}
function R(e2, t2, n2) {
  let r2 = F(n2, "style");
  if (r2 === void 0 || r2.trim() === "") return {};
  let i2 = {};
  for (let a2 of ke(t2, r2)) "value" in a2 ? i2[a2.property] = a2.value : a2.silent !== true && P(e2, n2, "warning", `<${t2}> style \`${a2.property}\` ${a2.dropped}.`);
  return i2;
}
function ht(e2, t2, n2, r2) {
  let i2 = F(t2, "id"), a2 = i2 ?? "";
  if (!ct.test(a2) || r2.has(a2)) {
    let o3 = gt(`slide-${n2 + 1}`, r2);
    P(e2, t2, "note", i2 === void 0 ? `The slide has no id; it is "${o3}".` : `id="${i2}" is ${r2.has(i2) ? "taken by an earlier slide" : "not [A-Za-z0-9_-]{1,64}"}; the slide is "${o3}".`), a2 = o3;
  }
  r2.add(a2);
  let o2 = F(t2, "data-transition"), s2 = F(t2, "data-section")?.trim(), c2 = t2.children.filter((e3) => e3.kind === "raw" && e3.name === "aside");
  for (let t3 of c2.filter((e3) => !e3.closed)) P(e2, t3, "warning", "<aside> has no </aside>; the notes end where the slide does.");
  let l2 = c2.map((e3) => _t(e3.inner)).join("\n\n"), u2 = V(e2, t2.children.filter((e3) => e3.kind !== "raw" || e3.name !== "aside"), 1);
  return o2 !== void 0 && !N.includes(o2) && P(e2, t2, "warning", `data-transition="${o2}" is dropped: ${N.join(", ")}.`), e2.elements > Ge && P(e2, t2, "warning", `This slide has ${e2.elements} elements; keep a slide under ${Ge}, or split it.`), {
    id: a2,
    style: R(e2, "section", t2),
    ...N.includes(o2 ?? "") ? { transition: o2 } : {},
    ...s2 === void 0 || s2 === "" ? {} : { section: s2 },
    ...t2.attributes.some((e3) => e3.name === "hidden") ? { hidden: true } : {},
    notes: l2,
    children: u2
  };
}
function gt(e2, t2) {
  if (!t2.has(e2)) return e2;
  for (let n2 = 2; ; n2 += 1) if (!t2.has(`${e2}-${n2}`)) return `${e2}-${n2}`;
}
function _t(e2) {
  return T(e2.replace(/<br\s*\/?>/gi, "\n").replace(/<\/?p\b[^>]*>/gi, "\n").replace(/<[^>]*>/g, "")).split("\n").map((e3) => e3.trim()).join("\n").replace(/\n{3,}/g, "\n\n").trim();
}
function vt(e2) {
  let t2 = e2.trim().split(/\s+/), n2 = /^-?\d+(\.\d+)?(%|px)$/;
  if (t2.length !== 3) return;
  let r2 = Number(t2[0]);
  return Number.isFinite(r2) && r2 >= 1 && r2 <= 50 && n2.test(t2[1]) && n2.test(t2[2]) ? {
    zoom: r2,
    x: t2[1],
    y: t2[2]
  } : void 0;
}
function z(e2, t2, n2) {
  let r2 = {}, i2 = ot[t2] ?? [];
  for (let { name: a2, value: o2 } of n2.attributes) a2 !== "style" && (a2 === "data-crop" && t2 === "img" && vt(o2) === void 0 ? P(e2, n2, "warning", `data-crop="${o2.slice(0, 60)}" is dropped: a zoom from 1 to 50 and where it is centred, as \`2 30% 40%\`.`) : at.has(a2) || i2.includes(a2) ? r2[a2] = o2 : a2.startsWith("on") ? P(e2, n2, "warning", `<${t2} ${a2}> is dropped: a slide runs no scripts.`) : st.test(a2) || P(e2, n2, "note", `<${t2}> attribute \`${a2}\` is dropped.`));
  return r2;
}
function B(e2) {
  if (tt.has(e2)) return "transparent";
  if (nt.has(e2)) return "dropped";
  let t2 = et[e2] ?? e2;
  return qe.includes(t2) || Je.includes(t2) || [
    "li",
    "tr",
    "th",
    "td"
  ].includes(t2) ? t2 : "unknown";
}
function V(e2, t2, n2) {
  let r2 = [], i2 = [], a2 = () => {
    let t3 = H(e2, i2), n3 = i2[0];
    t3.length > 0 && n3 !== void 0 && (P(e2, n3, "note", "Text directly inside a container is set as a <p>."), r2.push(W("p", {}, {}, t3))), i2 = [];
  };
  for (let o2 of t2) {
    if (o2.kind === "text") {
      i2.push(o2);
      continue;
    }
    if (o2.kind === "raw") {
      a2(), r2.push(...yt(e2, o2));
      continue;
    }
    let t3 = B(o2.name);
    t3 !== "transparent" && t3 !== "dropped" && t3 !== "unknown" && (it.has(t3) || t3 === "br") ? i2.push(o2) : (a2(), r2.push(...bt(e2, o2, n2)));
  }
  return a2(), r2;
}
function yt(e2, t2) {
  switch (!t2.closed && t2.name !== "script" && P(e2, t2, "warning", `<${t2.name}> has no </${t2.name}>; it ends where the slide does.`), t2.name) {
    case "svg":
      return Mt(e2, t2);
    case "script":
      return P(e2, t2, "warning", "<script> is dropped: a slide runs no scripts."), [];
    case "style":
      return P(e2, t2, "warning", "A <style> inside a slide is dropped: style each element inline."), [];
    default:
      return [];
  }
}
function bt(e2, t2, n2) {
  let r2 = B(t2.name);
  switch (r2) {
    case "transparent":
      return V(e2, t2.children, n2);
    case "dropped":
      return P(e2, t2, "warning", `<${t2.name}> is dropped: it is not in the slide subset.`), [];
    case "unknown":
      return P(e2, t2, "warning", `<${t2.name}> is not in the slide subset; what is inside it is kept.`), V(e2, t2.children, n2);
  }
  r2 !== t2.name && P(e2, t2, "note", `<${t2.name}> is read as <${r2}>.`), e2.elements += 1;
  let i2 = z(e2, r2, t2), a2 = R(e2, r2, t2);
  switch (r2) {
    case "div":
      return n2 > 15 ? (P(e2, t2, "warning", "Containers nest at most 15 deep; this one is flattened into its parent."), V(e2, t2.children, n2)) : [W("div", i2, a2, V(e2, t2.children, n2 + 1))];
    case "h1":
    case "h2":
    case "h3":
    case "p":
      return [W(r2, i2, a2, H(e2, t2.children))];
    case "ul":
    case "ol":
      return [W(r2, i2, a2, xt(e2, t2, "li"))];
    case "table":
      return [W("table", i2, a2, xt(e2, t2, "tr"))];
    case "img": {
      let n3 = i2.src;
      if (n3 === void 0 || !mt(n3)) {
        P(e2, t2, "warning", n3 === void 0 ? "<img> has no src; it is drawn as an empty box." : `<img src="${n3.slice(0, 60)}"> is dropped: an image is one of the deck's assets or an https URL.`);
        let { src: r3, ...o2 } = i2;
        return [W("img", o2, a2, [])];
      }
      return [W("img", i2, a2, [])];
    }
    case "x-shape":
      return i2.kind === void 0 || !Ye.includes(i2.kind) ? (P(e2, t2, "warning", `<x-shape kind="${i2.kind ?? ""}"> is drawn as a rect: kinds are ${Ye.join(", ")}.`), [W("x-shape", {
        ...i2,
        kind: "rect"
      }, a2, [])]) : [W("x-shape", i2, a2, [])];
    case "x-icon":
      return i2.name === void 0 || k(i2.name) === void 0 ? (P(e2, t2, "warning", `<x-icon name="${i2.name ?? ""}"> is not an icon there is; it is dropped. See the icon list.`), []) : [W("x-icon", i2, a2, [])];
    case "x-connector":
    case "hr":
      return [W(r2, i2, a2, [])];
    case "li":
    case "tr":
    case "th":
    case "td":
      return P(e2, t2, "warning", `<${r2}> outside its ${r2 === "li" ? "list" : "table"} is set as a paragraph.`), [W("p", {}, {}, H(e2, t2.children))];
    default:
      return [W("p", {}, {}, H(e2, [t2]))];
  }
}
function xt(e2, t2, n2) {
  let r2 = [], i2 = (a2) => {
    for (let o2 of a2) o2.kind === "text" ? o2.text.trim() !== "" && P(e2, o2, "warning", `Text directly inside <${t2.name}> is dropped: put it in a <${n2 === "li" ? "li" : "td"}>.`) : o2.kind !== "raw" && (tt.has(o2.name) ? i2(o2.children) : o2.name === n2 ? (e2.elements += 1, n2 === "li" ? r2.push(W("li", z(e2, "li", o2), R(e2, "li", o2), H(e2, o2.children))) : (St(e2, o2), r2.push(W("tr", {}, R(e2, "tr", o2), Ct(e2, o2))))) : P(e2, o2, "warning", `<${o2.name}> inside <${t2.name}> is dropped: it holds only <${n2}>.`));
  };
  return i2(t2.children), r2;
}
function St(e2, t2) {
  for (let { name: n2 } of t2.attributes) at.has(n2) && P(e2, t2, "note", `<${t2.name}> attribute \`${n2}\` is dropped: give it to the <table>.`);
}
function Ct(e2, t2) {
  return t2.children.flatMap((t3) => t3.kind === "element" ? t3.name !== "td" && t3.name !== "th" ? (P(e2, t3, "warning", `<${t3.name}> inside <tr> is dropped: a row holds <th> and <td>.`), []) : (t3.attributes.some((e3) => e3.name === "colspan" || e3.name === "rowspan") && P(e2, t3, "warning", "colspan and rowspan are dropped: every cell is one cell."), e2.elements += 1, St(e2, t3), [W(t3.name, {}, R(e2, t3.name, t3), H(e2, t3.children))]) : []);
}
function H(e2, t2) {
  let n2 = U(e2, t2), r2 = (e3) => e3?.type === "element" && e3.tag === "br";
  for (; r2(n2[0]); ) n2.shift();
  for (; r2(n2.at(-1)); ) n2.pop();
  return Et(n2);
}
var wt = /* @__PURE__ */ new Set([
  "h1",
  "h2",
  "h3",
  "p",
  "div",
  "ul",
  "ol",
  "li",
  "table",
  "tr",
  "td",
  "th"
]);
function U(e2, t2) {
  let n2 = [], r2 = () => {
    let e3 = n2.at(-1);
    e3 !== void 0 && (e3.type !== "element" || e3.tag !== "br") && n2.push(W("br", {}, {}, []));
  };
  for (let i2 of t2) {
    let t3 = i2.kind === "element" ? B(i2.name) : void 0;
    i2.kind === "element" && typeof t3 == "string" && wt.has(t3) ? (rt.has(t3) || P(e2, i2, "note", `<${i2.name}> inside text is set as lines of that text.`), r2(), n2.push(...U(e2, i2.children)), r2()) : n2.push(...Tt(e2, i2));
  }
  return n2;
}
function Tt(e2, t2) {
  if (t2.kind === "text") return [{
    type: "text",
    text: t2.text
  }];
  if (t2.kind === "raw") return t2.name === "svg" && P(e2, t2, "warning", "An <svg> inside text is dropped: place it beside the text, in the container."), [];
  let n2 = B(t2.name);
  if (n2 === "br") return [W("br", {}, {}, [])];
  if (n2 === "dropped") return P(e2, t2, "warning", `<${t2.name}> is dropped: it is not in the slide subset.`), [];
  if (typeof n2 == "string" && it.has(n2)) {
    n2 !== t2.name && t2.name !== "strong" && t2.name !== "em" && P(e2, t2, "note", `<${t2.name}> is read as <${n2}>.`);
    let r2 = z(e2, n2, t2);
    return n2 === "a" && r2.href !== void 0 && !/^(https?:|mailto:|#)/.test(r2.href) && (P(e2, t2, "warning", `<a href="${r2.href.slice(0, 60)}"> loses its link: links are https:, mailto: or #slide-id.`), delete r2.href), [W(n2, r2, R(e2, n2, t2), U(e2, t2.children))];
  }
  return n2 === "img" || n2 === "x-icon" || n2 === "x-shape" ? (P(e2, t2, "warning", `<${t2.name}> inside text is dropped: place it beside the text, in the container.`), []) : (n2 === "unknown" && P(e2, t2, "note", `<${t2.name}> is not in the slide subset; its words are kept.`), U(e2, t2.children));
}
function Et(e2) {
  let t2 = Dt(e2);
  Ot(t2, "start"), Ot(t2, "end");
  let n2 = kt(t2);
  for (; n2.at(-1)?.type === "element" && n2.at(-1).tag === "br"; ) n2.pop();
  return n2;
}
function Dt(e2, t2 = { space: true }) {
  let n2 = [];
  for (let r2 of e2) if (r2.type === "text") {
    let e3 = r2.text.replace(/[ \t\n\r\f]+/g, " ");
    t2.space && e3.startsWith(" ") && (e3 = e3.slice(1)), e3 !== "" && (t2.space = e3.endsWith(" "));
    let i2 = n2.at(-1);
    i2?.type === "text" ? n2[n2.length - 1] = {
      type: "text",
      text: i2.text + e3
    } : n2.push({
      type: "text",
      text: e3
    });
  } else r2.type === "element" ? (r2.tag === "br" && (t2.space = true), n2.push({
    ...r2,
    children: Dt(r2.children, t2)
  })) : n2.push(r2);
  return n2;
}
function Ot(e2, t2) {
  let n2 = t2 === "start" ? e2.keys() : [...e2.keys()].reverse();
  for (let r2 of n2) {
    let n3 = e2[r2];
    if (n3.type === "text") {
      let i2 = t2 === "start" ? n3.text.replace(/^ /, "") : n3.text.replace(/ $/, "");
      if (e2[r2] = {
        type: "text",
        text: i2
      }, i2 !== "") break;
    } else {
      if (n3.type === "element" && n3.tag === "br") break;
      if (n3.type === "element") {
        let i2 = [...n3.children];
        if (Ot(i2, t2), e2[r2] = {
          ...n3,
          children: i2
        }, i2.some((e3) => e3.type !== "text" || e3.text !== "")) break;
      }
    }
  }
  for (let t3 = 0; t3 < e2.length; t3 += 1) {
    let n3 = e2[t3];
    if (n3.type === "element" && n3.tag === "br") {
      let n4 = e2[t3 - 1], r2 = e2[t3 + 1];
      n4?.type === "text" && (e2[t3 - 1] = {
        type: "text",
        text: n4.text.replace(/ $/, "")
      }), r2?.type === "text" && (e2[t3 + 1] = {
        type: "text",
        text: r2.text.replace(/^ /, "")
      });
    }
  }
}
function kt(e2) {
  return e2.flatMap((e3) => {
    if (e3.type === "text") return e3.text === "" ? [] : [e3];
    if (e3.type === "element" && it.has(e3.tag)) {
      let t2 = kt(e3.children);
      return t2.length === 0 ? [] : [{
        ...e3,
        children: t2
      }];
    }
    return [e3];
  });
}
var At = [
  [/<script\b/i, "holds a <script>"],
  [/[\s/"']on[a-z]+\s*=/i, "holds an event handler"],
  [/<foreignObject\b/i, "holds a <foreignObject>"],
  [/<style\b/i, "holds a <style>"],
  [/javascript:/i, "names javascript:"],
  [/(?:xlink:)?href\s*=\s*(?!["']?#)/i, "refers to something outside itself"],
  [/url\(\s*["']?(?!#)/i, "refers to something outside itself"],
  [/<(iframe|embed|object|video|audio|image)\b/i, "holds media"],
  [/<(?:set|animate\w*)\b[^>]*attributeName\s*=\s*["']?\s*(?:xlink:)?(?:href|on|style)/i, "animates a link, a handler or a style"]
];
function jt(e2) {
  if (e2.attributes.some((e3) => /^on/i.test(e3.name))) return "holds an event handler";
  if (e2.attributes.some((e3) => /href$/i.test(e3.name) && !e3.value.startsWith("#"))) return "refers to something outside itself";
  let t2 = T(e2.inner), n2 = t2.replace(/[\t\n\r]/g, "");
  return At.find(([e3]) => e3.test(t2) || e3.test(n2))?.[1];
}
function Mt(e2, t2) {
  let n2 = jt(t2);
  if (n2 !== void 0) return P(e2, t2, "warning", `An <svg> is dropped: it ${n2}. A drawing holds shapes and its own #id references only.`), [];
  if (t2.inner.length > Ke) return P(e2, t2, "warning", `An <svg> of ${t2.inner.length} bytes is dropped: a drawing is at most ${Ke} bytes.`), [];
  e2.elements += 1;
  let r2 = {};
  for (let { name: e3, value: n3 } of t2.attributes) e3 === "style" || e3 === "xmlns" || e3.startsWith("xmlns:") || (r2[e3] = n3);
  return r2["aria-label"] === void 0 && P(e2, t2, "note", "An <svg> without aria-label: say what it shows, for a reader who cannot see it."), [{
    type: "svg",
    attributes: r2,
    style: R(e2, "svg", t2),
    markup: t2.inner.trim()
  }];
}
function W(e2, t2, n2, r2) {
  return {
    type: "element",
    tag: e2,
    attributes: t2,
    style: n2,
    children: r2
  };
}
var Nt = [
  "id",
  "kind",
  "name",
  "src",
  "alt",
  "href",
  "x1",
  "y1",
  "x2",
  "y2",
  "from",
  "head",
  "route",
  "data-crop",
  "data-build-in",
  "data-build-out"
];
function G(e2, t2) {
  let n2 = Object.keys(e2).sort((e3, t3) => {
    let n3 = Nt.indexOf(e3), r3 = Nt.indexOf(t3);
    return (n3 === -1 ? 99 : n3) - (r3 === -1 ? 99 : r3) || e3.localeCompare(t3);
  }).map((t3) => ` ${t3}="${D(e2[t3])}"`), r2 = Me(t2);
  return n2.join("") + (r2 === "" ? "" : ` style="${D(r2)}"`);
}
function Pt(e2) {
  return e2.map((e3) => e3.type === "text" ? E(e3.text) : e3.type === "svg" ? "" : e3.tag === "br" ? "<br>" : `<${e3.tag}${G(e3.attributes, e3.style)}>${Pt(e3.children)}</${e3.tag}>`).join("");
}
var Ft = /* @__PURE__ */ new Set([
  "img",
  "hr",
  "br"
]);
function It(e2, t2) {
  if (e2.type === "text") return t2 + E(e2.text);
  if (e2.type === "svg") return `${t2}<svg${G(e2.attributes, e2.style)}>${e2.markup}</svg>`;
  let n2 = `${t2}<${e2.tag}${G(e2.attributes, e2.style)}>`;
  return Ft.has(e2.tag) ? n2 : e2.tag === "x-shape" || e2.tag === "x-icon" || e2.tag === "x-connector" ? `${n2}</${e2.tag}>` : e2.tag === "div" || e2.tag === "ul" || e2.tag === "ol" || e2.tag === "table" || e2.tag === "tr" ? e2.children.length === 0 ? `${n2}</${e2.tag}>` : [
    n2,
    ...e2.children.map((e3) => It(e3, `${t2}  `)),
    `${t2}</${e2.tag}>`
  ].join("\n") : `${n2}${Pt(e2.children)}</${e2.tag}>`;
}
function Lt(e2) {
  let t2 = { id: e2.id };
  e2.transition !== void 0 && (t2["data-transition"] = e2.transition), e2.section !== void 0 && (t2["data-section"] = e2.section);
  let n2 = e2.hidden === true ? " hidden" : "", r2 = e2.notes.trim() === "" ? [] : [`<aside>${E(e2.notes.trim())}</aside>`];
  return [
    `<section${G(t2, e2.style)}${n2}>`,
    ...e2.children.map((e3) => It(e3, "")),
    ...r2,
    "</section>"
  ].join("\n");
}
function Rt(e2) {
  let t2 = e2.fontFaces.map((e3) => `@font-face{font-family:"${e3.family.replace(/["\\]/g, "")}";src:url(${e3.src})}`);
  return [
    "<!doctype html>",
    "<html>",
    "<head>",
    '<meta charset="utf-8">',
    `<title>${E(e2.title)}</title>`,
    ...e2.fontLinks.map((e3) => `<link rel="stylesheet" href="${D(e3)}">`),
    ...t2.length === 0 ? [] : [`<style>${t2.join("")}</style>`],
    "</head>",
    `<body${G({}, e2.style)}>`,
    ...e2.slides.map(Lt),
    "</body>",
    "</html>",
    ""
  ].join("\n");
}
function zt(e2) {
  return e2.map((e3) => It(e3, "")).join("\n");
}
function Bt(e2) {
  let { deck: t2 } = lt(`<section id="paste">${e2}</section>`);
  return [...t2.slides[0]?.children ?? []];
}
var Vt = 24;
function Ht(e2) {
  let t2 = e2.filter((e3) => e3.severity === "warning"), n2 = t2.slice(0, Vt).map((e3) => `${e3.slide === void 0 ? "" : `Slide ${e3.slide}, `}line ${e3.line}: ${e3.message}`);
  return t2.length > Vt ? [...n2, `\u2026and ${t2.length - Vt} more like these.`] : n2;
}
function* Ut(e2, t2 = []) {
  for (let [n2, r2] of e2.entries()) {
    let e3 = [...t2, n2];
    yield {
      node: r2,
      path: e3
    }, r2.type === "element" && (yield* Ut(r2.children, e3));
  }
}
function K(e2) {
  return e2.map((e3) => {
    if (e3.type === "text") return e3.text;
    if (e3.type === "svg") return "";
    if (e3.tag === "br") return "\n";
    let t2 = K(e3.children);
    return rt.has(e3.tag) || e3.tag === "li" || e3.tag === "div" || e3.tag === "tr" ? `${t2}
` : e3.tag === "td" || e3.tag === "th" ? `${t2}	` : t2;
  }).join("");
}
function Wt(e2) {
  for (let { node: t2 } of Ut(e2.children)) if (t2.type === "element" && (t2.tag === "h1" || t2.tag === "h2")) return K(t2.children).trim();
  return K(e2.children).trim().split("\n")[0]?.trim() ?? "";
}
function Gt(e2) {
  return rt.has(e2) || e2 === "li" || e2 === "th" || e2 === "td";
}
var Kt = `
.deck-root{font-family:system-ui,-apple-system,"Segoe UI","Noto Sans","PingFang SC","Hiragino Sans",sans-serif;color:#1d1d1f;color-scheme:light}
.deck-slide{position:relative;width:${A}px;height:${j}px;overflow:hidden;display:flex;flex-direction:column;background:#ffffff;font-size:32px;line-height:1.4;overflow-wrap:break-word;-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility}
.deck-slide,.deck-slide *{margin:0;box-sizing:border-box;corner-shape:round}
.deck-slide div{display:flex;flex-direction:column;min-width:0}
.deck-slide h1{font-size:96px;font-weight:600;line-height:1.1}
.deck-slide h2{font-size:64px;font-weight:600;line-height:1.15}
.deck-slide h3{font-size:44px;font-weight:600;line-height:1.2}
.deck-slide ul,.deck-slide ol{padding-left:1.25em}
.deck-slide ul{list-style:disc}
.deck-slide ol{list-style:decimal}
.deck-slide li+li{margin-top:.25em}
.deck-slide a{color:inherit;text-decoration:underline}
.deck-slide b{font-weight:700}
.deck-slide img{display:block;max-width:none;object-fit:cover}
.deck-slide table{border-collapse:collapse;font-variant-numeric:tabular-nums}
.deck-slide th,.deck-slide td{padding:.35em .6em;border-bottom:1px solid rgb(128 128 128 / .3);text-align:left;vertical-align:top}
.deck-slide th{font-weight:600}
.deck-slide hr{border:0;border-top:2px solid currentColor;width:100%;flex:none}
.deck-slide .deck-shape,.deck-slide .deck-icon{flex:none}
.deck-slide .deck-shape>svg,.deck-slide .deck-icon>svg{display:block;width:100%;height:100%;overflow:visible}
.deck-slide .deck-connector{position:absolute;left:0;top:0;width:100%;height:100%;overflow:visible;pointer-events:none}
`;
var qt = "\n@keyframes deck-fade-in { from { opacity: 0 } to { opacity: 1 } }\n@keyframes deck-fade-out { from { opacity: 1 } to { opacity: 0 } }\n@keyframes deck-push-in { from { transform: translateX(100%) } to { transform: none } }\n@keyframes deck-push-out { from { transform: none } to { transform: translateX(-100%) } }\n@keyframes deck-push-in-back { from { transform: translateX(-100%) } to { transform: none } }\n@keyframes deck-push-out-back { from { transform: none } to { transform: translateX(100%) } }\n@keyframes deck-build-fade { from { opacity: 0 } }\n@keyframes deck-build-rise { from { opacity: 0; transform: translateY(48px) } }\n@keyframes deck-build-drop { from { opacity: 0; transform: translateY(-48px) } }\n@keyframes deck-build-left { from { opacity: 0; transform: translateX(-96px) } }\n@keyframes deck-build-right { from { opacity: 0; transform: translateX(96px) } }\n@keyframes deck-build-scale { from { opacity: 0; transform: scale(0.6) } }\n@keyframes deck-build-pop { 0% { opacity: 0; transform: scale(0.5) } 70% { opacity: 1; transform: scale(1.06) } 100% { transform: none } }\n";
var Jt = {
  diamond: "50,0 100,50 50,100 0,50",
  triangle: "50,0 100,100 0,100",
  "arrow-right": "0,30 60,30 60,0 100,50 60,100 60,70 0,70",
  "arrow-left": "100,30 40,30 40,0 0,50 40,100 40,70 100,70",
  "arrow-up": "30,100 30,40 0,40 50,0 100,40 70,40 70,100",
  "arrow-down": "30,0 30,60 0,60 50,100 100,60 70,60 70,0"
};
function Yt(e2, t2 = {}, n2 = [], r2 = Xt) {
  return e2.flatMap((e3, i2) => Zt(e3, t2, [...n2, i2], r2));
}
var Xt = {
  width: A,
  height: j
};
function Zt(e2, t2, n2, r2) {
  let i2 = t2.paths === true ? { path: n2 } : {};
  if (e2.type === "text") return [{
    kind: "text",
    text: e2.text
  }];
  if (e2.type === "svg") {
    let { "aria-label": n3, ...r3 } = e2.attributes, a2 = `<svg xmlns="http://www.w3.org/2000/svg"${Object.entries(r3).map(([e3, t3]) => ` ${e3}="${D(t3)}"`).join("")}>${e2.markup}</svg>`;
    return t2.svgAsImage === false ? [{
      kind: "markup",
      attributes: {},
      style: {
        ...$t(e2),
        ...e2.style,
        display: "block"
      },
      markup: a2.replace("<svg ", '<svg width="100%" height="100%" '),
      ...i2
    }] : [{
      kind: "element",
      tag: "img",
      attributes: {
        src: `data:image/svg+xml;charset=utf-8,${encodeURIComponent(a2)}`,
        alt: n3 ?? "",
        draggable: "false"
      },
      style: {
        "object-fit": "contain",
        ...$t(e2),
        ...e2.style
      },
      children: [],
      ...i2
    }];
  }
  switch (e2.tag) {
    case "x-shape":
      return [tn(e2, i2)];
    case "x-icon":
      return [{
        kind: "markup",
        class: "deck-icon",
        attributes: q(e2),
        style: {
          width: "64px",
          height: "64px",
          ...e2.style
        },
        markup: We(e2.attributes.name ?? ""),
        ...i2
      }];
    case "x-connector":
      return [rn(e2, i2, r2, t2.hitAreas === true)];
    case "img": {
      let n3 = e2.attributes.src, r3 = n3 === void 0 ? void 0 : t2.resolveAsset?.(n3) ?? n3;
      return [{
        kind: "element",
        tag: "img",
        attributes: {
          ...r3 === void 0 ? {} : { src: r3 },
          alt: e2.attributes.alt ?? "",
          draggable: "false",
          ...q(e2)
        },
        style: {
          ...r3 === void 0 ? { background: "rgb(128 128 128 / .15)" } : {},
          ...en(e2),
          ...e2.style
        },
        children: [],
        ...i2
      }];
    }
    default: {
      let a2 = q(e2);
      return e2.tag === "a" && e2.attributes.href !== void 0 && (a2.href = e2.attributes.href, a2.target = "_blank", a2.rel = "noopener"), [{
        kind: "element",
        tag: e2.tag,
        attributes: a2,
        style: { ...e2.style },
        children: Yt(e2.children, t2, n2, Qt(e2, r2)),
        ...i2
      }];
    }
  }
}
function Qt(e2, t2) {
  return e2.tag !== "div" || e2.style.position !== "relative" ? t2 : {
    width: f(e2.style.width ?? "") ?? t2.width,
    height: f(e2.style.height ?? "") ?? t2.height
  };
}
function $t(e2) {
  let t2 = {}, n2 = f(e2.attributes.width ?? ""), r2 = f(e2.attributes.height ?? "");
  return n2 !== void 0 && (t2.width = `${n2}px`), r2 !== void 0 && (t2.height = `${r2}px`), t2;
}
function en(e2) {
  let t2 = vt(e2.attributes["data-crop"] ?? "");
  return t2 === void 0 ? {} : {
    "object-position": `${t2.x} ${t2.y}`,
    "transform-origin": `${t2.x} ${t2.y}`,
    scale: String(t2.zoom)
  };
}
function q(e2) {
  let t2 = {};
  for (let n2 of [
    "id",
    "data-build-in",
    "data-build-out"
  ]) {
    let r2 = e2.attributes[n2];
    r2 !== void 0 && (t2[n2] = r2);
  }
  return t2;
}
function tn(e2, t2) {
  let n2 = e2.attributes.kind ?? "rect", { background: r2, border: i2, ...a2 } = e2.style, o2 = q(e2);
  if (n2 === "rect" || n2 === "rounded" || n2 === "ellipse") return {
    kind: "element",
    tag: "div",
    attributes: o2,
    style: {
      width: "240px",
      height: "160px",
      ...n2 === "rounded" ? { "border-radius": "24px" } : n2 === "ellipse" ? { "border-radius": "50%" } : {},
      ...r2 === void 0 ? { background: "#d4d4d8" } : { background: r2 },
      ...i2 === void 0 ? {} : { border: i2 },
      ...a2
    },
    children: [],
    class: "deck-shape",
    ...t2
  };
  let s2 = r2 ?? "#d4d4d8", c2 = nn(i2), l2 = n2 === "line" ? `<line x1="0" y1="50" x2="100" y2="50" stroke="${D(c2?.color ?? s2)}" stroke-width="${c2?.width ?? 4}" vector-effect="non-scaling-stroke"${J(c2?.style)}/>` : `<polygon points="${Jt[n2] ?? Jt.diamond}" fill="${D(s2)}"${c2 === void 0 ? "" : ` stroke="${D(c2.color)}" stroke-width="${c2.width}" vector-effect="non-scaling-stroke" stroke-linejoin="round"${J(c2.style)}`}/>`;
  return {
    kind: "markup",
    class: "deck-shape",
    attributes: o2,
    style: {
      width: "240px",
      height: n2 === "line" ? "8px" : "160px",
      ...a2
    },
    markup: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="none">${l2}</svg>`,
    ...t2
  };
}
function nn(e2) {
  if (e2 === void 0 || e2 === "none") return;
  let t2 = e2.split(/\s+(?![^(]*\))/);
  return {
    width: f(t2[0] ?? "") ?? 1,
    style: t2[1] ?? "solid",
    color: t2[2] ?? "#000000"
  };
}
function J(e2) {
  return e2 === "dashed" ? ' stroke-dasharray="8 6"' : e2 === "dotted" ? ' stroke-dasharray="2 4" stroke-linecap="round"' : "";
}
function Y(e2, t2) {
  if (e2 === void 0) return;
  let n2 = /^(-?[\d.]+)%$/.exec(e2.trim());
  return n2 === null ? f(e2) : Number(n2[1]) / 100 * t2;
}
function rn(e2, t2, n2, r2) {
  let i2 = e2.style.color ?? "#1d1d1f", a2 = nn(e2.style.border), o2 = a2?.width ?? 3, s2 = e2.attributes.head ?? "end", c2 = `deck-arrow-${i2.replace(/[^a-z0-9]/gi, "")}-${o2}`, l2 = `<marker id="${c2}" viewBox="0 0 10 10" refX="8" refY="5" markerUnits="userSpaceOnUse" markerWidth="${10 + o2 * 4}" markerHeight="${10 + o2 * 4}" orient="auto-start-reverse"><path d="M0 0 10 5 0 10z" fill="${D(i2)}"/></marker>`, u2 = `${s2 === "end" || s2 === "both" ? ` marker-end="url(#${c2})"` : ""}${s2 === "both" ? ` marker-start="url(#${c2})"` : ""}`, d2 = Y(e2.attributes.x1, n2.width), f2 = Y(e2.attributes.y1, n2.height), p2 = Y(e2.attributes.x2, n2.width), m2 = Y(e2.attributes.y2, n2.height), h2 = (e3) => `<polyline points="${e3}" fill="none" stroke="${D(i2)}" stroke-width="${o2}" stroke-linejoin="round"${J(a2?.style)}${u2}/>` + (r2 ? `<polyline points="${e3}" fill="none" stroke="transparent" stroke-width="24" pointer-events="stroke"/>` : "");
  if (d2 !== void 0 && f2 !== void 0 && p2 !== void 0 && m2 !== void 0) {
    let r3 = e2.attributes.route ?? "straight", i3 = (d2 + p2) / 2, a3 = r3 === "hv" ? `${d2},${f2} ${p2},${f2} ${p2},${m2}` : r3 === "vh" ? `${d2},${f2} ${d2},${m2} ${p2},${m2}` : r3 === "elbow" ? `${d2},${f2} ${i3},${f2} ${i3},${m2} ${p2},${m2}` : `${d2},${f2} ${p2},${m2}`;
    return {
      kind: "markup",
      attributes: q(e2),
      style: {
        position: "absolute",
        left: "0",
        top: "0",
        width: `${n2.width}px`,
        height: `${n2.height}px`,
        "pointer-events": "none",
        ...e2.style.opacity === void 0 ? {} : { opacity: e2.style.opacity }
      },
      markup: `<svg xmlns="http://www.w3.org/2000/svg" width="${n2.width}" height="${n2.height}" viewBox="0 0 ${n2.width} ${n2.height}" style="overflow:visible"><defs>${l2}</defs>${h2(a3)}</svg>`,
      ...t2
    };
  }
  let g2 = e2.attributes.from ?? "tl", [_2, v2, y2, b2] = g2 === "tr" ? [
    100,
    0,
    0,
    100
  ] : g2 === "bl" ? [
    0,
    100,
    100,
    0
  ] : g2 === "br" ? [
    100,
    100,
    0,
    0
  ] : [
    0,
    0,
    100,
    100
  ], { border: ee2, color: x2, ...te2 } = e2.style;
  return {
    kind: "markup",
    attributes: q(e2),
    style: {
      width: "96px",
      height: `${Math.max(o2, 2)}px`,
      "align-self": "center",
      flex: "none",
      ...te2
    },
    markup: `<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" style="overflow:visible;display:block"><defs>${l2}</defs><svg viewBox="0 0 100 100" preserveAspectRatio="none" overflow="visible"><line x1="${_2}" y1="${v2 === b2 ? 50 : v2}" x2="${y2}" y2="${v2 === b2 ? 50 : b2}" stroke="${D(i2)}" stroke-width="${o2}" vector-effect="non-scaling-stroke"${J(a2?.style)}${u2}/></svg></svg>`,
    ...t2
  };
}
function an(e2) {
  return Object.entries(e2).map(([e3, t2]) => `${e3}:${t2}`).join(";");
}
var on = /* @__PURE__ */ new Set([
  "img",
  "hr",
  "br"
]);
function sn(e2) {
  return e2.map((e3) => {
    if (e3.kind === "text") return E(e3.text);
    let t2 = e3.class === void 0 ? "" : ` class="${e3.class}"`, n2 = an(e3.style), r2 = n2 === "" ? "" : ` style="${D(n2)}"`, i2 = Object.entries(e3.attributes).map(([e4, t3]) => ` ${e4}="${D(t3)}"`).join("");
    if (e3.kind === "markup") return `<div${t2}${i2}${r2}>${e3.markup}</div>`;
    let a2 = `<${e3.tag}${t2}${i2}${r2}>`;
    return on.has(e3.tag) ? a2 : `${a2}${sn(e3.children)}</${e3.tag}>`;
  }).join("");
}
function cn(e2, t2 = {}) {
  let n2 = [
    `id="${D(e2.id)}"`,
    ...e2.transition === void 0 ? [] : [`data-transition="${e2.transition}"`],
    ...e2.hidden === true ? ["hidden"] : []
  ], r2 = an(e2.style);
  return `<section class="deck-slide" ${n2.join(" ")}${r2 === "" ? "" : ` style="${D(r2)}"`}>${sn(Yt(e2.children, t2))}</section>`;
}
function ln(e2, t2 = (e3) => e3) {
  let n2 = e2.fontFaces.map((e3) => `@font-face{font-family:"${e3.family.replace(/["\\]/g, "")}";src:url("${t2(e3.src)}");font-display:swap}`).join("");
  return [...e2.fontLinks.map((e3) => `<link rel="stylesheet" href="${D(e3)}">`), ...n2 === "" ? [] : [`<style>${n2}</style>`]].join("\n");
}
function un(e2) {
  return an({ ...e2 });
}
function dn(e2) {
  return e2.join(".");
}
function fn(e2) {
  return e2 === "" ? [] : e2.split(".").map(Number);
}
function pn(e2, t2) {
  return e2.length === t2.length && e2.every((e3, n2) => e3 === t2[n2]);
}
function mn(e2, t2) {
  return t2.length <= e2.length && t2.every((t3, n2) => t3 === e2[n2]);
}
function hn(e2) {
  return e2.slice(0, -1);
}
function gn(e2, t2) {
  let n2, r2 = e2;
  for (let e3 of t2) {
    if (n2 = r2[e3], n2 === void 0) return;
    r2 = n2.type === "element" ? n2.children : [];
  }
  return n2;
}
function _n(e2, t2) {
  let n2 = gn(e2, t2);
  return n2?.type === "element" ? n2 : void 0;
}
function vn(e2, t2) {
  if (t2.length === 0) return e2;
  let n2 = gn(e2, t2);
  return n2?.type === "element" ? n2.children : [];
}
function X(e2, t2, n2) {
  let [r2, ...i2] = t2;
  if (r2 === void 0 || e2[r2] === void 0) return [...e2];
  let a2 = [...e2], o2 = e2[r2];
  return a2[r2] = i2.length === 0 ? n2(o2) : o2.type === "element" ? {
    ...o2,
    children: X(o2.children, i2, n2)
  } : o2, a2;
}
function yn(e2, t2, n2) {
  return t2.length === 0 ? n2(e2) : X(e2, t2, (e3) => e3.type === "element" ? {
    ...e3,
    children: n2(e3.children)
  } : e3);
}
function bn(e2) {
  return [...e2].sort((e3, t2) => {
    for (let n2 = 0; n2 < Math.min(e3.length, t2.length); n2 += 1) if (e3[n2] !== t2[n2]) return t2[n2] - e3[n2];
    return t2.length - e3.length;
  });
}
function xn(e2, t2) {
  let n2 = t2.filter((e3) => !t2.some((t3) => t3 !== e3 && t3.length < e3.length && mn(e3, t3))), r2 = [...e2];
  for (let e3 of bn(n2)) {
    let t3 = e3.at(-1);
    r2 = yn(r2, hn(e3), (e4) => e4.filter((e5, n3) => n3 !== t3));
  }
  return r2;
}
function Sn(e2, t2, n2, r2) {
  return yn(e2, t2, (e3) => [
    ...e3.slice(0, n2),
    ...r2,
    ...e3.slice(n2)
  ]);
}
function Cn(e2, t2, n2) {
  let r2 = { ...t2 };
  for (let [t3, i2] of Object.entries(n2)) {
    if (i2 === void 0 || i2 === "") {
      delete r2[t3];
      continue;
    }
    let n3 = Fe(e2, t3, i2);
    n3 !== void 0 && (r2[t3] = n3);
  }
  return r2;
}
function wn(e2, t2) {
  return e2.type === "text" ? e2 : {
    ...e2,
    style: Cn(e2.type === "svg" ? "svg" : e2.tag, e2.style, t2)
  };
}
function Tn(e2, t2, n2) {
  if (e2.type === "text") return e2;
  let r2 = { ...e2.attributes };
  return n2 === void 0 ? delete r2[t2] : r2[t2] = n2, {
    ...e2,
    attributes: r2
  };
}
function En(e2, t2, n2) {
  let r2 = e2.slides[t2];
  if (r2 === void 0) return e2;
  let i2 = [...e2.slides];
  return i2[t2] = n2(r2), {
    ...e2,
    slides: i2
  };
}
function Dn(e2, t2, n2) {
  return En(e2, t2, (e3) => ({
    ...e3,
    children: n2(e3.children)
  }));
}
function On(e2) {
  let t2 = /rotate\((-?[\d.]+)(deg|turn|rad)\)/.exec(e2.transform ?? "");
  if (t2 === null) return 0;
  let n2 = Number(t2[1]);
  return t2[2] === "turn" ? n2 * 360 : t2[2] === "rad" ? n2 * 180 / Math.PI : n2;
}
function kn(e2, t2) {
  let n2 = Math.round(t2 * 10) / 10, r2 = (e2 ?? "").split(/\s+(?![^(]*\))/).filter((e3) => e3 !== "" && e3 !== "none" && !e3.startsWith("rotate(")), i2 = r2.filter((e3) => e3.startsWith("translate")), a2 = r2.filter((e3) => !e3.startsWith("translate")), o2 = n2 === 0 || n2 === 360 ? [] : [`rotate(${n2}deg)`], s2 = [
    ...i2,
    ...o2,
    ...a2
  ].join(" ");
  return s2 === "" ? void 0 : s2;
}
function An(e2, t2 = {}, n2 = [], r2 = {}) {
  return {
    type: "element",
    tag: e2,
    attributes: r2,
    style: t2,
    children: n2
  };
}
function jn(e2) {
  return {
    type: "text",
    text: e2
  };
}
function Mn(e2, t2) {
  for (let n2 = t2.length; n2 > 0; n2--) {
    let r2 = t2.slice(0, n2);
    if (_n(e2, r2)?.tag === "table") return {
      table: r2,
      row: t2[n2],
      column: t2[n2 + 1]
    };
  }
}
var Z = (e2) => e2.type === "element" && e2.tag === "tr";
var Q = (e2) => e2.type === "element" && (e2.tag === "td" || e2.tag === "th");
var Nn = (e2) => e2.children.some(Q) && e2.children.filter(Q).every((e3) => e3.tag === "th");
function Pn(e2, t2 = e2.tag) {
  let { id: n2, ...r2 } = e2.attributes;
  return An(t2, e2.style, [], r2);
}
function Fn(e2, t2) {
  let n2 = e2.children, r2 = Math.max(0, Math.min(t2, n2.length)), i2 = [
    n2[r2],
    n2[r2 - 1],
    ...n2
  ].filter((e3) => e3 !== void 0 && Z(e3)), a2 = i2.find((e3) => !Nn(e3)) ?? i2[0];
  if (a2 === void 0) return e2;
  let o2 = Nn(a2), { id: s2, ...c2 } = a2.attributes, l2 = An("tr", a2.style, a2.children.filter(Q).map((e3) => Pn(e3, o2 ? "td" : e3.tag)), c2);
  return {
    ...e2,
    children: [
      ...n2.slice(0, r2),
      l2,
      ...n2.slice(r2)
    ]
  };
}
function $(e2, t2) {
  return {
    ...e2,
    children: e2.children.map((e3) => {
      if (!Z(e3)) return e3;
      let n2 = Math.max(0, Math.min(t2, e3.children.length)), r2 = [
        e3.children[n2 - 1],
        e3.children[n2],
        ...e3.children
      ].find((e4) => e4 !== void 0 && Q(e4));
      return r2 === void 0 ? e3 : {
        ...e3,
        children: [
          ...e3.children.slice(0, n2),
          Pn(r2),
          ...e3.children.slice(n2)
        ]
      };
    })
  };
}
function In(e2, t2) {
  return e2.children.filter(Z).length <= 1 ? e2 : {
    ...e2,
    children: e2.children.filter((e3, n2) => n2 !== t2)
  };
}
function Ln(e2, t2) {
  return Math.max(0, ...e2.children.filter(Z).map((e3) => e3.children.filter(Q).length)) <= 1 ? e2 : {
    ...e2,
    children: e2.children.map((e3) => Z(e3) ? {
      ...e3,
      children: e3.children.filter((e4, n2) => n2 !== t2)
    } : e3)
  };
}
var Rn = [
  "rowAbove",
  "rowBelow",
  "columnLeft",
  "columnRight",
  "removeRow",
  "removeColumn"
];
function zn(e2, t2, n2) {
  let r2 = Mn(e2, t2), i2 = r2 === void 0 ? void 0 : _n(e2, r2.table);
  if (r2 === void 0 || i2 === void 0) return;
  let a2 = i2.children.filter(Z), o2 = a2.length - 1, s2 = Math.max(0, ...a2.map((e3) => e3.children.filter(Q).length)) - 1, c2 = r2.row ?? o2, l2 = r2.column ?? s2, u2 = {
    rowAbove: () => [
      Fn(i2, c2),
      1,
      0
    ],
    rowBelow: () => [
      Fn(i2, c2 + 1),
      0,
      0
    ],
    columnLeft: () => [
      $(i2, l2),
      0,
      1
    ],
    columnRight: () => [
      $(i2, l2 + 1),
      0,
      0
    ],
    removeRow: () => o2 < 1 ? void 0 : [
      In(i2, c2),
      NaN,
      0
    ],
    removeColumn: () => s2 < 1 ? void 0 : [
      Ln(i2, l2),
      0,
      NaN
    ]
  }[n2]();
  if (u2 === void 0) return;
  let [d2, f2, p2] = u2, m2 = r2.row !== void 0 && r2.column !== void 0 && !Number.isNaN(f2 + p2);
  return {
    nodes: X(e2, r2.table, () => d2),
    selection: m2 ? [
      ...r2.table,
      r2.row + f2,
      r2.column + p2
    ] : r2.table
  };
}
export {
  Kt as DECK_BASE_CSS,
  qe as DECK_BLOCK_TAGS,
  j as DECK_HEIGHT,
  O as DECK_ICONS,
  Ue as DECK_ICON_NAMES,
  Je as DECK_INLINE_TAGS,
  qt as DECK_MOTION_CSS,
  Ye as DECK_SHAPE_KINDS,
  N as DECK_TRANSITIONS,
  A as DECK_WIDTH,
  Rn as TABLE_EDITS,
  vn as childrenAt,
  ln as deckFontMarkup,
  k as deckIconBody,
  We as deckIconMarkup,
  K as deckNodesText,
  un as deckRootStyle,
  Wt as deckSlideTitle,
  Pe as deckStyleApplies,
  T as decodeEntities,
  Ht as describeDeckDiagnostics,
  zn as editTable,
  An as element,
  _n as elementAt,
  D as escapeAttribute,
  E as escapeText,
  Sn as insertAt,
  $ as insertTableColumn,
  Fn as insertTableRow,
  pt as isAssetPath,
  x as isColor,
  mt as isDeckImageSource,
  Ne as isDeckStyleProperty,
  Gt as isDeckTextBlock,
  mn as isWithin,
  gn as nodeAt,
  Fe as normalizeDeckStyleValue,
  hn as parentOf,
  fn as parsePathKey,
  wn as patchNodeStyle,
  Cn as patchStyle,
  dn as pathKey,
  lt as readDeck,
  vt as readDeckCrop,
  Bt as readDeckNodes,
  ke as readDeckStyle,
  f as readPixels,
  xn as removeAt,
  Ln as removeTableColumn,
  In as removeTableRow,
  Yt as renderDeckNodes,
  sn as renderNodesHtml,
  cn as renderSlideHtml,
  On as rotationOf,
  pn as samePath,
  Tn as setAttribute,
  y as splitTop,
  nn as strokeOf,
  e as styleTargetOf,
  Mn as tableAt,
  jn as text,
  Et as tidyInline,
  Re as tokenizeHtml,
  gt as uniqueId,
  X as updateAt,
  yn as updateChildrenAt,
  En as updateSlide,
  Dn as updateSlideChildren,
  Ut as walkDeckNodes,
  kn as withRotation,
  Rt as writeDeck,
  zt as writeDeckNodes,
  Me as writeDeckStyle,
  Pt as writeInline
};
