// Generated by scripts/build.mjs — do not edit. The source is @jannchie/slides.

// ../slides/dist/deck-tree-C9fT96fc.js
var e = [
  "background",
  "surface",
  "text",
  "muted",
  "accent",
  "line"
];
var t = {
  id: "minimal-light",
  name: "Minimal white",
  colors: {
    background: "#ffffff",
    surface: "#f4f4f5",
    text: "#0e0e11",
    muted: "#6e6f78",
    accent: "#0e0e11",
    line: "#e4e4e7"
  }
};
var n = {
  id: "minimal-dark",
  name: "Minimal black",
  colors: {
    background: "#0a0a0b",
    surface: "#18181b",
    text: "#f4f4f5",
    muted: "#a1a1aa",
    accent: "#f4f4f5",
    line: "#27272a"
  }
};
var r = [t, n];
function i(e2) {
  return /^[a-z0-9][a-z0-9-]{0,63}$/.test(e2);
}
function a(e2, n2 = r) {
  return n2.find((t2) => t2.id === e2) ?? n2[0] ?? t;
}
function o(t2) {
  return Object.fromEntries(e.map((e2) => [`--${e2}`, t2.colors[e2]]));
}
var s = RegExp(`^var\\(\\s*--(${e.join("|")})\\s*\\)$`, "i");
var c = RegExp(`var\\(\\s*--(?:${e.join("|")})\\s*\\)`, "gi");
function l(e2) {
  let t2 = e2 === void 0 ? null : s.exec(e2.trim());
  return t2 === null ? void 0 : t2[1].toLowerCase();
}
function u(e2) {
  return e2.replace(c, "");
}
function d(e2, t2) {
  let n2 = l(e2);
  return n2 === void 0 ? e2 : t2.colors[n2];
}
function f(e2) {
  switch (e2) {
    case "section":
    case "body":
      return "section";
    case "div":
      return "div";
    case "h1":
    case "h2":
    case "h3":
    case "p":
    case "ul":
    case "ol":
    case "li":
      return "text";
    case "span":
    case "a":
    case "b":
    case "i":
    case "u":
    case "s":
      return "inline";
    case "img":
      return "img";
    case "table":
      return "table";
    case "tr":
      return "row";
    case "th":
    case "td":
      return "cell";
    case "x-shape":
      return "shape";
    case "x-icon":
      return "icon";
    case "x-connector":
      return "connector";
    case "hr":
      return "hr";
    case "svg":
      return "svg";
    default:
      return;
  }
}
var p = [
  "section",
  "div",
  "text",
  "inline",
  "img",
  "table",
  "row",
  "cell",
  "shape",
  "icon",
  "connector",
  "hr",
  "svg"
];
var m = [
  "div",
  "text",
  "img",
  "table",
  "cell",
  "shape",
  "icon",
  "hr",
  "svg"
];
var h = [
  "div",
  "text",
  "img",
  "table",
  "shape",
  "icon",
  "hr",
  "svg",
  "connector"
];
var g = ["section", "div"];
var _ = [
  "section",
  "div",
  "text",
  "table",
  "cell"
];
var v = [
  "section",
  "div",
  "text",
  "img",
  "table",
  "cell",
  "icon"
];
var y = (e2) => ({ value: e2 });
var b = (e2) => ({ refused: e2 });
var ee = /^-?(?:\d+\.?\d*|\.\d+)$/;
function x(e2) {
  return ee.test(e2) ? Number(e2) : void 0;
}
function S(e2) {
  return String(Math.round(e2 * 1e3) / 1e3);
}
function C(e2) {
  let t2 = /^(-?(?:\d+\.?\d*|\.\d+))(px|pt)?$/i.exec(e2.trim());
  if (t2 === null) return;
  let n2 = Number(t2[1]);
  return t2[2]?.toLowerCase() === "pt" ? n2 * 4 / 3 : n2;
}
var te = (e2) => e2 === 0 ? "0" : `${S(e2)}px`;
function w(e2, t2 = -4096, n2 = 8192) {
  let r2 = C(e2);
  return r2 === void 0 ? b(/(em|rem|vw|vh|vmin|vmax|ch|ex)$/i.test(e2) ? "only px lengths" : "a length in px") : r2 < t2 || r2 > n2 ? b(`a length from ${t2} to ${n2}px`) : y(te(r2));
}
function T(e2) {
  let t2 = /^(-?(?:\d+\.?\d*|\.\d+))%$/.exec(e2.trim());
  return t2 === null ? void 0 : Number(t2[1]);
}
function E(e2, t2 = []) {
  let n2 = e2.trim().toLowerCase();
  if (t2.includes(n2)) return y(n2);
  let r2 = T(e2);
  return r2 === void 0 ? w(e2) : y(`${S(r2)}%`);
}
function D(e2) {
  return (t2) => {
    let n2 = t2.trim().toLowerCase();
    return e2.includes(n2) ? y(n2) : b(e2.join(" | "));
  };
}
function ne(e2, t2, n2 = false) {
  return (r2) => {
    let i2 = x(r2.trim());
    return i2 === void 0 || i2 < e2 || i2 > t2 || n2 && !Number.isInteger(i2) ? b(`a ${n2 ? "whole " : ""}number from ${e2} to ${t2}`) : y(S(i2));
  };
}
function O(e2, t2) {
  let n2 = [], r2 = 0, i2, a2 = false, o2 = "";
  for (let s2 of e2) i2 === void 0 ? s2 === '"' || s2 === "'" ? (i2 = s2, o2 += s2) : (s2 === "(" ? r2 += 1 : s2 === ")" && --r2, (t2 === "," ? s2 === "," : /\s/.test(s2)) && r2 === 0 ? (o2.trim() !== "" && n2.push(o2.trim()), o2 = "") : o2 += s2) : (o2 += s2, a2 ? a2 = false : s2 === "\\" ? a2 = true : s2 === i2 && (i2 = void 0));
  return o2.trim() !== "" && n2.push(o2.trim()), n2;
}
var re = new Set("aliceblue antiquewhite aqua aquamarine azure beige bisque black blanchedalmond blue blueviolet brown burlywood cadetblue chartreuse chocolate coral cornflowerblue cornsilk crimson cyan darkblue darkcyan darkgoldenrod darkgray darkgreen darkgrey darkkhaki darkmagenta darkolivegreen darkorange darkorchid darkred darksalmon darkseagreen darkslateblue darkslategray darkslategrey darkturquoise darkviolet deeppink deepskyblue dimgray dimgrey dodgerblue firebrick floralwhite forestgreen fuchsia gainsboro ghostwhite gold goldenrod gray green greenyellow grey honeydew hotpink indianred indigo ivory khaki lavender lavenderblush lawngreen lemonchiffon lightblue lightcoral lightcyan lightgoldenrodyellow lightgray lightgreen lightgrey lightpink lightsalmon lightseagreen lightskyblue lightslategray lightslategrey lightsteelblue lightyellow lime limegreen linen magenta maroon mediumaquamarine mediumblue mediumorchid mediumpurple mediumseagreen mediumslateblue mediumspringgreen mediumturquoise mediumvioletred midnightblue mintcream mistyrose moccasin navajowhite navy oldlace olive olivedrab orange orangered orchid palegoldenrod palegreen paleturquoise palevioletred papayawhip peachpuff peru pink plum powderblue purple rebeccapurple red rosybrown royalblue saddlebrown salmon sandybrown seagreen seashell sienna silver skyblue slateblue slategray slategrey snow springgreen steelblue tan teal thistle tomato turquoise violet wheat white whitesmoke yellow yellowgreen transparent".split(" "));
var ie = /^(rgba?|hsla?)\(\s*[-\d.%\s,/deg]+\)$/i;
function k(e2) {
  let t2 = e2.trim().toLowerCase();
  return l(t2) !== void 0 || /^#(?:[0-9a-f]{3,4}|[0-9a-f]{6}|[0-9a-f]{8})$/.test(t2) || ie.test(t2) || re.has(t2);
}
function ae(t2) {
  let n2 = t2.trim();
  if (/currentcolor/i.test(n2) || /var\(/i.test(u(n2))) return b(`a colour written out \u2014 #hex, rgb(), hsl() or a name \u2014 or a theme colour, var(--${e.join("), var(--")}); not currentColor or any other var()`);
  let r2 = l(n2);
  return r2 === void 0 ? k(n2) ? y(n2.toLowerCase()) : b("a colour: #hex, rgb(), hsl(), a name, or a theme colour such as var(--accent)") : y(`var(--${r2})`);
}
function oe(e2) {
  return /^-?(?:\d+\.?\d*|\.\d+)(deg|turn|rad)$/i.test(e2.trim()) || e2.trim() === "0";
}
var se = /^(repeating-)?(linear|radial)-gradient\((.*)\)$/is;
function ce(e2) {
  let t2 = se.exec(e2.trim());
  if (t2 === null) return b("a colour or a linear-gradient() / radial-gradient()");
  let n2 = O(t2[3], ","), r2 = n2.filter((e3) => k(O(e3, " ")[0] ?? ""));
  if (r2.length < 2 || r2.length > 8) return b("a gradient of 2 to 8 colour stops");
  for (let e3 of n2) {
    let [t3, ...n3] = O(e3, " ");
    if (k(t3 ?? "")) {
      if (!n3.every((e4) => T(e4) !== void 0 || C(e4) !== void 0)) return b("gradient stops as a colour and up to two positions in % or px");
      continue;
    }
    let r3 = O(e3, " ");
    if (!(r3.length === 1 && oe(r3[0]) || r3[0] === "to" && r3.slice(1).every((e4) => [
      "top",
      "bottom",
      "left",
      "right"
    ].includes(e4)) || r3.every((e4) => [
      "circle",
      "ellipse",
      "at",
      "center",
      "top",
      "bottom",
      "left",
      "right",
      "closest-side",
      "farthest-corner"
    ].includes(e4) || T(e4) !== void 0 || C(e4) !== void 0))) return b("a gradient's direction as an angle, `to <side>`, or a radial shape `at X% Y%`");
  }
  return y(e2.trim().replace(/\s+/g, " "));
}
function le(e2) {
  let t2 = e2.trim();
  if (/url\(/i.test(t2)) return b("a colour or a gradient \u2014 an image is an <img>");
  if (k(t2)) {
    let e3 = l(t2);
    return y(e3 === void 0 ? t2.toLowerCase() : `var(--${e3})`);
  }
  let n2 = O(t2, ",");
  if (n2.length > 2 || n2.length === 2 && !k(n2[1])) return b("one gradient, optionally with a colour under it");
  let r2 = ce(n2[0]);
  return "refused" in r2 ? r2 : y(n2.length === 2 ? `${r2.value}, ${n2[1].toLowerCase()}` : r2.value);
}
var ue = [
  "solid",
  "dashed",
  "dotted",
  "double",
  "none"
];
function A(e2) {
  let t2 = e2.trim().toLowerCase();
  if (t2 === "none" || t2 === "0") return y("none");
  let n2 = O(t2, " "), r2 = n2.find((e3) => ue.includes(e3)), i2 = n2.find((e3) => C(e3) !== void 0), a2 = n2.find((e3) => e3 !== r2 && e3 !== i2);
  if (r2 === void 0) return b("a stroke with its style word: `2px solid #ccc`");
  if (n2.length > 3 || a2 !== void 0 && !k(a2)) return b("a width, a style and a colour: `2px solid #ccc`");
  let o2 = i2 === void 0 ? 1 : C(i2);
  return o2 < 0 || o2 > 32 ? b("a stroke from 0 to 32px") : y([
    te(o2),
    r2,
    ...a2 === void 0 ? [] : [a2]
  ].join(" "));
}
function de(e2, t2, n2 = false) {
  return (r2) => {
    let i2 = O(r2.trim(), " ");
    if (i2.length < 1 || i2.length > 4) return b("one to four lengths in px");
    let a2 = i2.map((r3) => n2 && T(r3) !== void 0 ? y(`${S(T(r3))}%`) : w(r3, e2, t2));
    return a2.find((e3) => "refused" in e3) ?? y(a2.map((e3) => e3.value).join(" "));
  };
}
function fe(e2) {
  return (t2) => {
    if (t2.trim().toLowerCase() === "none") return y("none");
    let n2 = O(t2, ",");
    if (n2.length > 8) return b("at most eight shadows");
    for (let t3 of n2) {
      let n3 = O(t3, " ").filter((t4) => !(e2 && t4.toLowerCase() === "inset")), r2 = n3.filter((e3) => k(e3)), i2 = n3.filter((e3) => C(e3) !== void 0);
      if (r2.length !== 1 || i2.length < 2 || i2.length > (e2 ? 4 : 3) || r2.length + i2.length !== n3.length) return b(`shadows as x y${e2 ? " [blur [spread]]" : " [blur]"} and one colour`);
    }
    return y(n2.map((e3) => e3.replace(/\s+/g, " ").trim()).join(", "));
  };
}
var pe = /^(translate|translateX|translateY|rotate|scale|skew|skewX|skewY)\(([^()]*)\)$/;
function me(e2) {
  let t2 = e2.trim();
  if (t2 === "none") return y("none");
  for (let e3 of O(t2, " ")) {
    let t3 = pe.exec(e3);
    if (t3 === null) return b("translate(), rotate(), scale() and skew() only");
    let n2 = O(t3[2], ","), r2 = t3[1];
    if (!(r2.startsWith("translate") ? n2.length >= 1 && n2.length <= (r2 === "translate" ? 2 : 1) && n2.every((e4) => C(e4) !== void 0 || T(e4) !== void 0) : r2 === "rotate" || r2.startsWith("skew") ? n2.length >= 1 && n2.length <= (r2 === "skew" ? 2 : 1) && n2.every(oe) : n2.length === 1 && x(n2[0]) !== void 0 && Number(n2[0]) >= 0.1 && Number(n2[0]) <= 4)) return b(`${r2}() with ${r2.startsWith("translate") ? "px or % offsets" : r2 === "scale" ? "one factor" : "an angle"}`);
  }
  return y(t2.replace(/\s+/g, " "));
}
var he = /^(blur|brightness|contrast|saturate|grayscale|sepia|invert|hue-rotate|opacity)\(([^()]*)\)$/;
function ge(e2) {
  let t2 = e2.trim();
  return t2 === "none" ? y("none") : O(t2, " ").every((e3) => he.test(e3)) ? y(t2.replace(/\s+/g, " ")) : b("blur(), brightness(), contrast(), saturate(), grayscale(), sepia(), invert(), hue-rotate() and opacity()");
}
function _e(e2) {
  let t2 = O(e2, ",");
  return t2.length === 0 || t2.some((e3) => !/^(["'])[^"';{}<>]+\1$|^[A-Za-z][\w -]*$/.test(e3)) ? b("font names, quoted when they have spaces, then a generic family") : y(t2.join(", "));
}
function ve(e2) {
  let t2 = e2.trim().toLowerCase();
  if (t2 === "normal") return y("400");
  if (t2 === "bold") return y("700");
  let n2 = x(t2);
  return n2 !== void 0 && n2 >= 100 && n2 <= 900 && n2 % 100 == 0 ? y(String(n2)) : b("100 to 900 in hundreds, normal or bold");
}
function ye(e2) {
  let t2 = e2.trim(), n2 = x(t2);
  if (n2 !== void 0) return n2 >= 0.5 && n2 <= 4 ? y(S(n2)) : b("a factor from 0.5 to 4");
  let r2 = T(t2);
  return r2 === void 0 ? w(t2, 4, 1600) : r2 >= 50 && r2 <= 400 ? y(S(r2 / 100)) : b("a factor from 0.5 to 4");
}
function be(e2) {
  let t2 = e2.trim().toLowerCase();
  if (t2 === "normal") return y("normal");
  let n2 = /^(-?(?:\d+\.?\d*|\.\d+))em$/.exec(t2);
  return n2 === null ? w(t2, -24, 32) : y(`${S(Number(n2[1]))}em`);
}
function xe(e2) {
  let t2 = /^span\s+(\d+)$/.exec(e2.trim());
  return t2 !== null && Number(t2[1]) >= 1 && Number(t2[1]) <= 24 ? y(`span ${Number(t2[1])}`) : b("`span N`: grid children fill in order");
}
function Se(e2) {
  let t2 = e2.trim().replace(/\s+/g, " "), n2 = O(t2.replace(/repeat\(\s*(\d+)\s*,\s*([^()]+)\)/g, (e3, t3, n3) => Array.from({ length: Math.min(Number(t3), 25) }, () => n3.trim()).join(" ")), " ");
  return n2.length === 0 || n2.length > 24 ? b("1 to 24 tracks") : n2.every((e3) => e3 === "auto" || /^\d+(\.\d+)?fr$/.test(e3) || C(e3) !== void 0 || T(e3) !== void 0) ? y(t2) : b("tracks in px, %, fr or auto \u2014 no minmax(), auto-fill or names");
}
function Ce(e2) {
  let t2 = e2.trim().toLowerCase();
  if (["none", "auto"].includes(t2)) return y(t2);
  let n2 = O(t2, " "), r2 = (e3) => e3 === "auto" || e3 === "content" || C(e3) !== void 0 || T(e3) !== void 0;
  return n2.length >= 1 && n2.length <= 3 && x(n2[0]) !== void 0 && (n2.length < 2 || x(n2[1]) !== void 0 || n2.length === 2 && r2(n2[1])) && (n2.length < 3 || r2(n2[2])) ? y(t2) : b("none, auto, or grow [shrink] [basis]");
}
function we(e2) {
  let t2 = e2.trim();
  return /^\d+(\.\d+)?(\s*\/\s*\d+(\.\d+)?)?$/.test(t2) ? y(t2.replace(/\s*\/\s*/, " / ")) : b("N or N / N");
}
function Te(e2) {
  let t2 = e2.trim(), n2 = /^calc\(\s*(-?[\d.]+)%\s*([+-])\s*([\d.]+)px\s*\)$/.exec(t2);
  return n2 === null ? E(t2, ["auto"]) : y(`calc(${S(Number(n2[1]))}% ${n2[2]} ${S(Number(n2[3]))}px)`);
}
function Ee(e2) {
  let t2 = O(e2.trim().toLowerCase(), " "), n2 = [
    "none",
    "underline",
    "line-through"
  ], r2 = [
    "solid",
    "double",
    "dotted",
    "dashed",
    "wavy"
  ];
  return t2.length >= 1 && n2.includes(t2[0]) && t2.slice(1).every((e3) => r2.includes(e3) || k(e3)) ? y(t2.join(" ")) : b("none, underline or line-through, then a style and a colour");
}
function De(e2) {
  let t2 = O(e2.trim(), " "), n2 = t2[0] === void 0 ? void 0 : C(t2[0]);
  return t2.length === 2 && n2 !== void 0 && n2 >= 0 && n2 <= 8 && k(t2[1]) ? y(`${te(n2)} ${t2[1].toLowerCase()}`) : b("a width up to 8px and a colour");
}
function Oe(e2) {
  let t2 = e2.trim().toLowerCase();
  return t2 === "transparent" || t2 === "currentcolor" ? y(t2) : b("transparent, with background-clip:text");
}
var j = [
  "start",
  "center",
  "end",
  "stretch",
  "baseline",
  "flex-start",
  "flex-end"
];
var ke = {
  position: {
    targets: h,
    read: D(["absolute", "relative"]),
    takes: "absolute | relative"
  },
  left: {
    targets: h,
    read: Te,
    takes: "px, %, calc(% \xB1 px) or auto"
  },
  top: {
    targets: h,
    read: Te,
    takes: "px, %, calc(% \xB1 px) or auto"
  },
  right: {
    targets: h,
    read: (e2) => E(e2, ["auto"]),
    takes: "px, % or auto"
  },
  bottom: {
    targets: h,
    read: (e2) => E(e2, ["auto"]),
    takes: "px, % or auto"
  },
  width: {
    targets: [...m, "section"],
    read: (e2) => E(e2, ["auto"]),
    takes: "px, % or auto"
  },
  height: {
    targets: [...m, "section"],
    read: (e2) => E(e2, ["auto"]),
    takes: "px, % or auto"
  },
  "min-width": {
    targets: m,
    read: (e2) => E(e2, ["min-content", "max-content"]),
    takes: "px, min-content or max-content"
  },
  "min-height": {
    targets: m,
    read: (e2) => w(e2, 0),
    takes: "px"
  },
  "max-width": {
    targets: m,
    read: (e2) => w(e2, 0),
    takes: "px"
  },
  "max-height": {
    targets: m,
    read: (e2) => w(e2, 0),
    takes: "px"
  },
  display: {
    targets: g,
    read: D([
      "flex",
      "grid",
      "none"
    ]),
    takes: "flex | grid | none"
  },
  "flex-direction": {
    targets: g,
    read: D([
      "row",
      "column",
      "row-reverse",
      "column-reverse"
    ]),
    takes: "row | column [-reverse]"
  },
  "flex-wrap": {
    targets: g,
    read: D(["wrap", "nowrap"]),
    takes: "wrap | nowrap"
  },
  gap: {
    targets: g,
    read: (e2) => w(e2, 0, 512),
    takes: "one length from 0 to 512px"
  },
  "align-items": {
    targets: g,
    read: D(j),
    takes: j.join(" | ")
  },
  "justify-content": {
    targets: g,
    read: D([
      "start",
      "center",
      "end",
      "space-between",
      "space-around",
      "space-evenly",
      "flex-start",
      "flex-end"
    ]),
    takes: "start | center | end | space-between | space-around | space-evenly"
  },
  "justify-items": {
    targets: g,
    read: D([
      "start",
      "center",
      "end",
      "stretch"
    ]),
    takes: "start | center | end | stretch"
  },
  "align-self": {
    targets: m,
    read: D([...j, "auto"]),
    takes: `${j.join(" | ")} | auto`
  },
  "justify-self": {
    targets: m,
    read: D([
      "start",
      "center",
      "end",
      "stretch",
      "auto"
    ]),
    takes: "start | center | end | stretch | auto"
  },
  flex: {
    targets: m,
    read: Ce,
    takes: "none, auto, or grow [shrink] [basis]"
  },
  "flex-grow": {
    targets: m,
    read: ne(0, 100),
    takes: "a number"
  },
  "flex-shrink": {
    targets: m,
    read: ne(0, 100),
    takes: "a number"
  },
  "flex-basis": {
    targets: m,
    read: (e2) => E(e2, ["auto"]),
    takes: "px or auto"
  },
  "grid-template-columns": {
    targets: g,
    read: Se,
    takes: "tracks in px, %, fr or auto"
  },
  "grid-template-rows": {
    targets: g,
    read: Se,
    takes: "tracks in px, %, fr or auto"
  },
  "grid-column": {
    targets: m,
    read: xe,
    takes: "span N"
  },
  "grid-row": {
    targets: m,
    read: xe,
    takes: "span N"
  },
  "aspect-ratio": {
    targets: m,
    read: we,
    takes: "N or N / N"
  },
  padding: {
    targets: [..._, "inline"],
    read: de(0, 256),
    takes: "one to four lengths from 0 to 256px"
  },
  overflow: {
    targets: ["div", "section"],
    read: D(["hidden", "visible"]),
    takes: "hidden | visible"
  },
  "font-family": {
    targets: [..._, "inline"],
    read: _e,
    takes: "font names, then a generic family"
  },
  "font-size": {
    targets: [..._, "inline"],
    read: (e2) => w(e2, 8, 400),
    takes: "a size from 8 to 400px"
  },
  "font-weight": {
    targets: [..._, "inline"],
    read: ve,
    takes: "100 to 900, normal or bold"
  },
  "font-style": {
    targets: [..._, "inline"],
    read: D(["normal", "italic"]),
    takes: "normal | italic"
  },
  "line-height": {
    targets: _,
    read: ye,
    takes: "a factor from 0.5 to 4, or px"
  },
  "letter-spacing": {
    targets: [..._, "inline"],
    read: be,
    takes: "px, em or normal"
  },
  "text-align": {
    targets: _,
    read: D([
      "left",
      "center",
      "right",
      "justify",
      "start",
      "end"
    ]),
    takes: "left | center | right | justify"
  },
  "text-transform": {
    targets: [..._, "inline"],
    read: D([
      "none",
      "uppercase",
      "lowercase",
      "capitalize"
    ]),
    takes: "none | uppercase | lowercase | capitalize"
  },
  "white-space": {
    targets: _,
    read: D(["normal", "nowrap"]),
    takes: "normal | nowrap"
  },
  "text-decoration": {
    targets: [..._, "inline"],
    read: Ee,
    takes: "none | underline | line-through [style] [colour]"
  },
  "font-variant-numeric": {
    targets: [..._, "inline"],
    read: D(["normal", "tabular-nums"]),
    takes: "normal | tabular-nums"
  },
  "-webkit-text-stroke": {
    targets: ["text"],
    read: De,
    takes: "a width and a colour"
  },
  "-webkit-text-fill-color": {
    targets: ["text", "inline"],
    read: Oe,
    takes: "transparent"
  },
  "background-clip": {
    targets: ["text"],
    read: D(["text", "border-box"]),
    takes: "text"
  },
  color: {
    targets: [
      ..._,
      "inline",
      "icon",
      "connector",
      "hr"
    ],
    read: ae,
    takes: "a colour"
  },
  background: {
    targets: [
      ...v,
      "row",
      "shape",
      "hr",
      "inline"
    ],
    read: le,
    takes: "a colour or one gradient"
  },
  border: {
    targets: [
      ...v,
      "shape",
      "hr",
      "connector"
    ],
    read: A,
    takes: "`2px solid #ccc`"
  },
  "border-top": {
    targets: [...v, "hr"],
    read: A,
    takes: "`2px solid #ccc`"
  },
  "border-right": {
    targets: v,
    read: A,
    takes: "`2px solid #ccc`"
  },
  "border-bottom": {
    targets: v,
    read: A,
    takes: "`2px solid #ccc`"
  },
  "border-left": {
    targets: v,
    read: A,
    takes: "`2px solid #ccc`"
  },
  "border-radius": {
    targets: [
      ...v,
      "shape",
      "inline"
    ],
    read: de(0, 2048, true),
    takes: "one to four lengths, or 50%"
  },
  "box-shadow": {
    targets: [...v, "shape"],
    read: fe(true),
    takes: "x y [blur [spread]] colour, up to eight"
  },
  "text-shadow": {
    targets: [..._, "inline"],
    read: fe(false),
    takes: "x y [blur] colour, up to eight"
  },
  opacity: {
    targets: p,
    read: ne(0, 1),
    takes: "0 to 1"
  },
  transform: {
    targets: [...h, "section"],
    read: me,
    takes: "translate(), rotate(), scale(), skew()"
  },
  filter: {
    targets: [
      "div",
      "text",
      "img",
      "shape",
      "svg"
    ],
    read: ge,
    takes: "blur(), brightness(), \u2026 \u2014 no url()"
  },
  "backdrop-filter": {
    targets: ["div", "text"],
    read: ge,
    takes: "blur(), brightness(), \u2026 \u2014 no url()"
  },
  "mix-blend-mode": {
    targets: [
      "div",
      "text",
      "img",
      "shape",
      "svg"
    ],
    read: D([
      "normal",
      "multiply",
      "screen",
      "overlay",
      "darken",
      "lighten"
    ]),
    takes: "normal | multiply | screen | overlay | darken | lighten"
  },
  "object-fit": {
    targets: ["img"],
    read: D([
      "cover",
      "contain",
      "fill"
    ]),
    takes: "cover | contain"
  },
  "object-position": {
    targets: ["img"],
    read: (e2) => O(e2, " ").every((e3) => T(e3) !== void 0 || [
      "center",
      "top",
      "bottom",
      "left",
      "right"
    ].includes(e3)) ? y(e2.trim()) : b("X% Y%"),
    takes: "X% Y%"
  }
};
var Ae = {
  "background-color": "background",
  "background-image": "background",
  "grid-gap": "gap",
  "row-gap": "gap",
  "column-gap": "gap",
  "text-fill-color": "-webkit-text-fill-color",
  "-webkit-background-clip": "background-clip"
};
var je = /* @__PURE__ */ new Set([
  "box-sizing",
  "-webkit-font-smoothing",
  "-moz-osx-font-smoothing",
  "font-feature-settings",
  "text-rendering",
  "cursor",
  "user-select",
  "pointer-events",
  "list-style",
  "list-style-type"
]);
var Me = {
  margin: "space boxes with the parent's gap and padding",
  "margin-top": "space boxes with the parent's gap and padding",
  "margin-bottom": "space boxes with the parent's gap and padding",
  "margin-left": "space boxes with the parent's gap and padding",
  "margin-right": "space boxes with the parent's gap and padding",
  "z-index": "later elements paint over earlier ones: order them instead",
  float: "use a flex row",
  "border-color": "write the whole stroke: `border:2px solid #ccc`",
  "border-width": "write the whole stroke: `border:2px solid #ccc`",
  "border-style": "write the whole stroke: `border:2px solid #ccc`",
  animation: "use data-build-in on a pinned element",
  transition: "use data-transition on the slide",
  "vertical-align": "align with a flex container's align-items",
  "word-break": "size the box to its longest word",
  "text-wrap": "size the box to its text"
};
function Ne(e2, t2) {
  let n2 = f(e2), r2 = [];
  for (let i2 of Ie(t2)) {
    let t3 = i2.indexOf(":");
    if (t3 === -1) {
      r2.push({
        property: i2.trim(),
        dropped: "is not a declaration: write `property:value`"
      });
      continue;
    }
    let a2 = i2.slice(0, t3).trim().toLowerCase(), o2 = i2.slice(t3 + 1).trim();
    /!important$/i.test(o2) && (o2 = o2.replace(/\s*!important$/i, "")), a2 !== "" && (a2 === "font" ? r2.push(...Fe(e2, o2)) : r2.push(Pe(n2, e2, Ae[a2] ?? a2, o2)));
  }
  return r2;
}
function Pe(t2, n2, r2, i2) {
  if (je.has(r2) || r2.startsWith("margin") && /^0(px)?(\s+0(px)?)*$/.test(i2)) return {
    property: r2,
    dropped: "",
    silent: true
  };
  let a2 = ke[r2];
  if (a2 === void 0) {
    let e2 = Me[r2];
    return {
      property: r2,
      dropped: `is not in the slide subset${e2 === void 0 ? "" : `: ${e2}`}`
    };
  }
  if (t2 === void 0 || !a2.targets.includes(t2)) return {
    property: r2,
    dropped: `does not apply to <${n2}>`
  };
  if (/var\(|url\(|expression\(|\\/i.test(u(i2))) return {
    property: r2,
    dropped: `${JSON.stringify(i2)}: no url(), expressions or escapes, and no var() but a theme colour (var(--${e.join("), var(--")}))`
  };
  let o2 = a2.read(i2);
  return "refused" in o2 ? {
    property: r2,
    dropped: `${JSON.stringify(i2)} is not ${o2.refused}`
  } : {
    property: r2,
    value: o2.value
  };
}
function Fe(e2, t2) {
  let n2 = f(e2), r2 = /^((?:(?:italic|normal|bold|[1-9]00)\s+)*)([\d.]+(?:px|pt)?)(?:\s*\/\s*([\d.]+(?:px|%)?))?\s+(.+)$/i.exec(t2.trim());
  if (r2 === null) return [{
    property: "font",
    dropped: `${JSON.stringify(t2)} is not [italic] [weight] size[/line-height] family`
  }];
  let i2 = r2[1].trim().split(/\s+/).filter(Boolean);
  return [
    ...i2.includes("italic") ? [["font-style", "italic"]] : [],
    ...i2.filter((e3) => e3 !== "italic" && e3 !== "normal").map((e3) => ["font-weight", e3]),
    ["font-size", r2[2]],
    ...r2[3] === void 0 ? [] : [["line-height", r2[3]]],
    ["font-family", r2[4]]
  ].map(([t3, r3]) => Pe(n2, e2, t3, r3));
}
function Ie(e2) {
  let t2 = [], n2 = 0, r2, i2 = false, a2 = "";
  for (let o2 of e2) if (r2 !== void 0) a2 += o2, i2 ? i2 = false : o2 === "\\" ? i2 = true : o2 === r2 && (r2 = void 0);
  else {
    if (o2 === '"' || o2 === "'") r2 = o2;
    else if (o2 === "(") n2 += 1;
    else if (o2 === ")") --n2;
    else if (o2 === ";" && n2 === 0) {
      t2.push(a2), a2 = "";
      continue;
    }
    a2 += o2;
  }
  return t2.push(a2), t2.filter((e3) => e3.trim() !== "");
}
function Le(e2) {
  return Object.entries(e2).map(([e3, t2]) => `${e3}:${t2}`).join(";");
}
function Re(e2) {
  return e2 in ke;
}
function ze(e2, t2) {
  let n2 = f(e2);
  return n2 !== void 0 && ke[t2]?.targets.includes(n2) === true;
}
function Be(e2, t2, n2) {
  let r2 = Pe(f(e2), e2, t2, n2);
  return "value" in r2 ? r2.value : void 0;
}
var Ve = /* @__PURE__ */ new Set([
  "svg",
  "style",
  "script",
  "aside"
]);
var He = {
  amp: "&",
  lt: "<",
  gt: ">",
  quot: '"',
  apos: "'",
  nbsp: "\xA0",
  ensp: "\u2002",
  emsp: "\u2003",
  thinsp: "\u2009",
  mdash: "\u2014",
  ndash: "\u2013",
  hellip: "\u2026",
  middot: "\xB7",
  bull: "\u2022",
  copy: "\xA9",
  reg: "\xAE",
  trade: "\u2122",
  times: "\xD7",
  divide: "\xF7",
  minus: "\u2212",
  plusmn: "\xB1",
  deg: "\xB0",
  laquo: "\xAB",
  raquo: "\xBB",
  lsquo: "\u2018",
  rsquo: "\u2019",
  ldquo: "\u201C",
  rdquo: "\u201D",
  rarr: "\u2192",
  larr: "\u2190",
  uarr: "\u2191",
  darr: "\u2193",
  harr: "\u2194",
  rArr: "\u21D2",
  le: "\u2264",
  ge: "\u2265",
  ne: "\u2260",
  asymp: "\u2248",
  infin: "\u221E",
  check: "\u2713",
  cross: "\u2717",
  star: "\u2606",
  hearts: "\u2665",
  euro: "\u20AC",
  pound: "\xA3",
  yen: "\xA5",
  cent: "\xA2",
  sect: "\xA7",
  para: "\xB6",
  dagger: "\u2020",
  frac12: "\xBD",
  frac14: "\xBC",
  frac34: "\xBE",
  sup2: "\xB2",
  sup3: "\xB3",
  micro: "\xB5",
  alpha: "\u03B1",
  beta: "\u03B2",
  gamma: "\u03B3",
  delta: "\u03B4",
  Delta: "\u0394",
  epsilon: "\u03B5",
  theta: "\u03B8",
  lambda: "\u03BB",
  mu: "\u03BC",
  pi: "\u03C0",
  sigma: "\u03C3",
  Sigma: "\u03A3",
  omega: "\u03C9",
  Omega: "\u03A9"
};
function M(e2) {
  return e2.replace(/&(#x[0-9a-f]+|#\d+|[a-z][a-z0-9]*);/gi, (e3, t2) => {
    if (t2[0] === "#") {
      let n2 = t2[1] === "x" || t2[1] === "X" ? parseInt(t2.slice(2), 16) : parseInt(t2.slice(1), 10);
      return Number.isFinite(n2) && n2 > 0 && n2 <= 1114111 ? String.fromCodePoint(n2) : e3;
    }
    return He[t2] ?? e3;
  });
}
function N(e2) {
  return e2.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
function P(e2) {
  return e2.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;");
}
function Ue(e2) {
  let t2 = [], n2 = [0];
  for (let t3 = 0; t3 < e2.length; t3 += 1) e2.charCodeAt(t3) === 10 && n2.push(t3 + 1);
  let r2 = (e3) => {
    let t3 = 0, r3 = n2.length - 1;
    for (; t3 < r3; ) {
      let i3 = t3 + r3 + 1 >> 1;
      n2[i3] <= e3 ? t3 = i3 : r3 = i3 - 1;
    }
    return {
      line: t3 + 1,
      column: e3 - n2[t3] + 1
    };
  }, i2 = 0, a2 = 0, o2 = (n3) => {
    n3 > a2 && t2.push({
      type: "text",
      text: M(e2.slice(a2, n3)),
      ...r2(a2)
    });
  };
  for (; i2 < e2.length; ) {
    let n3 = e2.indexOf("<", i2);
    if (n3 === -1) break;
    if (e2.startsWith("<!--", n3)) {
      o2(n3);
      let t3 = e2.indexOf("-->", n3 + 4);
      i2 = t3 === -1 ? e2.length : t3 + 3, a2 = i2;
      continue;
    }
    if (e2.startsWith("<!", n3) || e2.startsWith("<?", n3)) {
      o2(n3);
      let t3 = e2.indexOf(">", n3);
      i2 = t3 === -1 ? e2.length : t3 + 1, a2 = i2;
      continue;
    }
    let s2 = /^<\/([a-zA-Z][\w-]*)\s*>/.exec(e2.slice(n3, n3 + 80));
    if (s2 !== null) {
      o2(n3), t2.push({
        type: "end",
        name: s2[1].toLowerCase(),
        ...r2(n3)
      }), i2 = n3 + s2[0].length, a2 = i2;
      continue;
    }
    let c2 = Ge(e2, n3);
    if (c2 === void 0) i2 = n3 + 1;
    else {
      if (o2(n3), Ve.has(c2.name) && !c2.selfClosing) {
        let { inner: a3, after: o3, closed: s3 } = Ke(e2, c2.name, c2.end);
        t2.push({
          type: "raw",
          name: c2.name,
          attributes: c2.attributes,
          inner: a3,
          closed: s3,
          ...r2(n3)
        }), i2 = o3;
      } else t2.push({
        type: "start",
        name: c2.name,
        attributes: c2.attributes,
        selfClosing: c2.selfClosing,
        ...r2(n3)
      }), i2 = c2.end;
      a2 = i2;
    }
  }
  return o2(e2.length), t2;
}
var We = /([^\s"'>/=]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'=<>`]+)))?/y;
function Ge(e2, t2) {
  let n2 = /^<([a-zA-Z][\w-]*)/.exec(e2.slice(t2, t2 + 64));
  if (n2 === null) return;
  let r2 = [], i2 = t2 + n2[0].length, a2 = n2[1].toLowerCase() === "svg";
  for (; i2 < e2.length; ) {
    let t3 = /^\s*/.exec(e2.slice(i2, i2 + 256));
    if (i2 += t3[0].length, e2.startsWith("/>", i2)) return {
      name: n2[1].toLowerCase(),
      attributes: r2,
      selfClosing: true,
      end: i2 + 2
    };
    if (e2[i2] === ">") return {
      name: n2[1].toLowerCase(),
      attributes: r2,
      selfClosing: false,
      end: i2 + 1
    };
    We.lastIndex = i2;
    let o2 = We.exec(e2);
    if (o2 === null) {
      if (e2[i2] === "/") {
        i2 += 1;
        continue;
      }
      return;
    }
    r2.push({
      name: a2 ? o2[1] : o2[1].toLowerCase(),
      value: M(o2[2] ?? o2[3] ?? o2[4] ?? "")
    }), i2 += o2[0].length;
  }
}
function Ke(e2, t2, n2) {
  let r2 = RegExp(`<(/?)(${t2}|section)\\b[^>]*?(/?)>`, "gi"), i2 = 1;
  r2.lastIndex = n2;
  for (let a2 = r2.exec(e2); a2 !== null; a2 = r2.exec(e2)) {
    if (a2[2].toLowerCase() !== t2) return {
      inner: e2.slice(n2, a2.index),
      after: a2.index,
      closed: false
    };
    if (a2[1] === "/" ? --i2 : a2[3] !== "/" && t2 === "svg" && (i2 += 1), i2 === 0) return {
      inner: e2.slice(n2, a2.index),
      after: a2.index + a2[0].length,
      closed: true
    };
  }
  return {
    inner: e2.slice(n2),
    after: e2.length,
    closed: false
  };
}
var F = {
  activity: '<path d="M2.5 11.5H5.82a1 1 0 00.93-.63L9.13 4.93a.37.37 0 01.69.02l4.36 13.1a.37.37 0 00.69.02l2.38-5.94a1 1 0 01.93-.63H21.5"/>',
  add: '<path d="M12 4.5v15M4.5 12h15"/>',
  analytics: '<path d="M3 20.5H21m-16.5 0v-5a1 1 0 011-1h1a1 1 0 011 1v5m3 0v-7a1 1 0 011-1h1a1 1 0 011 1v7m3 0v-4a1 1 0 011-1h1a1 1 0 011 1v4M6 8.5L12 5l6 2.5"/><path d="M6 8.5H6M12 5h0m6 2.5h0" stroke-width="2"/>',
  api: '<path d="M10 4.5H9A1.5 1.5 0 007.5 6v4a2 2 0 01-2 2 2 2 0 012 2v4A1.5 1.5 0 009 19.5h1m4-15h1A1.5 1.5 0 0116.5 6v4a2 2 0 002 2 2 2 0 00-2 2v4A1.5 1.5 0 0115 19.5H14"/>',
  application: '<path d="M5 3.5H9A1.5 1.5 0 0110.5 5V9A1.5 1.5 0 019 10.5H5A1.5 1.5 0 013.5 9V5A1.5 1.5 0 015 3.5zm10 0h4A1.5 1.5 0 0120.5 5V9A1.5 1.5 0 0119 10.5H15A1.5 1.5 0 0113.5 9V5A1.5 1.5 0 0115 3.5zM5 13.5H9A1.5 1.5 0 0110.5 15v4A1.5 1.5 0 019 20.5H5A1.5 1.5 0 013.5 19V15A1.5 1.5 0 015 13.5zm10 0h4A1.5 1.5 0 0120.5 15v4A1.5 1.5 0 0119 20.5H15A1.5 1.5 0 0113.5 19V15A1.5 1.5 0 0115 13.5z"/>',
  "arrow-down": '<path d="M12 4.3V18.64M5.4 13.1l6.25 6.25a.5.5 0 00.7 0L18.6 13.1"/>',
  "arrow-left": '<path d="M19.7 12H5.36M10.9 5.4L4.65 11.65a.5.5 0 000 .7L10.9 18.6"/>',
  "arrow-right": '<path d="M4.3 12H18.64M13.1 5.4l6.25 6.25a.5.5 0 010 .7L13.1 18.6"/>',
  "arrow-up": '<path d="M12 19.7V5.36M5.4 10.9l6.25-6.25a.5.5 0 01.7 0L18.6 10.9"/>',
  "arrow-up-right": '<path d="M5.3 18.7L17.75 6.25M9.15 5.5H18a.5.5 0 01.5.5v8.85"/>',
  badge: '<path d="M6 9A6 6 0 1018 9 6 6 0 106 9m3.46 5.44L7.75 21l2.5-1.25 1-4.8m3.29-.51L16.25 21l-2.5-1.25-1-4.8"/><path d="M9 9a3 3 0 106 0A3 3 0 109 9" stroke-width="1.05"/>',
  book: '<path d="M12 5.75c-2-1.5-5.25-2-9.25-2v14.5c4 0 7.25.5 9.25 2zm0 0c2-1.5 5.25-2 9.25-2v14.5c-4 0-7.25.5-9.25 2z"/>',
  bot: '<path d="M7.5 8.5h9a2 2 0 012 2v6a2 2 0 01-2 2h-9a2 2 0 01-2-2v-6a2 2 0 012-2zm4.5 0v-3m-2.5 7v2m5-2v2M3.5 12v3m17-3v3"/>',
  building: '<path d="M2.5 20.5h19m-15 0V6.5a2 2 0 012-2h7a2 2 0 012 2v14m-7 0V18A1.5 1.5 0 0112 16.5h0A1.5 1.5 0 0113.5 18v2.5"/><path d="M10 7.5h0m4 0h0m-4 3h0m4 0h0m-4 3h0m4 0h0" stroke-width="2"/>',
  calendar: '<path d="M5.75 4.75h12.5a2 2 0 012 2v12.5a2 2 0 01-2 2H5.75a2 2 0 01-2-2V6.75a2 2 0 012-2zm-2 5h16.5M7.5 2.75v4.5m9-4.5v4.5"/>',
  camera: '<path d="M4.5 7.5H7.17a2 2 0 001.42-.59l.82-.82a2 2 0 011.42-.59h2.34a2 2 0 011.42.59l.82.82a2 2 0 001.42.59H19.5a2 2 0 012 2v8a2 2 0 01-2 2H4.5a2 2 0 01-2-2v-8a2 2 0 012-2zm4 5.75a3.5 3.5 0 107 0 3.5 3.5 0 10-7 0"/>',
  "chart-bar": '<path d="M3.5 3.5v16a1 1 0 001 1h16m-12-4V12m4 4.5v-9m4 9v-6"/>',
  "chart-line": '<path d="M3.5 3.5v16a1 1 0 001 1h16M7 15l2.79-2.79a1 1 0 011.42 0l2.08 2.08a1 1 0 001.42 0L19 10"/>',
  "chart-pie": '<path d="M3.5 12a8.5 8.5 0 1017 0 8.5 8.5 0 10-17 0M12 3.5V12h8.5"/>',
  chat: '<path d="M6 16.25H4.38A1.63 1.63 0 012.75 14.63V5.75a2 2 0 012-2h14.5a2 2 0 012 2v8.5a2 2 0 01-2 2H10.83a2 2 0 00-1.42.59L6 20.25"/>',
  checkmark: '<path d="M4.8 12l4.8 4.8 9.6-9.6"/>',
  "checkmark-outline": '<path d="M3 12a9 9 0 1018 0A9 9 0 103 12"/><path d="M7.8 12l2.8 2.8 5.6-5.6" stroke-width="1.2"/>',
  chip: '<path d="M7 5.5H17A1.5 1.5 0 0118.5 7V17A1.5 1.5 0 0117 18.5H7A1.5 1.5 0 015.5 17V7A1.5 1.5 0 017 5.5zm3.25 4h3.5a.75.75 0 01.75.75v3.5a.75.75 0 01-.75.75h-3.5a.75.75 0 01-.75-.75v-3.5a.75.75 0 01.75-.75zm-.75-7v3m5-3v3m-5 13v3m5-3v3m-12-12h3m-3 5h3m13-5h3m-3 5h3"/>',
  close: '<path d="M6 6L18 18M18 6L6 18"/>',
  cloud: '<path d="M5.03 18.5A2.55 2.55 0 013.91 13.67q1.26-.26 1.13-1.55a4.08 4.08 0 015.02-3.73q1.2.5 2.17-.35a4.58 4.58 0 017.04 3.23q-.02 1.3 1.1 1.95a3.07 3.07 0 01-2.08 5.33z"/>',
  code: '<path d="M8.4 7.2L3.95 11.65a.5.5 0 000 .7L8.4 16.8m7.2-9.6l4.45 4.45a.5.5 0 010 .7L15.6 16.8M13.61 6L10.39 18"/>',
  cube: '<path d="M12.5 3.29l7 4.04a1 1 0 01.5.87v7.6a1 1 0 01-.5.87l-7 4.04a1 1 0 01-1 0l-7-4.04A1 1 0 014 15.8V8.2a1 1 0 01.5-.87l7-4.04a1 1 0 011 0zM4.75 8.05L12 12.24l7.25-4.19M12 12.24V21"/>',
  "currency-dollar": '<path d="M16.38 8.25A4.38 3.75 0 1012 12 4.38 3.75 0 117.63 15.75M12 2.5v19"/>',
  dashboard: '<path d="M6.31 18.87a8.05 8.05 0 1111.38 0M12 13.18l3.66-3.66"/>',
  "data-base": '<path d="M4.5 6a7.5 2.75 0 0115 0A7.5 2.75 0 014.5 6m0 0V18a7.5 2.75 0 0015 0V6m-15 6a7.5 2.75 0 0015 0"/>',
  "delivery-truck": '<path d="M2.5 15.99V7A1.5 1.5 0 014 5.5h9A1.5 1.5 0 0114.5 7v6.82m0-4.32h3.25a1.5 1.5 0 011.2.6l2.25 3a1.5 1.5 0 01.3.9v.94M4.75 17.5a2.25 2.25 0 104.5 0 2.25 2.25 0 10-4.5 0m10.5 0a2.25 2.25 0 104.5 0 2.25 2.25 0 10-4.5 0"/>',
  document: '<path d="M6.75 2.75h7.54a.5.5 0 01.36.15L19.1 7.35a.5.5 0 01.15.36V19.25a2 2 0 01-2 2H6.75a2 2 0 01-2-2V4.75a2 2 0 012-2zm7.75 0V7.5h4.75M8.5 10.5h7m-7 4h7m-7 4h4"/>',
  earth: '<path d="M3 12a9 9 0 1018 0A9 9 0 103 12m9-9a4.5 9 0 010 18A4.5 9 0 0112 3M3 12H21M4.52 7H19.48M4.52 17H19.48"/>',
  education: '<path d="M12.21 4.59L21.54 8.8a.23.23 0 010 .41l-9.33 4.2a.5.5 0 01-.41 0L2.46 9.21a.23.23 0 010-.41L11.8 4.59a.5.5 0 01.41 0zM6.5 11.03V15.5c0 2 2.5 3 5.5 3 3 0 5.5-1 5.5-3V11.03m2-.9V17.5"/><path d="M19.5 17.5h0" stroke-width="2"/>',
  email: '<path d="M4.75 3.75h14.5a2 2 0 012 2v12.5a2 2 0 01-2 2H4.75a2 2 0 01-2-2V5.75a2 2 0 012-2zM2.75 6l8.5 4.91a1.5 1.5 0 001.5 0L21.25 6"/>',
  "face-satisfied": '<path d="M3 12a9 9 0 1018 0A9 9 0 103 12m5.5 2.25a4 4 0 007 0"/><path d="M9 9.75H9m6 0h0" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>',
  favorite: '<path d="M12 20C9 18 3 14.5 3 9.25 3 6.5 5 4.5 7.5 4.5c2 0 3.5 1 4.5 2.5 1-1.5 2.5-2.5 4.5-2.5 2.5 0 4.5 2 4.5 4.75C21 14.5 15 18 12 20z"/>',
  flag: '<path d="M5.5 21V3.5m0 0H18a.54.54 0 01.45.83L16.37 7.45a1 1 0 000 1.11l2.08 3.11A.54.54 0 0118 12.5H5.5"/>',
  flash: '<path d="M12.89 3.29L5.61 12.71A.49.49 0 006 13.5h4.5a.88.88 0 01.88.99l-.76 6.02a.27.27 0 00.49.2l7.28-9.42A.49.49 0 0018 10.5H13.5a.88.88 0 01-.88-.99l.76-6.02a.27.27 0 00-.49-.2z"/>',
  folder: '<path d="M4.75 3.75H8.17a2 2 0 011.42.59l1.82 1.82a2 2 0 001.42.59h6.42a2 2 0 012 2v9.5a2 2 0 01-2 2H4.75a2 2 0 01-2-2V5.75a2 2 0 012-2z"/>',
  gift: '<path d="M4.5 7.5h15A1.5 1.5 0 0121 9v1a1.5 1.5 0 01-1.5 1.5H4.5A1.5 1.5 0 013 10V9A1.5 1.5 0 014.5 7.5zm.5 4v7a2 2 0 002 2H17a2 2 0 002-2v-7m-7-4v13m0-13C10.5 4 6.5 3.5 7 6c.5 1.5 5 1.5 5 1.5m0 0c1.5-3.5 5.5-4 5-1.5-.5 1.5-5 1.5-5 1.5"/>',
  group: '<path d="M5.75 9a3.25 3.25 0 106.5 0A3.25 3.25 0 105.75 9M3 20a6 6 0 0112 0M15 5.6a3 3 0 111.5 5.65m.5 3a5.5 5.5 0 014 5.25"/>',
  growth: '<path d="M3 17l5.29-5.29a1 1 0 011.42 0l2.58 2.58a1 1 0 001.42 0l6.04-6.04m-3.5-.75H20a.5.5 0 01.5.5v3.75"/>',
  help: '<path d="M3 12a9 9 0 1018 0A9 9 0 103 12M9.5 9.5A2.5 2.5 0 1113 11.8c-.6.3-1 .8-1 1.5v.45"/><path d="M12 16.75h0" stroke-width="2"/>',
  home: '<path d="M2.5 20.5h19m-18-8l7.09-7.09a2 2 0 012.82 0L20.5 12.5m-14-3v11m11-11v11m-8 0v-5a2 2 0 012-2h1a2 2 0 012 2v5"/>',
  idea: '<path d="M8.42 14.62a6.25 6.25 0 117.16 0L15 17.5H9zM9.75 20.5h4.5"/>',
  image: '<path d="M5.5 3.5h13a2 2 0 012 2v13a2 2 0 01-2 2H5.5a2 2 0 01-2-2V5.5a2 2 0 012-2zm-2 13.36L8 12.35a.5.5 0 01.71 0l8.15 8.15"/><path d="M16.25 7.75h0" stroke-width="2"/>',
  industry: '<path d="M2.5 20.5h19m-16 0V10.15a2 2 0 011-1.73l5.57-3.21a.29.29 0 01.43.25V8.5a.29.29 0 00.43.25l6.14-3.54a.29.29 0 01.43.25V20.5m-9 0v-4a2 2 0 012-2h0a2 2 0 012 2v4"/>',
  information: '<path d="M3 12a9 9 0 1018 0A9 9 0 103 12m9-1v5.5"/><path d="M12 8h0" stroke-width="2"/>',
  laptop: '<path d="M7.5 5.5h9a2 2 0 012 2v6a2 2 0 01-2 2h-9a2 2 0 01-2-2v-6a2 2 0 012-2zm-5 13h19"/>',
  link: '<path d="M11.75 13.53a3 3 30 01-.5-.23h0a3 3 30 01-1.1-4.1l2-3.46a3 3 30 014.1-1.1h0 0a3 3 30 011.1 4.1l-.99 1.71m-4.11.02a3 3 30 01.5.23h0 0a3 3 30 011.1 4.1l-2 3.46a3 3 30 01-4.1 1.1h0a3 3 30 01-1.1-4.1l.99-1.71"/>',
  "list-checked": '<path d="M3.75 3.75h16.5m-16.5 6h16.5m-16.5 6H7.92"/><path d="M10.42 17l3.22 3.22 6.44-6.44" stroke-width="1.2"/>',
  location: '<path d="M12 21.25c0 0-7.25-6.07-7.25-11.25a7.25 7.25 0 0114.5 0c0 5.18-7.25 11.25-7.25 11.25zM9.5 10a2.5 2.5 0 105 0 2.5 2.5 0 10-5 0"/>',
  locked: '<path d="M8 11h8a2 2 0 012 2v4a2 2 0 01-2 2H8A2 2 0 016 17V13a2 2 0 012-2zm0 0V8.5a4 4 0 018 0V11m-4 3v2"/>',
  "machine-learning-model": '<path d="M1.75 8a1.75 1.75 0 103.5 0A1.75 1.75 0 101.75 8m0 8a1.75 1.75 0 103.5 0 1.75 1.75 0 10-3.5 0m8.5-11.75a1.75 1.75 0 103.5 0 1.75 1.75 0 10-3.5 0m0 7.75a1.75 1.75 0 103.5 0 1.75 1.75 0 10-3.5 0m0 7.75a1.75 1.75 0 103.5 0 1.75 1.75 0 10-3.5 0M18.75 8a1.75 1.75 0 103.5 0 1.75 1.75 0 10-3.5 0m0 8a1.75 1.75 0 103.5 0 1.75 1.75 0 10-3.5 0M5.1 7.29l5.3-2.33M5.08 8.75l5.34 2.5M4.53 9.42l6.44 8.91M4.53 14.58l6.44-8.91M5.08 15.25l5.34-2.5M5.1 16.71l5.3 2.33M13.6 4.96l5.3 2.33M13.03 5.67l6.44 8.91m-5.89-3.33l5.34-2.5m-5.34 4l5.34 2.5m-5.89 3.08l6.44-8.91M13.6 19.04l5.3-2.33"/>',
  map: '<path d="M4.12 5.74L9.08 3.68a1 1 0 01.83.03L14.09 5.8a1 1 0 00.83.02l4.66-1.93a.67.67 0 01.92.61V17.33a1 1 0 01-.61.93l-4.97 2.06a1 1 0 01-.83-.02L9.91 18.2a1 1 0 00-.83-.02L4.42 20.11A.67.67 0 013.5 19.5V6.67a1 1 0 01.62-.93zM9.5 3.5V18.1m5-12.2V20.5"/>',
  microphone: '<path d="M12 3h0a3 3 0 013 3v5a3 3 0 01-3 3h0A3 3 0 019 11V6a3 3 0 013-3zM6 11a6 6 0 0012 0m-6 6v3.5m-3.5 0h7"/>',
  mobile: '<path d="M8.5 2.5h7a2 2 0 012 2v15a2 2 0 01-2 2h-7a2 2 0 01-2-2V4.5a2 2 0 012-2zm2 16h3"/>',
  money: '<path d="M4.5 6.5h15a2 2 0 012 2v7a2 2 0 01-2 2H4.5a2 2 0 01-2-2v-7a2 2 0 012-2zM9.25 12a2.75 2.75 0 105.5 0 2.75 2.75 0 10-5.5 0"/><path d="M6 12H6m12 0h0" stroke-width="2"/>',
  moon: '<path d="M20.21 14.72A8.5 8.5 0 119.78 4.29q1.58-.27.76 1.11a6.5 6.5 0 008.56 8.56q1.38-.82 1.11.76z"/>',
  "network-3": '<path d="M4.63 9.92a1.7 3.5 0 012.74 0q.16.55.71.71a3.5 1.7 0 010 2.74q-.55.16-.71.71a1.7 3.5 0 01-2.74 0q-.16-.55-.71-.71a3.5 1.7 0 010-2.74q.55-.16.71-.71zm6.55.43l1.29 1.3a.5.5 0 010 .7l-1.29 1.3m5.45-3.73a1.7 3.5 0 012.74 0q.16.55.71.71a3.5 1.7 0 010 2.74q-.55.16-.71.71a1.7 3.5 0 01-2.74 0q-.16-.55-.71-.71a3.5 1.7 0 010-2.74q.55-.16.71-.71z"/>',
  password: '<path d="M3.75 16.5a3.75 3.75 0 107.5 0 3.75 3.75 0 10-7.5 0m6.4-2.65L20 4M17.5 6.5l2 2M15 9l1.5 1.5"/>',
  phone: '<path d="M6 3.5H9.5L11 8 8.75 9.5a11 11 0 005.75 5.75L16 13l4.5 1.5v4A1.5 1.5 0 0119 20 15.5 15.5 0 014.5 5 1.5 1.5 0 016 3.5z"/>',
  play: '<path d="M10.23 6l8.66 5a1.16 1.16 0 010 2l-8.66 5A1.16 1.16 0 018.5 17V7a1.16 1.16 0 011.73-1z"/>',
  "question-answering": '<path d="M14.5 6.5V5.13A1.38 1.38 0 0013.13 3.75H4.75a2 2 0 00-2 2V9.5a2 2 0 002 2H5.5a.83.83 0 01.59 1.41L4.5 14.5M19 17.25h1.13a1.13 1.13 0 001.12-1.12V10.5a2 2 0 00-2-2H11.5a2 2 0 00-2 2v4.75a2 2 0 002 2h3.67a2 2 0 011.42.59L19 20.25"/>',
  rain: '<path d="M6.1 15.5a2.16 2.16 0 01-.95-4.09q1.07-.22.96-1.31a3.45 3.45 0 014.25-3.15q1.01.42 1.84-.3a3.87 3.87 0 015.95 2.74q-.01 1.09.93 1.64a2.6 2.6 0 01-1.76 4.51zm1.9 2v3m4-3v3m4-3v3"/>',
  recycle: '<path d="M14.01 4.49a7.78 7.78 0 015.71 8.48m-2.44-1.7l1.92 2.36a.5.5 0 00.7.07l2.35-1.92M17.5 17.5a7.78 7.78 0 01-10.2.7m2.69-1.27l-3 .49a.5.5 0 00-.41.57l.49 3M4.49 14.01A7.78 7.78 0 018.98 4.83M8.73 7.79L9.81 4.95a.5.5 0 00-.29-.64L6.68 3.23"/>',
  rocket: '<path d="M18.72 5.28c.35 4.6-2.48 8.13-6.72 11.67L7.05 12c3.54-4.24 7.07-7.07 11.67-6.72zM12.88 8.64a1.75 1.75 45 102.48 2.48A1.75 1.75 45 1012.88 8.64m-3.47.77l-4.48.47L2.81 12H7.05m7.54 2.59l-.47 4.48L12 21.19V16.95M6.7 15.18L5.64 18.36 8.82 17.3"/>',
  search: '<path d="M4 10.5a6.5 6.5 0 1013 0 6.5 6.5 0 10-13 0m11.1 4.6l5.4 5.4"/>',
  security: '<path d="M3.75 4.25a23.44 23.44 0 0116.5 0V11c0 5.33-3.71 8.41-8.25 10.25C7.46 19.41 3.75 16.33 3.75 11z"/>',
  send: '<path d="M16.61 4.76L14.2 21.44a.35.35 30 01-.64.12l-3.27-5.6a1 1 30 00-.86-.5l-6.49-.03a.35.35 30 01-.22-.62L15.96 4.39a.4.4 30 01.65.37zm-.87.76L9.92 15.6"/>',
  settings: '<path d="M10.32 4.76l.14-.52a1 1 0 01.96-.74h1.16a1 1 0 01.97.74l.13.52a1 1 0 00.59.67l.77.32a1 1 0 00.89-.06l.46-.27a1 1 0 011.21.16l.82.82a1 1 0 01.16 1.21l-.27.46a1 1 0 00-.06.89l.32.77a1 1 0 00.67.59l.52.14a1 1 0 01.74.96v1.16a1 1 0 01-.74.97l-.52.13a1 1 0 00-.67.59l-.32.77a1 1 0 00.06.89l.27.46a1 1 0 01-.16 1.21l-.82.82a1 1 0 01-1.21.16l-.46-.27a1 1 0 00-.89-.06l-.77.32a1 1 0 00-.59.67l-.13.52a1 1 0 01-.97.74H11.42a1 1 0 01-.96-.74l-.14-.52a1 1 0 00-.59-.67l-.77-.32a1 1 0 00-.89.06l-.46.27A1 1 0 016.4 18.42l-.82-.82a1 1 0 01-.16-1.21l.27-.46a1 1 0 00.06-.89l-.32-.77a1 1 0 00-.67-.59l-.52-.13a1 1 0 01-.74-.97V11.42a1 1 0 01.74-.96l.52-.14a1 1 0 00.67-.59l.32-.77a1 1 0 00-.06-.89l-.27-.46A1 1 0 015.58 6.4l.82-.82a1 1 0 011.21-.16l.46.27a1 1 0 00.89.06l.77-.32a1 1 0 00.59-.67zM9 12a3 3 0 106 0A3 3 0 109 12"/>',
  "shopping-cart": '<path d="M2.5 3.5H3.78A1.5 1.5 0 015.25 4.69l2 9.62A1.5 1.5 0 008.72 15.5h8.61a1.5 1.5 0 001.45-1.14l1.36-5.4A1.17 1.17 0 0019 7.5H5.85m1.65 12a1.5 1.5 0 103 0 1.5 1.5 0 10-3 0m8 0a1.5 1.5 0 103 0 1.5 1.5 0 10-3 0"/>',
  star: '<path d="M13.22 6.83l.8 1.73a1.8 1.8 0 001.42 1.03l1.89.22a1.34 1.34 0 01.75 2.32l-1.4 1.29a1.8 1.8 0 00-.54 1.68l.37 1.86a1.34 1.34 0 01-1.97 1.43l-1.66-.93a1.8 1.8 0 00-1.76 0l-1.66.93A1.34 1.34 0 017.49 16.96l.37-1.86a1.8 1.8 0 00-.54-1.68l-1.4-1.29a1.34 1.34 0 01.75-2.32l1.89-.22A1.8 1.8 0 009.98 8.56l.8-1.73a1.34 1.34 0 012.44 0z"/>',
  store: '<path d="M2.5 20.5h19M3.85 9.15L6.91 6.09A2 2 0 018.33 5.5h7.34a2 2 0 011.42.59l3.06 3.06A.21.21 0 0120 9.5H4a.21.21 0 01-.15-.35zM10.5 5.5v4m3-4v4m-8 0v11m13-11v11m-11 0v-5a2 2 0 012-2h0a2 2 0 012 2v5m3.5-7h0A1.5 1.5 0 0116.5 15h0A1.5 1.5 0 0115 16.5h0A1.5 1.5 0 0113.5 15h0A1.5 1.5 0 0115 13.5z"/>',
  subtract: '<path d="M4.5 12h15"/>',
  sun: '<path d="M8 12a4 4 0 108 0A4 4 0 108 12m10.5 0H21m-4.4 4.6l1.76 1.76M12 18.5V21M7.4 16.6L5.64 18.36M5.5 12H3M7.4 7.4L5.64 5.64M12 5.5V3m4.6 4.4l1.76-1.76"/>',
  task: '<path d="M17 4.56A2 2 0 0118.5 6.5v12a2 2 0 01-2 2h-9a2 2 0 01-2-2V6.5A2 2 0 017 4.56M8.7 13.5l2.2 2.2 4.4-4.4M10.5 3.5h3a1 1 0 011 1v1a1 1 0 01-1 1h-3a1 1 0 01-1-1v-1a1 1 0 011-1z"/>',
  "thumbs-up": '<path d="M5 10.5H7a.5.5 0 01.5.5v9a.5.5 0 01-.5.5H5A1.5 1.5 0 013.5 19V12A1.5 1.5 0 015 10.5zm2.35.15L10.5 4c.5-1 3-1 3.5 1l-.5 5.5h5a1.72 1.72 0 011.7 1.98l-.94 6.32a2 2 0 01-1.98 1.7l-9.93-.15"/>',
  time: '<path d="M3.95 12a8.05 8.05 0 1016.1 0A8.05 8.05 0 103.95 12M12 7.4V12L8.55 15.45"/>',
  "tool-kit": '<path d="M5.5 8.5h13a2 2 0 012 2v7a2 2 0 01-2 2H5.5a2 2 0 01-2-2v-7a2 2 0 012-2zm3 0v-2a1 1 0 011-1h5a1 1 0 011 1v2m-12 4h7m3 0h7m-9.5-2h2a.5.5 0 01.5.5v3a.5.5 0 01-.5.5H11a.5.5 0 01-.5-.5V11a.5.5 0 01.5-.5z"/>',
  tools: '<path d="M11.4 7.86a4.5 4.5 45 016.43-3.81l-3 3 2.12 2.12 3-3a4.5 4.5 45 01-1.89 5.88m-7.83 4.19L8.11 18.36A1.75 1.75 45 015.64 15.89l2.61-2.61M5.99 5.99l5.3 5.3m-.17.18l.35-.35a1.5 1.5-45 012.12 0l4.6 4.59a1.5 1.5-45 010 2.12l-.36.36a1.5 1.5-45 01-2.12 0l-4.59-4.6a1.5 1.5-45 010-2.12z"/>',
  tree: '<path d="M9.5 16.5H7A4 4 0 015.5 9a6.6 6.6 0 0113 0A4 4 0 0117 16.5H14.5m-2.5 5l1-9M12 15L9.5 12.5m2.5 1l2-2"/>',
  trophy: '<path d="M7 3.5H17v6A5 5 0 017 9.5zm0 2H4.5C4.5 8 5.4 10 7.23 11M17 5.5h2.5c0 2.5-.9 4.5-2.73 5.5M12 14.5v3m-3 0h6a1 1 0 011 1v1a1 1 0 01-1 1H9a1 1 0 01-1-1v-1a1 1 0 011-1z"/>',
  user: '<path d="M8.25 8a3.75 3.75 0 107.5 0A3.75 3.75 0 108.25 8M5 20.5a7 6.5 0 0114 0"/>',
  video: '<path d="M5 6.5h8a2 2 0 012 2v7a2 2 0 01-2 2H5a2 2 0 01-2-2v-7a2 2 0 012-2zM15 10l5.13-2.96a.58.58 0 01.87.5v8.92a.58.58 0 01-.87.5L15 14"/>',
  wallet: '<path d="M5.5 5h13a2 2 0 012 2V17a2 2 0 01-2 2H5.5a2 2 0 01-2-2V7a2 2 0 012-2zm15 5H17a1.5 1.5 0 00-1.5 1.5v1A1.5 1.5 0 0017 14h3.5"/><path d="M18 12h0" stroke-width="2"/>',
  warning: '<path d="M3 12a9 9 0 1018 0A9 9 0 103 12m9-4.5v5"/><path d="M12 16h0" stroke-width="2"/>',
  "warning-alt": '<path d="M13 4.73l7.5 13.04a1.16 1.16 0 01-1 1.73H4.5a1.16 1.16 0 01-1-1.73L11 4.73a1.15 1.15 0 012 0zM12 9v4.5"/><path d="M12 16.5h0" stroke-width="2"/>'
};
var qe = {
  "checkmark-filled": "checkmark-outline",
  lightning: "flash",
  "star-filled": "star",
  "user-multiple": "group"
};
var Je = Object.keys(F);
function Ye(e2) {
  let t2 = Object.hasOwn(qe, e2) ? qe[e2] : e2;
  return Object.hasOwn(F, t2) ? F[t2] : void 0;
}
function Xe(e2) {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" role="img">${Ye(e2) ?? ""}</svg>`;
}
var Ze = 1920;
var Qe = 1080;
var I = 500;
var $e = 200;
var et = 53248;
var tt = [
  "div",
  "h1",
  "h2",
  "h3",
  "p",
  "ul",
  "ol",
  "img",
  "table",
  "hr",
  "x-shape",
  "x-icon",
  "x-connector"
];
var nt = [
  "b",
  "i",
  "u",
  "s",
  "a",
  "span",
  "br"
];
var L = [
  "fade",
  "push",
  "magic"
];
var rt = [
  "rect",
  "rounded",
  "ellipse",
  "diamond",
  "triangle",
  "arrow-right",
  "arrow-left",
  "arrow-up",
  "arrow-down",
  "line"
];
var it = /* @__PURE__ */ new Set([
  "br",
  "hr",
  "img",
  "meta",
  "link",
  "input",
  "wbr",
  "source",
  "col",
  "area",
  "base",
  "x-shape",
  "x-icon",
  "x-connector"
]);
var at = /* @__PURE__ */ new Set([
  "p",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "div",
  "ul",
  "ol",
  "table",
  "section",
  "hr",
  "blockquote",
  "figure",
  "header",
  "footer",
  "aside"
]);
var ot = 256;
function st(e2, t2) {
  let n2 = {
    kind: "element",
    name: "#root",
    attributes: [],
    children: [],
    line: 1,
    column: 1
  }, r2 = [n2], i2 = () => r2.at(-1), a2 = (e3, t3 = []) => {
    for (let n3 = r2.length - 1; n3 > 0; --n3) {
      let i3 = r2[n3].name;
      if (t3.includes(i3)) return;
      if (e3.includes(i3)) {
        r2.length = n3;
        return;
      }
    }
  };
  for (let n3 of Ue(e2)) switch (n3.type) {
    case "text":
      i2().children.push({
        kind: "text",
        text: n3.text,
        line: n3.line,
        column: n3.column
      });
      break;
    case "raw":
      i2().children.push({
        kind: "raw",
        name: n3.name,
        attributes: n3.attributes,
        inner: n3.inner,
        closed: n3.closed,
        line: n3.line,
        column: n3.column
      });
      break;
    case "start": {
      let e3 = n3.name;
      at.has(e3) && a2(["p"], [
        "div",
        "section",
        "td",
        "th",
        "li",
        "body"
      ]), e3 === "li" ? a2(["li"], ["ul", "ol"]) : e3 === "tr" ? a2(["tr"], [
        "table",
        "tbody",
        "thead",
        "tfoot"
      ]) : e3 === "td" || e3 === "th" ? a2(["td", "th"], ["tr", "table"]) : e3 === "section" && a2(["section"]);
      let o2 = {
        kind: "element",
        name: e3,
        attributes: n3.attributes,
        children: [],
        line: n3.line,
        column: n3.column
      };
      i2().children.push(o2), !it.has(e3) && !n3.selfClosing && (r2.length < ot ? r2.push(o2) : t2(o2));
      break;
    }
    case "end":
      if (it.has(n3.name)) break;
      a2([n3.name]);
  }
  return n2;
}
var ct = {
  strong: "b",
  em: "i",
  del: "s",
  strike: "s",
  ins: "u",
  h4: "h3",
  h5: "h3",
  h6: "h3",
  blockquote: "div",
  figure: "div",
  figcaption: "p",
  header: "div",
  footer: "div",
  main: "div",
  article: "div",
  nav: "div",
  center: "div",
  small: "span",
  mark: "span",
  sup: "span",
  sub: "span",
  code: "span",
  kbd: "span",
  label: "span",
  time: "span",
  abbr: "span",
  cite: "span",
  q: "span"
};
var lt = /* @__PURE__ */ new Set([
  "thead",
  "tbody",
  "tfoot",
  "colgroup",
  "picture"
]);
var ut = /* @__PURE__ */ new Set([
  "script",
  "noscript",
  "iframe",
  "object",
  "embed",
  "canvas",
  "video",
  "audio",
  "form",
  "input",
  "button",
  "select",
  "textarea",
  "template",
  "x-embed",
  "col",
  "source",
  "meta",
  "link",
  "style",
  "title",
  "head"
]);
var dt = /* @__PURE__ */ new Set([
  "h1",
  "h2",
  "h3",
  "p"
]);
var ft = /* @__PURE__ */ new Set([
  "b",
  "i",
  "u",
  "s",
  "a",
  "span"
]);
var pt = /* @__PURE__ */ new Set([
  "id",
  "data-build-in",
  "data-build-out"
]);
var mt = {
  a: ["href"],
  img: [
    "src",
    "alt",
    "data-crop"
  ],
  "x-shape": ["kind"],
  "x-icon": ["name"],
  "x-connector": [
    "x1",
    "y1",
    "x2",
    "y2",
    "head",
    "route",
    "from"
  ]
};
var ht = /^(class|role|title|lang|dir|tabindex|aria-.*|data-.*|width|height|loading|decoding|draggable|target|rel|xmlns.*)$/;
var gt = /^[A-Za-z0-9_-]{1,64}$/;
function R(e2, t2, n2, r2) {
  e2.diagnostics.push({
    severity: n2,
    line: t2.line,
    column: t2.column,
    ...e2.slide === void 0 ? {} : { slide: e2.slide },
    message: r2
  });
}
function _t(e2) {
  let t2 = {
    diagnostics: [],
    slide: void 0,
    elements: 0
  }, n2 = false, r2 = st(e2.replace(/\r\n?/g, "\n"), (e3) => {
    n2 || (n2 = true, R(t2, e3, "warning", `Elements nest more than ${ot} deep here; what is deeper is set beside its parent.`));
  }), a2 = B(r2, "html") ?? r2, o2 = B(a2, "head"), s2 = B(a2, "body") ?? a2, c2 = B(o2 ?? a2, "title"), l2 = [], u2 = [];
  for (let e3 of V(o2 ?? a2, (e4) => e4.kind === "element" && e4.name === "link")) {
    let n3 = z(e3, "href");
    z(e3, "rel") === "stylesheet" && n3 !== void 0 && (n3.startsWith("https://fonts.googleapis.com/") ? l2.push(n3) : R(t2, e3, "warning", `<link href="${n3}"> is dropped: a deck loads stylesheets only from Google Fonts.`));
  }
  for (let e3 of V(r2, (e4) => e4.kind === "raw" && e4.name === "style")) u2.push(...bt(t2, e3));
  let d2 = V(s2, (e3) => e3.kind === "element" && e3.name === "section", true);
  d2.length > I && R(t2, d2[I], "warning", `A deck holds at most ${I} slides; the rest are dropped.`);
  let f2 = /* @__PURE__ */ new Set(), p2 = d2.slice(0, I).map((e3, n3) => (t2.slide = n3 + 1, t2.elements = 0, Ct(t2, e3, n3, f2)));
  t2.slide = void 0;
  for (let e3 of vt(s2)) R(t2, e3, "warning", "Content outside a <section> is dropped: every slide is a <section>.");
  let m2 = z(s2, "data-theme")?.trim().toLowerCase();
  return m2 !== void 0 && !i(m2) && R(t2, s2, "warning", `data-theme="${m2}" is not a theme's id (lower case, digits and hyphens); the deck is drawn in the default theme.`), {
    deck: {
      title: c2 === void 0 ? "" : yt(c2).trim(),
      fontLinks: l2,
      fontFaces: u2,
      style: H(t2, "body", s2),
      ...m2 !== void 0 && i(m2) ? { theme: m2 } : {},
      slides: p2
    },
    diagnostics: t2.diagnostics
  };
}
function z(e2, t2) {
  return e2.attributes.find((e3) => e3.name === t2)?.value;
}
function B(e2, t2) {
  for (let n2 of e2.children) {
    if (n2.kind !== "element") continue;
    if (n2.name === t2) return n2;
    let e3 = B(n2, t2);
    if (e3 !== void 0) return e3;
  }
}
function V(e2, t2, n2 = false) {
  let r2 = [];
  for (let i2 of e2.children) t2(i2) && (r2.push(i2), n2) || i2.kind === "element" && r2.push(...V(i2, t2, n2));
  return r2;
}
function vt(e2) {
  return e2.children.flatMap((e3) => e3.kind === "text" ? e3.text.trim() === "" ? [] : [e3] : e3.kind === "raw" ? e3.name === "style" ? [] : [e3] : e3.name === "section" || e3.name === "head" || e3.name === "title" || e3.name === "link" || e3.name === "meta" ? [] : V(e3, (e4) => e4.kind === "element" && e4.name === "section").length > 0 ? vt(e3) : [e3]);
}
function yt(e2) {
  return e2.kind === "text" ? e2.text : e2.kind === "raw" ? "" : e2.children.map(yt).join("");
}
function bt(e2, t2) {
  let n2 = [];
  return t2.inner.replace(/@font-face\s*\{([^}]*)\}/g, (r2, i2) => {
    let a2 = /font-family\s*:\s*(["']?)([^;"']+)\1/.exec(i2)?.[2]?.trim(), o2 = /src\s*:\s*url\(\s*(["']?)([^)"']+)\1\s*\)/.exec(i2)?.[2]?.trim();
    return a2 !== void 0 && o2 !== void 0 && xt(o2) ? n2.push({
      family: a2,
      src: o2
    }) : R(e2, t2, "warning", "An @font-face is dropped: it needs a font-family and a src naming one of the deck's assets."), "";
  }).replace(/\/\*[\s\S]*?\*\//g, "").trim() !== "" && R(e2, t2, "warning", "A <style> may hold only @font-face rules; the rest is dropped. Style each element inline."), n2;
}
function xt(e2) {
  return /^assets\/[\w.-]{1,128}$/.test(e2);
}
function St(e2) {
  return xt(e2) || /^https:\/\/[^\s"'<>]+$/.test(e2);
}
function H(e2, t2, n2) {
  let r2 = z(n2, "style");
  if (r2 === void 0 || r2.trim() === "") return {};
  let i2 = {};
  for (let a2 of Ne(t2, r2)) "value" in a2 ? i2[a2.property] = a2.value : a2.silent !== true && R(e2, n2, "warning", `<${t2}> style \`${a2.property}\` ${a2.dropped}.`);
  return i2;
}
function Ct(e2, t2, n2, r2) {
  let i2 = z(t2, "id"), a2 = i2 ?? "";
  if (!gt.test(a2) || r2.has(a2)) {
    let o3 = wt(`slide-${n2 + 1}`, r2);
    R(e2, t2, "note", i2 === void 0 ? `The slide has no id; it is "${o3}".` : `id="${i2}" is ${r2.has(i2) ? "taken by an earlier slide" : "not [A-Za-z0-9_-]{1,64}"}; the slide is "${o3}".`), a2 = o3;
  }
  r2.add(a2);
  let o2 = z(t2, "data-transition"), s2 = z(t2, "data-section")?.trim(), c2 = t2.children.filter((e3) => e3.kind === "raw" && e3.name === "aside");
  for (let t3 of c2.filter((e3) => !e3.closed)) R(e2, t3, "warning", "<aside> has no </aside>; the notes end where the slide does.");
  let l2 = c2.map((e3) => Tt(e3.inner)).join("\n\n"), u2 = W(e2, t2.children.filter((e3) => e3.kind !== "raw" || e3.name !== "aside"), 1);
  return o2 !== void 0 && !L.includes(o2) && R(e2, t2, "warning", `data-transition="${o2}" is dropped: ${L.join(", ")}.`), e2.elements > $e && R(e2, t2, "warning", `This slide has ${e2.elements} elements; keep a slide under ${$e}, or split it.`), {
    id: a2,
    style: H(e2, "section", t2),
    ...L.includes(o2 ?? "") ? { transition: o2 } : {},
    ...s2 === void 0 || s2 === "" ? {} : { section: s2 },
    ...t2.attributes.some((e3) => e3.name === "hidden") ? { hidden: true } : {},
    notes: l2,
    children: u2
  };
}
function wt(e2, t2) {
  if (!t2.has(e2)) return e2;
  for (let n2 = 2; ; n2 += 1) if (!t2.has(`${e2}-${n2}`)) return `${e2}-${n2}`;
}
function Tt(e2) {
  return M(e2.replace(/<br\s*\/?>/gi, "\n").replace(/<\/?p\b[^>]*>/gi, "\n").replace(/<[^>]*>/g, "")).split("\n").map((e3) => e3.trim()).join("\n").replace(/\n{3,}/g, "\n\n").trim();
}
function Et(e2) {
  let t2 = e2.trim().split(/\s+/), n2 = /^-?\d+(\.\d+)?(%|px)$/;
  if (t2.length !== 3) return;
  let r2 = Number(t2[0]);
  return Number.isFinite(r2) && r2 >= 1 && r2 <= 50 && n2.test(t2[1]) && n2.test(t2[2]) ? {
    zoom: r2,
    x: t2[1],
    y: t2[2]
  } : void 0;
}
function Dt(e2, t2, n2) {
  let r2 = {}, i2 = mt[t2] ?? [];
  for (let { name: a2, value: o2 } of n2.attributes) a2 !== "style" && (a2 === "data-crop" && t2 === "img" && Et(o2) === void 0 ? R(e2, n2, "warning", `data-crop="${o2.slice(0, 60)}" is dropped: a zoom from 1 to 50 and where it is centred, as \`2 30% 40%\`.`) : pt.has(a2) || i2.includes(a2) ? r2[a2] = o2 : a2.startsWith("on") ? R(e2, n2, "warning", `<${t2} ${a2}> is dropped: a slide runs no scripts.`) : ht.test(a2) || R(e2, n2, "note", `<${t2}> attribute \`${a2}\` is dropped.`));
  return r2;
}
function U(e2) {
  if (lt.has(e2)) return "transparent";
  if (ut.has(e2)) return "dropped";
  let t2 = ct[e2] ?? e2;
  return tt.includes(t2) || nt.includes(t2) || [
    "li",
    "tr",
    "th",
    "td"
  ].includes(t2) ? t2 : "unknown";
}
function W(e2, t2, n2) {
  let r2 = [], i2 = [], a2 = () => {
    let t3 = G(e2, i2), n3 = i2[0];
    t3.length > 0 && n3 !== void 0 && (R(e2, n3, "note", "Text directly inside a container is set as a <p>."), r2.push(q("p", {}, {}, t3))), i2 = [];
  };
  for (let o2 of t2) {
    if (o2.kind === "text") {
      i2.push(o2);
      continue;
    }
    if (o2.kind === "raw") {
      a2(), r2.push(...Ot(e2, o2));
      continue;
    }
    let t3 = U(o2.name);
    t3 !== "transparent" && t3 !== "dropped" && t3 !== "unknown" && (ft.has(t3) || t3 === "br") ? i2.push(o2) : (a2(), r2.push(...kt(e2, o2, n2)));
  }
  return a2(), r2;
}
function Ot(e2, t2) {
  switch (!t2.closed && t2.name !== "script" && R(e2, t2, "warning", `<${t2.name}> has no </${t2.name}>; it ends where the slide does.`), t2.name) {
    case "svg":
      return Vt(e2, t2);
    case "script":
      return R(e2, t2, "warning", "<script> is dropped: a slide runs no scripts."), [];
    case "style":
      return R(e2, t2, "warning", "A <style> inside a slide is dropped: style each element inline."), [];
    default:
      return [];
  }
}
function kt(e2, t2, n2) {
  let r2 = U(t2.name);
  switch (r2) {
    case "transparent":
      return W(e2, t2.children, n2);
    case "dropped":
      return R(e2, t2, "warning", `<${t2.name}> is dropped: it is not in the slide subset.`), [];
    case "unknown":
      return R(e2, t2, "warning", `<${t2.name}> is not in the slide subset; what is inside it is kept.`), W(e2, t2.children, n2);
  }
  r2 !== t2.name && R(e2, t2, "note", `<${t2.name}> is read as <${r2}>.`), e2.elements += 1;
  let i2 = Dt(e2, r2, t2), a2 = H(e2, r2, t2);
  switch (r2) {
    case "div":
      return n2 > 15 ? (R(e2, t2, "warning", "Containers nest at most 15 deep; this one is flattened into its parent."), W(e2, t2.children, n2)) : [q("div", i2, a2, W(e2, t2.children, n2 + 1))];
    case "h1":
    case "h2":
    case "h3":
    case "p":
      return [q(r2, i2, a2, G(e2, t2.children))];
    case "ul":
    case "ol":
      return [q(r2, i2, a2, At(e2, t2, "li"))];
    case "table":
      return [q("table", i2, a2, At(e2, t2, "tr"))];
    case "img": {
      let n3 = i2.src;
      if (n3 === void 0 || !St(n3)) {
        R(e2, t2, "warning", n3 === void 0 ? "<img> has no src; it is drawn as an empty box." : `<img src="${n3.slice(0, 60)}"> is dropped: an image is one of the deck's assets or an https URL.`);
        let { src: r3, ...o2 } = i2;
        return [q("img", o2, a2, [])];
      }
      return [q("img", i2, a2, [])];
    }
    case "x-shape":
      return i2.kind === void 0 || !rt.includes(i2.kind) ? (R(e2, t2, "warning", `<x-shape kind="${i2.kind ?? ""}"> is drawn as a rect: kinds are ${rt.join(", ")}.`), [q("x-shape", {
        ...i2,
        kind: "rect"
      }, a2, [])]) : [q("x-shape", i2, a2, [])];
    case "x-icon":
      return i2.name === void 0 || Ye(i2.name) === void 0 ? (R(e2, t2, "warning", `<x-icon name="${i2.name ?? ""}"> is not an icon there is; it is dropped. See the icon list.`), []) : [q("x-icon", i2, a2, [])];
    case "x-connector":
    case "hr":
      return [q(r2, i2, a2, [])];
    case "li":
    case "tr":
    case "th":
    case "td":
      return R(e2, t2, "warning", `<${r2}> outside its ${r2 === "li" ? "list" : "table"} is set as a paragraph.`), [q("p", {}, {}, G(e2, t2.children))];
    default:
      return [q("p", {}, {}, G(e2, [t2]))];
  }
}
function At(e2, t2, n2) {
  let r2 = [], i2 = (a2) => {
    for (let o2 of a2) o2.kind === "text" ? o2.text.trim() !== "" && R(e2, o2, "warning", `Text directly inside <${t2.name}> is dropped: put it in a <${n2 === "li" ? "li" : "td"}>.`) : o2.kind !== "raw" && (lt.has(o2.name) ? i2(o2.children) : o2.name === n2 ? (e2.elements += 1, n2 === "li" ? r2.push(q("li", Dt(e2, "li", o2), H(e2, "li", o2), G(e2, o2.children))) : (jt(e2, o2), r2.push(q("tr", {}, H(e2, "tr", o2), Mt(e2, o2))))) : R(e2, o2, "warning", `<${o2.name}> inside <${t2.name}> is dropped: it holds only <${n2}>.`));
  };
  return i2(t2.children), r2;
}
function jt(e2, t2) {
  for (let { name: n2 } of t2.attributes) pt.has(n2) && R(e2, t2, "note", `<${t2.name}> attribute \`${n2}\` is dropped: give it to the <table>.`);
}
function Mt(e2, t2) {
  return t2.children.flatMap((t3) => t3.kind === "element" ? t3.name !== "td" && t3.name !== "th" ? (R(e2, t3, "warning", `<${t3.name}> inside <tr> is dropped: a row holds <th> and <td>.`), []) : (t3.attributes.some((e3) => e3.name === "colspan" || e3.name === "rowspan") && R(e2, t3, "warning", "colspan and rowspan are dropped: every cell is one cell."), e2.elements += 1, jt(e2, t3), [q(t3.name, {}, H(e2, t3.name, t3), G(e2, t3.children))]) : []);
}
function G(e2, t2) {
  let n2 = K(e2, t2), r2 = (e3) => e3?.type === "element" && e3.tag === "br";
  for (; r2(n2[0]); ) n2.shift();
  for (; r2(n2.at(-1)); ) n2.pop();
  return Ft(n2);
}
var Nt = /* @__PURE__ */ new Set([
  "h1",
  "h2",
  "h3",
  "p",
  "div",
  "ul",
  "ol",
  "li",
  "table",
  "tr",
  "td",
  "th"
]);
function K(e2, t2) {
  let n2 = [], r2 = () => {
    let e3 = n2.at(-1);
    e3 !== void 0 && (e3.type !== "element" || e3.tag !== "br") && n2.push(q("br", {}, {}, []));
  };
  for (let i2 of t2) {
    let t3 = i2.kind === "element" ? U(i2.name) : void 0;
    i2.kind === "element" && typeof t3 == "string" && Nt.has(t3) ? (dt.has(t3) || R(e2, i2, "note", `<${i2.name}> inside text is set as lines of that text.`), r2(), n2.push(...K(e2, i2.children)), r2()) : n2.push(...Pt(e2, i2));
  }
  return n2;
}
function Pt(e2, t2) {
  if (t2.kind === "text") return [{
    type: "text",
    text: t2.text
  }];
  if (t2.kind === "raw") return t2.name === "svg" && R(e2, t2, "warning", "An <svg> inside text is dropped: place it beside the text, in the container."), [];
  let n2 = U(t2.name);
  if (n2 === "br") return [q("br", {}, {}, [])];
  if (n2 === "dropped") return R(e2, t2, "warning", `<${t2.name}> is dropped: it is not in the slide subset.`), [];
  if (typeof n2 == "string" && ft.has(n2)) {
    n2 !== t2.name && t2.name !== "strong" && t2.name !== "em" && R(e2, t2, "note", `<${t2.name}> is read as <${n2}>.`);
    let r2 = Dt(e2, n2, t2);
    return n2 === "a" && r2.href !== void 0 && !/^(https?:|mailto:|#)/.test(r2.href) && (R(e2, t2, "warning", `<a href="${r2.href.slice(0, 60)}"> loses its link: links are https:, mailto: or #slide-id.`), delete r2.href), [q(n2, r2, H(e2, n2, t2), K(e2, t2.children))];
  }
  return n2 === "img" || n2 === "x-icon" || n2 === "x-shape" ? (R(e2, t2, "warning", `<${t2.name}> inside text is dropped: place it beside the text, in the container.`), []) : (n2 === "unknown" && R(e2, t2, "note", `<${t2.name}> is not in the slide subset; its words are kept.`), K(e2, t2.children));
}
function Ft(e2) {
  let t2 = It(e2);
  Lt(t2, "start"), Lt(t2, "end");
  let n2 = Rt(t2);
  for (; n2.at(-1)?.type === "element" && n2.at(-1).tag === "br"; ) n2.pop();
  return n2;
}
function It(e2, t2 = { space: true }) {
  let n2 = [];
  for (let r2 of e2) if (r2.type === "text") {
    let e3 = r2.text.replace(/[ \t\n\r\f]+/g, " ");
    t2.space && e3.startsWith(" ") && (e3 = e3.slice(1)), e3 !== "" && (t2.space = e3.endsWith(" "));
    let i2 = n2.at(-1);
    i2?.type === "text" ? n2[n2.length - 1] = {
      type: "text",
      text: i2.text + e3
    } : n2.push({
      type: "text",
      text: e3
    });
  } else r2.type === "element" ? (r2.tag === "br" && (t2.space = true), n2.push({
    ...r2,
    children: It(r2.children, t2)
  })) : n2.push(r2);
  return n2;
}
function Lt(e2, t2) {
  let n2 = t2 === "start" ? e2.keys() : [...e2.keys()].reverse();
  for (let r2 of n2) {
    let n3 = e2[r2];
    if (n3.type === "text") {
      let i2 = t2 === "start" ? n3.text.replace(/^ /, "") : n3.text.replace(/ $/, "");
      if (e2[r2] = {
        type: "text",
        text: i2
      }, i2 !== "") break;
    } else {
      if (n3.type === "element" && n3.tag === "br") break;
      if (n3.type === "element") {
        let i2 = [...n3.children];
        if (Lt(i2, t2), e2[r2] = {
          ...n3,
          children: i2
        }, i2.some((e3) => e3.type !== "text" || e3.text !== "")) break;
      }
    }
  }
  for (let t3 = 0; t3 < e2.length; t3 += 1) {
    let n3 = e2[t3];
    if (n3.type === "element" && n3.tag === "br") {
      let n4 = e2[t3 - 1], r2 = e2[t3 + 1];
      n4?.type === "text" && (e2[t3 - 1] = {
        type: "text",
        text: n4.text.replace(/ $/, "")
      }), r2?.type === "text" && (e2[t3 + 1] = {
        type: "text",
        text: r2.text.replace(/^ /, "")
      });
    }
  }
}
function Rt(e2) {
  return e2.flatMap((e3) => {
    if (e3.type === "text") return e3.text === "" ? [] : [e3];
    if (e3.type === "element" && ft.has(e3.tag)) {
      let t2 = Rt(e3.children);
      return t2.length === 0 ? [] : [{
        ...e3,
        children: t2
      }];
    }
    return [e3];
  });
}
var zt = [
  [/<script\b/i, "holds a <script>"],
  [/[\s/"']on[a-z]+\s*=/i, "holds an event handler"],
  [/<foreignObject\b/i, "holds a <foreignObject>"],
  [/<style\b/i, "holds a <style>"],
  [/javascript:/i, "names javascript:"],
  [/(?:xlink:)?href\s*=\s*(?!["']?#)/i, "refers to something outside itself"],
  [/url\(\s*["']?(?!#)/i, "refers to something outside itself"],
  [/<(iframe|embed|object|video|audio|image)\b/i, "holds media"],
  [/<(?:set|animate\w*)\b[^>]*attributeName\s*=\s*["']?\s*(?:xlink:)?(?:href|on|style)/i, "animates a link, a handler or a style"]
];
function Bt(e2) {
  if (e2.attributes.some((e3) => /^on/i.test(e3.name))) return "holds an event handler";
  if (e2.attributes.some((e3) => /href$/i.test(e3.name) && !e3.value.startsWith("#"))) return "refers to something outside itself";
  let t2 = M(e2.inner), n2 = t2.replace(/[\t\n\r]/g, "");
  return zt.find(([e3]) => e3.test(t2) || e3.test(n2))?.[1];
}
function Vt(e2, t2) {
  let n2 = Bt(t2);
  if (n2 !== void 0) return R(e2, t2, "warning", `An <svg> is dropped: it ${n2}. A drawing holds shapes and its own #id references only.`), [];
  if (t2.inner.length > et) return R(e2, t2, "warning", `An <svg> of ${t2.inner.length} bytes is dropped: a drawing is at most ${et} bytes.`), [];
  e2.elements += 1;
  let r2 = {};
  for (let { name: e3, value: n3 } of t2.attributes) e3 === "style" || e3 === "xmlns" || e3.startsWith("xmlns:") || (r2[e3] = n3);
  return r2["aria-label"] === void 0 && R(e2, t2, "note", "An <svg> without aria-label: say what it shows, for a reader who cannot see it."), [{
    type: "svg",
    attributes: r2,
    style: H(e2, "svg", t2),
    markup: t2.inner.trim()
  }];
}
function q(e2, t2, n2, r2) {
  return {
    type: "element",
    tag: e2,
    attributes: t2,
    style: n2,
    children: r2
  };
}
var Ht = [
  "id",
  "kind",
  "name",
  "src",
  "alt",
  "href",
  "x1",
  "y1",
  "x2",
  "y2",
  "from",
  "head",
  "route",
  "data-crop",
  "data-build-in",
  "data-build-out"
];
function J(e2, t2) {
  let n2 = Object.keys(e2).sort((e3, t3) => {
    let n3 = Ht.indexOf(e3), r3 = Ht.indexOf(t3);
    return (n3 === -1 ? 99 : n3) - (r3 === -1 ? 99 : r3) || e3.localeCompare(t3);
  }).map((t3) => ` ${t3}="${P(e2[t3])}"`), r2 = Le(t2);
  return n2.join("") + (r2 === "" ? "" : ` style="${P(r2)}"`);
}
function Ut(e2) {
  return e2.map((e3) => e3.type === "text" ? N(e3.text) : e3.type === "svg" ? "" : e3.tag === "br" ? "<br>" : `<${e3.tag}${J(e3.attributes, e3.style)}>${Ut(e3.children)}</${e3.tag}>`).join("");
}
var Wt = /* @__PURE__ */ new Set([
  "img",
  "hr",
  "br"
]);
function Gt(e2, t2) {
  if (e2.type === "text") return t2 + N(e2.text);
  if (e2.type === "svg") return `${t2}<svg${J(e2.attributes, e2.style)}>${e2.markup}</svg>`;
  let n2 = `${t2}<${e2.tag}${J(e2.attributes, e2.style)}>`;
  return Wt.has(e2.tag) ? n2 : e2.tag === "x-shape" || e2.tag === "x-icon" || e2.tag === "x-connector" ? `${n2}</${e2.tag}>` : e2.tag === "div" || e2.tag === "ul" || e2.tag === "ol" || e2.tag === "table" || e2.tag === "tr" ? e2.children.length === 0 ? `${n2}</${e2.tag}>` : [
    n2,
    ...e2.children.map((e3) => Gt(e3, `${t2}  `)),
    `${t2}</${e2.tag}>`
  ].join("\n") : `${n2}${Ut(e2.children)}</${e2.tag}>`;
}
function Kt(e2) {
  let t2 = { id: e2.id };
  e2.transition !== void 0 && (t2["data-transition"] = e2.transition), e2.section !== void 0 && (t2["data-section"] = e2.section);
  let n2 = e2.hidden === true ? " hidden" : "", r2 = e2.notes.trim() === "" ? [] : [`<aside>${N(e2.notes.trim())}</aside>`];
  return [
    `<section${J(t2, e2.style)}${n2}>`,
    ...e2.children.map((e3) => Gt(e3, "")),
    ...r2,
    "</section>"
  ].join("\n");
}
function qt(e2) {
  let t2 = e2.fontFaces.map((e3) => `@font-face{font-family:"${e3.family.replace(/["\\]/g, "")}";src:url(${e3.src})}`);
  return [
    "<!doctype html>",
    "<html>",
    "<head>",
    '<meta charset="utf-8">',
    `<title>${N(e2.title)}</title>`,
    ...e2.fontLinks.map((e3) => `<link rel="stylesheet" href="${P(e3)}">`),
    ...t2.length === 0 ? [] : [`<style>${t2.join("")}</style>`],
    "</head>",
    `<body${J(e2.theme === void 0 ? {} : { "data-theme": e2.theme }, e2.style)}>`,
    ...e2.slides.map(Kt),
    "</body>",
    "</html>",
    ""
  ].join("\n");
}
function Jt(e2) {
  return e2.map((e3) => Gt(e3, "")).join("\n");
}
function Yt(e2) {
  let { deck: t2 } = _t(`<section id="paste">${e2}</section>`);
  return [...t2.slides[0]?.children ?? []];
}
var Xt = 24;
function Zt(e2) {
  let t2 = e2.filter((e3) => e3.severity === "warning"), n2 = t2.slice(0, Xt).map((e3) => `${e3.slide === void 0 ? "" : `Slide ${e3.slide}, `}line ${e3.line}: ${e3.message}`);
  return t2.length > Xt ? [...n2, `\u2026and ${t2.length - Xt} more like these.`] : n2;
}
function* Qt(e2, t2 = []) {
  for (let [n2, r2] of e2.entries()) {
    let e3 = [...t2, n2];
    yield {
      node: r2,
      path: e3
    }, r2.type === "element" && (yield* Qt(r2.children, e3));
  }
}
function Y(e2) {
  return e2.map((e3) => {
    if (e3.type === "text") return e3.text;
    if (e3.type === "svg") return "";
    if (e3.tag === "br") return "\n";
    let t2 = Y(e3.children);
    return dt.has(e3.tag) || e3.tag === "li" || e3.tag === "div" || e3.tag === "tr" ? `${t2}
` : e3.tag === "td" || e3.tag === "th" ? `${t2}	` : t2;
  }).join("");
}
function $t(e2) {
  for (let { node: t2 } of Qt(e2.children)) if (t2.type === "element" && (t2.tag === "h1" || t2.tag === "h2")) return Y(t2.children).trim();
  return Y(e2.children).trim().split("\n")[0]?.trim() ?? "";
}
function en(e2) {
  return dt.has(e2) || e2 === "li" || e2 === "th" || e2 === "td";
}
var tn = `
.deck-root{font-family:system-ui,-apple-system,"Segoe UI","Noto Sans","PingFang SC","Hiragino Sans",sans-serif;color:var(--text,#1d1d1f);color-scheme:light}
.deck-slide{position:relative;width:${Ze}px;height:${Qe}px;overflow:hidden;display:flex;flex-direction:column;background:var(--background,#ffffff);font-size:32px;line-height:1.4;overflow-wrap:break-word;-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility}
.deck-slide,.deck-slide *{margin:0;box-sizing:border-box;corner-shape:round}
.deck-slide div{display:flex;flex-direction:column;min-width:0}
.deck-slide h1{font-size:96px;font-weight:600;line-height:1.1}
.deck-slide h2{font-size:64px;font-weight:600;line-height:1.15}
.deck-slide h3{font-size:44px;font-weight:600;line-height:1.2}
.deck-slide ul,.deck-slide ol{padding-left:1.25em}
.deck-slide ul{list-style:disc}
.deck-slide ol{list-style:decimal}
.deck-slide li+li{margin-top:.25em}
.deck-slide a{color:inherit;text-decoration:underline}
.deck-slide b{font-weight:700}
.deck-slide img{display:block;max-width:none;object-fit:cover}
.deck-slide table{border-collapse:collapse;font-variant-numeric:tabular-nums}
.deck-slide th,.deck-slide td{padding:.35em .6em;border-bottom:1px solid rgb(128 128 128 / .3);text-align:left;vertical-align:top}
.deck-slide th{font-weight:600}
.deck-slide hr{border:0;border-top:2px solid currentColor;width:100%;flex:none}
.deck-slide .deck-shape,.deck-slide .deck-icon{flex:none}
.deck-slide .deck-shape>svg,.deck-slide .deck-icon>svg{display:block;width:100%;height:100%;overflow:visible}
.deck-slide .deck-connector{position:absolute;left:0;top:0;width:100%;height:100%;overflow:visible;pointer-events:none}
`;
var nn = "\n@keyframes deck-fade-in { from { opacity: 0 } to { opacity: 1 } }\n@keyframes deck-fade-out { from { opacity: 1 } to { opacity: 0 } }\n@keyframes deck-push-in { from { transform: translateX(100%) } to { transform: none } }\n@keyframes deck-push-out { from { transform: none } to { transform: translateX(-100%) } }\n@keyframes deck-push-in-back { from { transform: translateX(-100%) } to { transform: none } }\n@keyframes deck-push-out-back { from { transform: none } to { transform: translateX(100%) } }\n@keyframes deck-build-fade { from { opacity: 0 } }\n@keyframes deck-build-rise { from { opacity: 0; transform: translateY(48px) } }\n@keyframes deck-build-drop { from { opacity: 0; transform: translateY(-48px) } }\n@keyframes deck-build-left { from { opacity: 0; transform: translateX(-96px) } }\n@keyframes deck-build-right { from { opacity: 0; transform: translateX(96px) } }\n@keyframes deck-build-scale { from { opacity: 0; transform: scale(0.6) } }\n@keyframes deck-build-pop { 0% { opacity: 0; transform: scale(0.5) } 70% { opacity: 1; transform: scale(1.06) } 100% { transform: none } }\n";
var rn = {
  diamond: "50,0 100,50 50,100 0,50",
  triangle: "50,0 100,100 0,100",
  "arrow-right": "0,30 60,30 60,0 100,50 60,100 60,70 0,70",
  "arrow-left": "100,30 40,30 40,0 0,50 40,100 40,70 100,70",
  "arrow-up": "30,100 30,40 0,40 50,0 100,40 70,40 70,100",
  "arrow-down": "30,0 30,60 0,60 50,100 100,60 70,60 70,0"
};
function an(e2, t2 = {}, n2 = [], r2 = on) {
  return e2.flatMap((e3, i2) => sn(e3, t2, [...n2, i2], r2));
}
var on = {
  width: Ze,
  height: Qe
};
function sn(e2, t2, n2, r2) {
  let i2 = t2.paths === true ? { path: n2 } : {};
  if (e2.type === "text") return [{
    kind: "text",
    text: e2.text
  }];
  if (e2.type === "svg") {
    let { "aria-label": n3, ...r3 } = e2.attributes, a2 = `<svg xmlns="http://www.w3.org/2000/svg"${Object.entries(r3).map(([e3, t3]) => ` ${e3}="${P(t3)}"`).join("")}>${e2.markup}</svg>`;
    return t2.svgAsImage === false ? [{
      kind: "markup",
      attributes: {},
      style: {
        ...ln(e2),
        ...e2.style,
        display: "block"
      },
      markup: a2.replace("<svg ", '<svg width="100%" height="100%" '),
      ...i2
    }] : [{
      kind: "element",
      tag: "img",
      attributes: {
        src: `data:image/svg+xml;charset=utf-8,${encodeURIComponent(a2)}`,
        alt: n3 ?? "",
        draggable: "false"
      },
      style: {
        "object-fit": "contain",
        ...ln(e2),
        ...e2.style
      },
      children: [],
      ...i2
    }];
  }
  switch (e2.tag) {
    case "x-shape":
      return [dn(e2, i2)];
    case "x-icon":
      return [{
        kind: "markup",
        class: "deck-icon",
        attributes: X(e2),
        style: {
          width: "64px",
          height: "64px",
          ...e2.style
        },
        markup: Xe(e2.attributes.name ?? ""),
        ...i2
      }];
    case "x-connector":
      return [mn(e2, i2, r2, t2.hitAreas === true)];
    case "img": {
      let n3 = e2.attributes.src, r3 = n3 === void 0 ? void 0 : t2.resolveAsset?.(n3) ?? n3;
      return [{
        kind: "element",
        tag: "img",
        attributes: {
          ...r3 === void 0 ? {} : { src: r3 },
          alt: e2.attributes.alt ?? "",
          draggable: "false",
          ...X(e2)
        },
        style: {
          ...r3 === void 0 ? { background: "rgb(128 128 128 / .15)" } : {},
          ...un(e2),
          ...e2.style
        },
        children: [],
        ...i2
      }];
    }
    default: {
      let a2 = X(e2);
      return e2.tag === "a" && e2.attributes.href !== void 0 && (a2.href = e2.attributes.href, a2.target = "_blank", a2.rel = "noopener"), [{
        kind: "element",
        tag: e2.tag,
        attributes: a2,
        style: { ...e2.style },
        children: an(e2.children, t2, n2, cn(e2, r2)),
        ...i2
      }];
    }
  }
}
function cn(e2, t2) {
  return e2.tag !== "div" || e2.style.position !== "relative" ? t2 : {
    width: C(e2.style.width ?? "") ?? t2.width,
    height: C(e2.style.height ?? "") ?? t2.height
  };
}
function ln(e2) {
  let t2 = {}, n2 = C(e2.attributes.width ?? ""), r2 = C(e2.attributes.height ?? "");
  return n2 !== void 0 && (t2.width = `${n2}px`), r2 !== void 0 && (t2.height = `${r2}px`), t2;
}
function un(e2) {
  let t2 = Et(e2.attributes["data-crop"] ?? "");
  return t2 === void 0 ? {} : {
    "object-position": `${t2.x} ${t2.y}`,
    "transform-origin": `${t2.x} ${t2.y}`,
    scale: String(t2.zoom)
  };
}
function X(e2) {
  let t2 = {};
  for (let n2 of [
    "id",
    "data-build-in",
    "data-build-out"
  ]) {
    let r2 = e2.attributes[n2];
    r2 !== void 0 && (t2[n2] = r2);
  }
  return t2;
}
function dn(e2, t2) {
  let n2 = e2.attributes.kind ?? "rect", { background: r2, border: i2, ...a2 } = e2.style, o2 = X(e2);
  if (n2 === "rect" || n2 === "rounded" || n2 === "ellipse") return {
    kind: "element",
    tag: "div",
    attributes: o2,
    style: {
      width: "240px",
      height: "160px",
      ...n2 === "rounded" ? { "border-radius": "24px" } : n2 === "ellipse" ? { "border-radius": "50%" } : {},
      ...r2 === void 0 ? { background: "#d4d4d8" } : { background: r2 },
      ...i2 === void 0 ? {} : { border: i2 },
      ...a2
    },
    children: [],
    class: "deck-shape",
    ...t2
  };
  let s2 = r2 ?? "#d4d4d8", c2 = fn(i2), l2 = n2 === "line" ? `<line x1="0" y1="50" x2="100" y2="50" stroke="${P(c2?.color ?? s2)}" stroke-width="${c2?.width ?? 4}" vector-effect="non-scaling-stroke"${Z(c2?.style)}/>` : `<polygon points="${rn[n2] ?? rn.diamond}" fill="${P(s2)}"${c2 === void 0 ? "" : ` stroke="${P(c2.color)}" stroke-width="${c2.width}" vector-effect="non-scaling-stroke" stroke-linejoin="round"${Z(c2.style)}`}/>`;
  return {
    kind: "markup",
    class: "deck-shape",
    attributes: o2,
    style: {
      width: "240px",
      height: n2 === "line" ? "8px" : "160px",
      ...a2
    },
    markup: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="none">${l2}</svg>`,
    ...t2
  };
}
function fn(e2) {
  if (e2 === void 0 || e2 === "none") return;
  let t2 = e2.split(/\s+(?![^(]*\))/);
  return {
    width: C(t2[0] ?? "") ?? 1,
    style: t2[1] ?? "solid",
    color: t2[2] ?? "#000000"
  };
}
function Z(e2) {
  return e2 === "dashed" ? ' stroke-dasharray="8 6"' : e2 === "dotted" ? ' stroke-dasharray="2 4" stroke-linecap="round"' : "";
}
function pn(e2, t2) {
  if (e2 === void 0) return;
  let n2 = /^(-?[\d.]+)%$/.exec(e2.trim());
  return n2 === null ? C(e2) : Number(n2[1]) / 100 * t2;
}
function mn(e2, t2, n2, r2) {
  let i2 = e2.style.color ?? "#1d1d1f", a2 = fn(e2.style.border), o2 = a2?.width ?? 3, s2 = e2.attributes.head ?? "end", c2 = `deck-arrow-${i2.replace(/[^a-z0-9]/gi, "")}-${o2}`, l2 = `<marker id="${c2}" viewBox="0 0 10 10" refX="8" refY="5" markerUnits="userSpaceOnUse" markerWidth="${10 + o2 * 4}" markerHeight="${10 + o2 * 4}" orient="auto-start-reverse"><path d="M0 0 10 5 0 10z" fill="${P(i2)}"/></marker>`, u2 = `${s2 === "end" || s2 === "both" ? ` marker-end="url(#${c2})"` : ""}${s2 === "both" ? ` marker-start="url(#${c2})"` : ""}`, d2 = pn(e2.attributes.x1, n2.width), f2 = pn(e2.attributes.y1, n2.height), p2 = pn(e2.attributes.x2, n2.width), m2 = pn(e2.attributes.y2, n2.height), h2 = (e3) => `<polyline points="${e3}" fill="none" stroke="${P(i2)}" stroke-width="${o2}" stroke-linejoin="round"${Z(a2?.style)}${u2}/>` + (r2 ? `<polyline points="${e3}" fill="none" stroke="transparent" stroke-width="24" pointer-events="stroke"/>` : "");
  if (d2 !== void 0 && f2 !== void 0 && p2 !== void 0 && m2 !== void 0) {
    let r3 = e2.attributes.route ?? "straight", i3 = (d2 + p2) / 2, a3 = r3 === "hv" ? `${d2},${f2} ${p2},${f2} ${p2},${m2}` : r3 === "vh" ? `${d2},${f2} ${d2},${m2} ${p2},${m2}` : r3 === "elbow" ? `${d2},${f2} ${i3},${f2} ${i3},${m2} ${p2},${m2}` : `${d2},${f2} ${p2},${m2}`;
    return {
      kind: "markup",
      attributes: X(e2),
      style: {
        position: "absolute",
        left: "0",
        top: "0",
        width: `${n2.width}px`,
        height: `${n2.height}px`,
        "pointer-events": "none",
        ...e2.style.opacity === void 0 ? {} : { opacity: e2.style.opacity }
      },
      markup: `<svg xmlns="http://www.w3.org/2000/svg" width="${n2.width}" height="${n2.height}" viewBox="0 0 ${n2.width} ${n2.height}" style="overflow:visible"><defs>${l2}</defs>${h2(a3)}</svg>`,
      ...t2
    };
  }
  let g2 = e2.attributes.from ?? "tl", [_2, v2, y2, b2] = g2 === "tr" ? [
    100,
    0,
    0,
    100
  ] : g2 === "bl" ? [
    0,
    100,
    100,
    0
  ] : g2 === "br" ? [
    100,
    100,
    0,
    0
  ] : [
    0,
    0,
    100,
    100
  ], { border: ee2, color: x2, ...S2 } = e2.style;
  return {
    kind: "markup",
    attributes: X(e2),
    style: {
      width: "96px",
      height: `${Math.max(o2, 2)}px`,
      "align-self": "center",
      flex: "none",
      ...S2
    },
    markup: `<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" style="overflow:visible;display:block"><defs>${l2}</defs><svg viewBox="0 0 100 100" preserveAspectRatio="none" overflow="visible"><line x1="${_2}" y1="${v2 === b2 ? 50 : v2}" x2="${y2}" y2="${v2 === b2 ? 50 : b2}" stroke="${P(i2)}" stroke-width="${o2}" vector-effect="non-scaling-stroke"${Z(a2?.style)}${u2}/></svg></svg>`,
    ...t2
  };
}
function hn(e2) {
  return Object.entries(e2).map(([e3, t2]) => `${e3}:${t2}`).join(";");
}
var gn = /* @__PURE__ */ new Set([
  "img",
  "hr",
  "br"
]);
function _n(e2) {
  return e2.map((e3) => {
    if (e3.kind === "text") return N(e3.text);
    let t2 = e3.class === void 0 ? "" : ` class="${e3.class}"`, n2 = hn(e3.style), r2 = n2 === "" ? "" : ` style="${P(n2)}"`, i2 = Object.entries(e3.attributes).map(([e4, t3]) => ` ${e4}="${P(t3)}"`).join("");
    if (e3.kind === "markup") return `<div${t2}${i2}${r2}>${e3.markup}</div>`;
    let a2 = `<${e3.tag}${t2}${i2}${r2}>`;
    return gn.has(e3.tag) ? a2 : `${a2}${_n(e3.children)}</${e3.tag}>`;
  }).join("");
}
function vn(e2, t2 = {}) {
  let n2 = [
    `id="${P(e2.id)}"`,
    ...e2.transition === void 0 ? [] : [`data-transition="${e2.transition}"`],
    ...e2.hidden === true ? ["hidden"] : []
  ], r2 = hn(e2.style);
  return `<section class="deck-slide" ${n2.join(" ")}${r2 === "" ? "" : ` style="${P(r2)}"`}>${_n(an(e2.children, t2))}</section>`;
}
function yn(e2, t2 = (e3) => e3) {
  let n2 = e2.fontFaces.map((e3) => `@font-face{font-family:"${e3.family.replace(/["\\]/g, "")}";src:url("${t2(e3.src)}");font-display:swap}`).join("");
  return [...e2.fontLinks.map((e3) => `<link rel="stylesheet" href="${P(e3)}">`), ...n2 === "" ? [] : [`<style>${n2}</style>`]].join("\n");
}
function bn(e2, n2 = t) {
  return hn({
    ...o(n2),
    ...e2
  });
}
function xn(e2) {
  return e2.join(".");
}
function Sn(e2) {
  return e2 === "" ? [] : e2.split(".").map(Number);
}
function Cn(e2, t2) {
  return e2.length === t2.length && e2.every((e3, n2) => e3 === t2[n2]);
}
function wn(e2, t2) {
  return t2.length <= e2.length && t2.every((t3, n2) => t3 === e2[n2]);
}
function Tn(e2) {
  return e2.slice(0, -1);
}
function En(e2, t2) {
  let n2, r2 = e2;
  for (let e3 of t2) {
    if (n2 = r2[e3], n2 === void 0) return;
    r2 = n2.type === "element" ? n2.children : [];
  }
  return n2;
}
function Dn(e2, t2) {
  let n2 = En(e2, t2);
  return n2?.type === "element" ? n2 : void 0;
}
function On(e2, t2) {
  if (t2.length === 0) return e2;
  let n2 = En(e2, t2);
  return n2?.type === "element" ? n2.children : [];
}
function kn(e2, t2, n2) {
  let [r2, ...i2] = t2;
  if (r2 === void 0 || e2[r2] === void 0) return [...e2];
  let a2 = [...e2], o2 = e2[r2];
  return a2[r2] = i2.length === 0 ? n2(o2) : o2.type === "element" ? {
    ...o2,
    children: kn(o2.children, i2, n2)
  } : o2, a2;
}
function An(e2, t2, n2) {
  return t2.length === 0 ? n2(e2) : kn(e2, t2, (e3) => e3.type === "element" ? {
    ...e3,
    children: n2(e3.children)
  } : e3);
}
function jn(e2) {
  return [...e2].sort((e3, t2) => {
    for (let n2 = 0; n2 < Math.min(e3.length, t2.length); n2 += 1) if (e3[n2] !== t2[n2]) return t2[n2] - e3[n2];
    return t2.length - e3.length;
  });
}
function Mn(e2, t2) {
  let n2 = t2.filter((e3) => !t2.some((t3) => t3 !== e3 && t3.length < e3.length && wn(e3, t3))), r2 = [...e2];
  for (let e3 of jn(n2)) {
    let t3 = e3.at(-1);
    r2 = An(r2, Tn(e3), (e4) => e4.filter((e5, n3) => n3 !== t3));
  }
  return r2;
}
function Nn(e2, t2, n2, r2) {
  return An(e2, t2, (e3) => [
    ...e3.slice(0, n2),
    ...r2,
    ...e3.slice(n2)
  ]);
}
function Pn(e2, t2, n2) {
  let r2 = { ...t2 };
  for (let [t3, i2] of Object.entries(n2)) {
    if (i2 === void 0 || i2 === "") {
      delete r2[t3];
      continue;
    }
    let n3 = Be(e2, t3, i2);
    n3 !== void 0 && (r2[t3] = n3);
  }
  return r2;
}
function Fn(e2, t2) {
  return e2.type === "text" ? e2 : {
    ...e2,
    style: Pn(e2.type === "svg" ? "svg" : e2.tag, e2.style, t2)
  };
}
function In(e2, t2, n2) {
  if (e2.type === "text") return e2;
  let r2 = { ...e2.attributes };
  return n2 === void 0 ? delete r2[t2] : r2[t2] = n2, {
    ...e2,
    attributes: r2
  };
}
function Ln(e2, t2, n2) {
  let r2 = e2.slides[t2];
  if (r2 === void 0) return e2;
  let i2 = [...e2.slides];
  return i2[t2] = n2(r2), {
    ...e2,
    slides: i2
  };
}
function Rn(e2, t2, n2) {
  return Ln(e2, t2, (e3) => ({
    ...e3,
    children: n2(e3.children)
  }));
}
function zn(e2) {
  let t2 = /rotate\((-?[\d.]+)(deg|turn|rad)\)/.exec(e2.transform ?? "");
  if (t2 === null) return 0;
  let n2 = Number(t2[1]);
  return t2[2] === "turn" ? n2 * 360 : t2[2] === "rad" ? n2 * 180 / Math.PI : n2;
}
function Bn(e2, t2) {
  let n2 = Math.round(t2 * 10) / 10, r2 = (e2 ?? "").split(/\s+(?![^(]*\))/).filter((e3) => e3 !== "" && e3 !== "none" && !e3.startsWith("rotate(")), i2 = r2.filter((e3) => e3.startsWith("translate")), a2 = r2.filter((e3) => !e3.startsWith("translate")), o2 = n2 === 0 || n2 === 360 ? [] : [`rotate(${n2}deg)`], s2 = [
    ...i2,
    ...o2,
    ...a2
  ].join(" ");
  return s2 === "" ? void 0 : s2;
}
function Vn(e2, t2 = {}, n2 = [], r2 = {}) {
  return {
    type: "element",
    tag: e2,
    attributes: r2,
    style: t2,
    children: n2
  };
}
function Hn(e2) {
  return {
    type: "text",
    text: e2
  };
}
function Un(e2, t2) {
  for (let n2 = t2.length; n2 > 0; n2--) {
    let r2 = t2.slice(0, n2);
    if (Dn(e2, r2)?.tag === "table") return {
      table: r2,
      row: t2[n2],
      column: t2[n2 + 1]
    };
  }
}
var Q = (e2) => e2.type === "element" && e2.tag === "tr";
var $ = (e2) => e2.type === "element" && (e2.tag === "td" || e2.tag === "th");
var Wn = (e2) => e2.children.some($) && e2.children.filter($).every((e3) => e3.tag === "th");
function Gn(e2, t2 = e2.tag) {
  let { id: n2, ...r2 } = e2.attributes;
  return Vn(t2, e2.style, [], r2);
}
function Kn(e2, t2) {
  let n2 = e2.children, r2 = Math.max(0, Math.min(t2, n2.length)), i2 = [
    n2[r2],
    n2[r2 - 1],
    ...n2
  ].filter((e3) => e3 !== void 0 && Q(e3)), a2 = i2.find((e3) => !Wn(e3)) ?? i2[0];
  if (a2 === void 0) return e2;
  let o2 = Wn(a2), { id: s2, ...c2 } = a2.attributes, l2 = Vn("tr", a2.style, a2.children.filter($).map((e3) => Gn(e3, o2 ? "td" : e3.tag)), c2);
  return {
    ...e2,
    children: [
      ...n2.slice(0, r2),
      l2,
      ...n2.slice(r2)
    ]
  };
}
function qn(e2, t2) {
  return {
    ...e2,
    children: e2.children.map((e3) => {
      if (!Q(e3)) return e3;
      let n2 = Math.max(0, Math.min(t2, e3.children.length)), r2 = [
        e3.children[n2 - 1],
        e3.children[n2],
        ...e3.children
      ].find((e4) => e4 !== void 0 && $(e4));
      return r2 === void 0 ? e3 : {
        ...e3,
        children: [
          ...e3.children.slice(0, n2),
          Gn(r2),
          ...e3.children.slice(n2)
        ]
      };
    })
  };
}
function Jn(e2, t2) {
  return e2.children.filter(Q).length <= 1 ? e2 : {
    ...e2,
    children: e2.children.filter((e3, n2) => n2 !== t2)
  };
}
function Yn(e2, t2) {
  return Math.max(0, ...e2.children.filter(Q).map((e3) => e3.children.filter($).length)) <= 1 ? e2 : {
    ...e2,
    children: e2.children.map((e3) => Q(e3) ? {
      ...e3,
      children: e3.children.filter((e4, n2) => n2 !== t2)
    } : e3)
  };
}
var Xn = [
  "rowAbove",
  "rowBelow",
  "columnLeft",
  "columnRight",
  "removeRow",
  "removeColumn"
];
function Zn(e2, t2, n2) {
  let r2 = Un(e2, t2), i2 = r2 === void 0 ? void 0 : Dn(e2, r2.table);
  if (r2 === void 0 || i2 === void 0) return;
  let a2 = i2.children.filter(Q), o2 = a2.length - 1, s2 = Math.max(0, ...a2.map((e3) => e3.children.filter($).length)) - 1, c2 = r2.row ?? o2, l2 = r2.column ?? s2, u2 = {
    rowAbove: () => [
      Kn(i2, c2),
      1,
      0
    ],
    rowBelow: () => [
      Kn(i2, c2 + 1),
      0,
      0
    ],
    columnLeft: () => [
      qn(i2, l2),
      0,
      1
    ],
    columnRight: () => [
      qn(i2, l2 + 1),
      0,
      0
    ],
    removeRow: () => o2 < 1 ? void 0 : [
      Jn(i2, c2),
      NaN,
      0
    ],
    removeColumn: () => s2 < 1 ? void 0 : [
      Yn(i2, l2),
      0,
      NaN
    ]
  }[n2]();
  if (u2 === void 0) return;
  let [d2, f2, p2] = u2, m2 = r2.row !== void 0 && r2.column !== void 0 && !Number.isNaN(f2 + p2);
  return {
    nodes: kn(e2, r2.table, () => d2),
    selection: m2 ? [
      ...r2.table,
      r2.row + f2,
      r2.column + p2
    ] : r2.table
  };
}

// ../slides/dist/index.js
function $2(e2, t2, n2, r2 = 600) {
  let i2 = globalThis;
  if (typeof i2.matchMedia == "function" && i2.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
  let a2 = e2.getBoundingClientRect(), o2 = t2.getBoundingClientRect(), s2 = o2.width / 1920 || 1, c2 = (e3, t3) => {
    let n3 = e3.getBoundingClientRect();
    return {
      x: (n3.left - t3.left) / s2,
      y: (n3.top - t3.top) / s2,
      w: n3.width / s2,
      h: n3.height / s2
    };
  }, l2 = (e3) => Array.from(e3.querySelectorAll("[id]")).filter((e4) => e4.closest("svg") === null), u2 = new Map(l2(e2).map((e3) => [e3.id, e3])), d2 = t2.closest(".deck-root"), f2 = i2.document.createElement("div");
  f2.className = "deck-root", f2.style.cssText = `${d2?.style.cssText ?? ""};position:absolute;left:0;top:0;width:1920px;height:1080px;pointer-events:none;z-index:10`;
  let p2 = i2.document.createElement("section");
  p2.className = "deck-slide", p2.style.cssText = "position:absolute;left:0;top:0;background:transparent;overflow:visible", f2.append(p2);
  let m2 = [];
  for (let e3 of l2(t2)) {
    let t3 = u2.get(e3.id);
    if (t3 === void 0) continue;
    let n3 = c2(t3, a2), s3 = c2(e3, o2), l3 = e3.cloneNode(true);
    l3.removeAttribute("id"), l3.style.position = "absolute", l3.style.left = `${s3.x}px`, l3.style.top = `${s3.y}px`, l3.style.width = `${s3.w}px`, l3.style.height = `${s3.h}px`, l3.style.margin = "0", l3.style.boxSizing = "border-box", l3.style.transformOrigin = "0 0", l3.style.flex = "none", p2.append(l3);
    let d3 = n3.h / (s3.h || 1), f3 = (e3.textContent ?? "").trim() === "" ? n3.w / (s3.w || 1) : d3;
    l3.animate([{
      transform: `translate(${n3.x - s3.x}px, ${n3.y - s3.y}px) scale(${f3}, ${d3})`,
      opacity: i2.getComputedStyle(t3).opacity
    }, {
      transform: "none",
      opacity: i2.getComputedStyle(e3).opacity
    }], {
      duration: r2,
      easing: "cubic-bezier(.4, 0, .2, 1)",
      fill: "both"
    }), m2.push(t3, e3);
  }
  if (m2.length !== 0) {
    for (let e3 of m2) e3.style.visibility = "hidden";
    n2.append(f2), i2.setTimeout(() => {
      f2.remove();
      for (let e3 of m2) e3.style.visibility = "";
    }, r2);
  }
}
var je2 = $2.toString();
export {
  tn as DECK_BASE_CSS,
  tt as DECK_BLOCK_TAGS,
  Qe as DECK_HEIGHT,
  F as DECK_ICONS,
  Je as DECK_ICON_NAMES,
  nt as DECK_INLINE_TAGS,
  je2 as DECK_MAGIC_MOVE_SOURCE,
  nn as DECK_MOTION_CSS,
  rt as DECK_SHAPE_KINDS,
  r as DECK_THEMES,
  e as DECK_THEME_ROLES,
  L as DECK_TRANSITIONS,
  Ze as DECK_WIDTH,
  n as MINIMAL_DARK,
  t as MINIMAL_LIGHT,
  Xn as TABLE_EDITS,
  On as childrenAt,
  yn as deckFontMarkup,
  Ye as deckIconBody,
  Xe as deckIconMarkup,
  $2 as deckMagicMove,
  Y as deckNodesText,
  bn as deckRootStyle,
  $t as deckSlideTitle,
  ze as deckStyleApplies,
  o as deckThemeStyle,
  M as decodeEntities,
  Zt as describeDeckDiagnostics,
  Zn as editTable,
  Vn as element,
  Dn as elementAt,
  P as escapeAttribute,
  N as escapeText,
  a as findDeckTheme,
  Nn as insertAt,
  qn as insertTableColumn,
  Kn as insertTableRow,
  xt as isAssetPath,
  k as isColor,
  St as isDeckImageSource,
  Re as isDeckStyleProperty,
  en as isDeckTextBlock,
  i as isDeckThemeId,
  wn as isWithin,
  En as nodeAt,
  Be as normalizeDeckStyleValue,
  Tn as parentOf,
  Sn as parsePathKey,
  Fn as patchNodeStyle,
  Pn as patchStyle,
  xn as pathKey,
  _t as readDeck,
  Et as readDeckCrop,
  Yt as readDeckNodes,
  Ne as readDeckStyle,
  C as readPixels,
  Mn as removeAt,
  Yn as removeTableColumn,
  Jn as removeTableRow,
  an as renderDeckNodes,
  _n as renderNodesHtml,
  vn as renderSlideHtml,
  d as resolveDeckColor,
  zn as rotationOf,
  Cn as samePath,
  In as setAttribute,
  O as splitTop,
  fn as strokeOf,
  f as styleTargetOf,
  Un as tableAt,
  Hn as text,
  l as themeRoleOf,
  Ft as tidyInline,
  Ue as tokenizeHtml,
  wt as uniqueId,
  kn as updateAt,
  An as updateChildrenAt,
  Ln as updateSlide,
  Rn as updateSlideChildren,
  Qt as walkDeckNodes,
  Bn as withRotation,
  u as withoutThemeReferences,
  qt as writeDeck,
  Jt as writeDeckNodes,
  Le as writeDeckStyle,
  Ut as writeInline
};
