import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

/**
 * Build the two files that carry `@jannchie/slides` into the plugin.
 *
 * The plugin installs nothing at runtime — the harness supplies its peers, and
 * the browser half's `require` reaches only what the module loader registered
 * (`react`, the primitives). So the deck library travels INSIDE the shipped
 * files rather than beside them:
 *
 * - `lib/deck.js` — the deck format (read, write, diagnose), for the host half's
 *   tool. No framework and no DOM.
 * - `lib/client.js` — `src/client.js`, the browser half, with the deck editor,
 *   the Vue it is written in, and its stylesheet bundled in.
 *
 * Both are generated and committed: CI and the publish workflow check and ship
 * the files as they stand, with no install step. Edit `src/client.js`, then run
 * `npm run build`.
 */

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const slides = dirname(createRequire(import.meta.url).resolve("@jannchie/slides/package.json"));

// The library's built entries — exactly where its published `exports` point,
// so this holds for a linked checkout and an installed release alike.
const alias = {
	"@jannchie/slides/editor": join(slides, "dist/editor.js"),
	"@jannchie/slides/style.css": join(slides, "dist/style.css"),
	"@jannchie/slides": join(slides, "dist/index.js"),
};

const banner = "// Generated by scripts/build.mjs — do not edit. The source is src/client.js and @jannchie/slides.";

await build({
	entryPoints: [alias["@jannchie/slides"]],
	outfile: join(root, "lib/deck.js"),
	bundle: true,
	format: "esm",
	platform: "neutral",
	target: "node20",
	legalComments: "none",
	banner: { js: banner.replace("src/client.js and ", "") },
	logLevel: "warning",
});

await build({
	entryPoints: [join(root, "src/client.js")],
	outfile: join(root, "lib/client.js"),
	bundle: true,
	format: "iife",
	platform: "browser",
	target: "es2022",
	alias,
	loader: { ".css": "text" },
	define: {
		"process.env.NODE_ENV": '"production"',
		__VUE_OPTIONS_API__: "true",
		__VUE_PROD_DEVTOOLS__: "false",
		__VUE_PROD_HYDRATION_MISMATCH_DETAILS__: "false",
	},
	// Minified: the readable source is src/client.js, and the editor and the Vue
	// inside it are most of the file a reader's browser downloads.
	minify: true,
	legalComments: "none",
	banner: { js: banner },
	logLevel: "warning",
});

console.log("built lib/deck.js and lib/client.js");
